### ISSUE TITLE
Use editor's tab length setting

### ISSUE THREAD

**Issue by gabmontes** [Glavin001/atom-beautify#644] opened 2015-11-05 14:04 UTC
It would be great if the indent size is taken from the editor's current setting when none is defined at package/global level.

**Comment by Glavin001** [comment] 2015-11-06 03:54
Actually this should already be the case. For example, JavaScript: https://github.com/Glavin001/atom-beautify/blob/master/src/languages/javascript.coffee#L3

I would recommend reading over https://github.com/Glavin001/atom-beautify/blob/master/CONTRIBUTING.md#new-issues-bugs-questions-etc and running the `Atom Beautify: Help Debug Editor` command. It will show you the different options that are combined to generate your final options that are used for beautification. Looking at it should show you if it is properly reading from your editor's settings, and also what else may be overwriting those settings later on in processing.

**Comment by flungo** [comment] 2016-11-17 18:22
I am having the same issue. I thought it was because I was using the default option (2) and so it wasn't explicitly set but even setting to 8 didn't seem to work.

**Comment by Glavin001** [comment] 2017-01-03 00:08
Closing as a duplicate of https://github.com/Glavin001/atom-beautify/issues/894

**Closed by Glavin001** 2017-01-03 00:08 UTC
Labels: question

**Comment by Glavin001** [comment] 2017-04-15 23:11
I've merged https://github.com/Glavin001/atom-beautify/pull/1598 which should resolve these issues.

Published to v0.29.21.
