### ISSUE TITLE
atom-beautify not allowing to save file when there is a syntax error on new update

### ISSUE THREAD

**Issue by jithinlal** [Glavin001/atom-beautify#1948] opened 2017-11-22 06:10 UTC
# Description

The atom-beautify package is not allowing my file to be saved, if there is any syntax error in my PHP file.

**Comment by bitgijs** [comment] 2017-11-22 08:21
same!

**Comment by johanvanhelden** [comment] 2017-11-22 09:13
Might be the same as: https://github.com/Glavin001/atom-beautify/issues/1949

With the difference being that mine does not save at all. Even if there are no errors.

**Comment by Jbz797** [comment] 2017-11-22 09:48
Same here !

**Comment by jithinlal** [comment] 2017-11-22 10:11
I mean is this an error in PHP, or any kind of language?

**Comment by eqfox** [comment] 2017-11-22 10:34
use eslint-fixer same problem~

**Comment by Glavin001** [comment] 2017-11-22 13:42
Closing as a duplicate of https://github.com/Glavin001/atom-beautify/issues/1949 , since it has more 👍 s.

**Comment by Glavin001** [comment] 2017-11-22 13:43
Bug in https://github.com/Glavin001/atom-beautify/pull/1924

**Closed by Glavin001** 2017-11-22 13:42 UTC

**Comment by Glavin001** [comment] 2017-11-22 14:38
Published the fix recommended by @exoticorn : https://github.com/Glavin001/atom-beautify/issues/1949#issuecomment-346347191

Patch version 0.30.8

Please try and let me know!

**Comment by johanvanhelden** [comment] 2017-11-22 14:48
Cheers @Glavin001 !

Just updated and everything works great again - it saves with and without beautifying.

**Comment by Glavin001** [comment] 2017-11-22 14:53
**Update**: Please try v0.30.9

**Comment by jithinlal** [comment] 2017-11-23 05:10
Its done now, working smoothly.
