### ISSUE TITLE
Support Stylus

### ISSUE THREAD

**Issue by wagnerferreira** [Glavin001/atom-beautify#525] opened 2015-08-25 17:37 UTC
When will support stylus(css)?

Thanks...

**Comment by Glavin001** [comment] 2015-08-25 18:21
> When will support stylus(css)?

Soonest possibility: when someone makes a Pull Request to support it.

**Comment by Glavin001** [comment] 2015-08-25 18:22
Duplicate of #318.

**Closed by Glavin001** 2015-08-25 18:22 UTC
Labels: add-language

**Comment by isuvorov** [comment] 2016-02-19 19:53
+1

**Comment by Mangor** [comment] 2016-06-20 02:26
+1

**Comment by jt3k** [comment] 2016-08-04 18:00
+1

**Comment by ckpinguin** [comment] 2016-12-15 14:41
+1

**Comment by sebatorresi** [comment] 2018-06-07 15:17
+1

**Comment by chepkasoff** [comment] 2019-02-01 13:42
+1 @ 2019

**Comment by jt3k** [comment] 2019-02-07 08:57
+1 @ 3019
