### ISSUE TITLE
Error using clang-format to format C code

### ISSUE THREAD

**Issue by anandsuresh** [Glavin001/atom-beautify#1413] opened 2016-12-15 18:31 UTC
# Description

Running beautify on a C file results in the following error:

```
EACCES: permission denied, open '.atom-beautify.undefined'
```

Only happens when I set the beautifier to use `clang-format` instead of `uncrustify`.

# Steps to Reproduce

1. Configure settings to have atom-beautify use `clang-format` as the default beautifier for C.
2. Run command `Atom Beautify: Beautify Editor`

# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/8ea99e9ec77ff7450e8288233698a55f

# Checklist

- [x] I have tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] I have reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched for existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [x] Generated debugging information and added link for `debug.md` Gist to this issue

**Comment by Glavin001** [comment] 2017-01-03 03:01
> > Here is a link to the `debug.md` Gist: https://gist.github.com/8ea99e9ec77ff7450e8288233698a55f
> 
> 2016-12-15T18:28:19.936Z - debug: [beautifiers/beautifier.coffee] dumpToFile .atom-beautify.undefined { Error: EACCES: permission denied, open '.atom-beautify.undefined'
    at Error (native)
  errno: -13,
  code: 'EACCES',
  syscall: 'open',
  path: '.atom-beautify.undefined' } undefined

Looks like the applicable code is:
- https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/clang-format.coffee#L67
- https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/clang-format.coffee#L25-L38

This was implemented in Pull Request https://github.com/Glavin001/atom-beautify/pull/546.
@ProgramFan may be the best person to assist with debugging this issue.

The simple answer is Atom does not have the appropriate permissions to the directory.

Try changing the permissions: http://stackoverflow.com/a/38324155/2578205

> `chmod a+w <folder>`

**Comment by ProgramFan** [comment] 2017-01-04 14:28
I can not reproduce the issue on macOS with atom 1.12.7. When the file is not saved, atom-beautify complains about no beautifiers. When the file is saved as test.c, the beautifier works correctly.

I don't know why your file get an name of 'undefined'. Maybe you have not created any project in atom yet? Even in that case, '.atom-beautify.undefined' shall be created correctly if you have write permission on the working dir.

So would you check your environment as in @Glavin001's reply?

**Comment by Glavin001** [comment] 2017-04-15 19:35
I'm closing this for now. It can be reopened once @anandsuresh replies to above comments.

**Closed by Glavin001** 2017-04-15 19:35 UTC
Labels: question
