### ISSUE TITLE
TSS: "Cannot read property 'indexOf' of undefined" when first line is empty

### ISSUE THREAD

**Issue by m1ga** [Glavin001/atom-beautify#1761] opened 2017-07-11 07:28 UTC
# Description

When I try to beautify a TSS file with an empty first row I'll receive an error:
`Cannot read property 'indexOf' of undefined`

Stacktrace:
```
Cannot read property 'indexOf' of undefined
    at jspretty__tokenize_space (/user/.atom/packages/atom-beautify/node_modules/prettydiff/lib/jspretty.js:1895:50)
    at jspretty__tokenize (/user/.atom/packages/atom-beautify/node_modules/prettydiff/lib/jspretty.js:2154:17)
    at jspretty_ (/user/.atom/packages/atom-beautify/node_modules/prettydiff/lib/jspretty.js:2430:6)
    at commonjs (/user/.atom/packages/atom-beautify/node_modules/prettydiff/lib/jspretty.js:5603:16)
    at core_ (/user/.atom/packages/atom-beautify/node_modules/prettydiff/prettydiff.js:2356:41)
    at prettydiff_ (/user/.atom/packages/atom-beautify/node_modules/prettydiff/prettydiff.js:2484:12)
    at Object.commonjs [as api] (/user/.atom/packages/atom-beautify/node_modules/prettydiff/prettydiff.js:2520:16)
    at /user/.atom/packages/atom-beautify/src/beautifiers/prettydiff.coffee:130:27
    at Promise._execute (/user/.atom/packages/atom-beautify/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/user/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/user/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:79:10)
    at PrettyDiff.module.exports.PrettyDiff.beautify (/user/.atom/packages/atom-beautify/src/beautifiers/prettydiff.coffee:75:16)
    at /user/.atom/packages/atom-beautify/src/beautifiers/index.coffee:354:28
    at tryCatcher (/user/.atom/packages/atom-beautify/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/user/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/user/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromiseCtx (/user/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:606:10)
    at Async._drainQueue (/user/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (/user/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:143:10)
    at Async.drainQueues (/user/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:17:14)
```

TSS (input - first line is empty):
```

".icon_btn" : {
width: 40,
height: 40
}
".icon" : {
font: {
fontSize: 30
}
}
```

If I remove the first blank line it is working fine:
TSS (output with no empty first line):
```
".icon_btn" : {
	width: 40,
	height: 40
}
".icon" : {
	font: {
		fontSize: 30
	}
}
```

Atom: 1.18.0 (OSX)
atom-beautify: 0.30.3

**Comment by prettydiff** [comment] 2017-07-11 11:29
Thank you for this.  I am looking into it.

**Comment by prettydiff** [comment] 2017-07-11 11:41
I can produce the error exactly to the same line number mentioned in the stack trace.  In the latest version of Pretty Diff the same error is coming from line number 2126.  The problem is solved by changing the line in question

from: `if (token[lengtha - 1].indexOf("//") === 0) {`

to: `if (lengtha > 0 && token[lengtha - 1].indexOf("//") === 0) {`

**Comment by prettydiff** [comment] 2017-10-10 13:09
This appears to be resolved in the latest version of Pretty Diff which is in Atom Beautify.

**Closed by prettydiff** 2017-10-10 13:09 UTC
Labels: third-party-bug
