### ISSUE TITLE
Recursive folder option

### ISSUE THREAD

**Issue by robertbaker** [Glavin001/atom-beautify#373] opened 2015-05-28 00:02 UTC
It would be nice to beautify multiple files at once.

**Comment by Glavin001** [comment] 2015-05-28 00:42
Duplicate of #36.

This feature has been disabled because in some cases it can cause detrimental errors when working with a large number of files. You can join the discussion #213. Hopefully this will be added back soon.

**Closed by Glavin001** 2015-05-28 00:42 UTC
Labels: duplicate
