### ISSUE TITLE
  ### Stack Trace  Uncaught TypeError: Cannot read property 'setScrollTop' of null  

### ISSUE THREAD

**Issue by raj7desai** [Glavin001/atom-beautify#1126] opened 2016-08-10 00:17 UTC
# Description

The results of beautification are not what I expect.

# Expected Results

The beautified code should have looked like:

```
<INSERT CODE HERE>
```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/2ba51f3caf83a29eec547acde098c3d3

# Checklist

- [ ] I have tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] I have reloaded (or restarted) Atom to ensure it is not a caching issue
- [ ] Searched for existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [ ] Generated debugging information and added link for `debug.md` Gist to this issue

**Comment by prettydiff** [comment] 2016-08-11 10:36
Related to https://github.com/Glavin001/atom-beautify/issues/977

**Comment by DerivcoHK** [comment] 2016-08-16 02:48
dead loop with js beautify on save , 
this error pop on closing the tab

**Comment by prettydiff** [comment] 2016-08-16 11:38
@DerivcoHK Those sound like two separate and unrelated defects.  Would you mind opening an issue for the JS Beautify loop on save?

**Comment by elliottregan** [comment] 2016-08-18 15:50
I thought that it might be trying to add a new line, and take it away, based on what happens to my cursor. I do have "end_with_newline": false set in my .jsbeautifyrc file.

Also, when the error does happen, the last line gets removed. When it doesn't happen, the last line is there.

I can "fix" it by restarting Atom.

**Comment by Glavin001** [comment] 2016-09-30 13:34
Duplicate of #977 and #1181.

**Closed by Glavin001** 2016-09-30 13:34 UTC

**Comment by raj7desai** [comment] 2016-10-07 15:14
Will follow up with the related issues. Thanks :)
