### ISSUE TITLE
Object.dirname is deprecated.

### ISSUE THREAD

**Issue by steronydh** [Glavin001/atom-beautify#1509] opened 2017-02-09 10:18 UTC
Atom 1.14
atom-beautify 0.29.17

Argument to `path.dirname` must be a string
```
Object.dirname (C:\Users\steronydh\AppData\Local\atom\app-1.14.0\resources\app.asar\src\electron-shims.js:9:10)
Promise.then.lang (C:\Users\steronydh\.atom\packages\atom-beautify\src\beautifiers\uncrustify\index.coffee:60:29)
Promise._execute (C:\Users\steronydh\.atom\packages\atom-beautify\node_modules\bluebird\js\release\debuggability.js:300:9)
Promise._resolveFromExecutor (C:\Users\steronydh\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:481:18)
new Promise (C:\Users\steronydh\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:77:14)
Uncrustify.beautify (C:\Users\steronydh\.atom\packages\atom-beautify\src\beautifiers\uncrustify\index.coffee:47:14)
```

**Comment by prettydiff** [comment] 2017-02-09 11:26
Duplicate of #1423

**Closed by prettydiff** 2017-02-09 11:26 UTC
Labels: duplicate
