### ISSUE TITLE
Coldfusion language

### ISSUE THREAD

**Issue by jasongutt** [Glavin001/atom-beautify#526] opened 2015-08-28 21:54 UTC
Please add support to the beautifier for "HTML (CFML)" and extension "cfm"

**Comment by prettydiff** [comment] 2015-09-02 12:44
First read some of the final comments here: https://github.com/Glavin001/atom-beautify/issues/354

Secondly, I may add support for CFML so long as it is more a markup language than something resembling JavaScript, Java, or Python.  Do you have code samples I can look at, possibly creating a gist?  It has been about a decade since I have looked at CF code.

**Comment by jasongutt** [comment] 2015-09-02 13:17
https://gist.github.com/jasongutt/139c5b88cac46f93c780

**Comment by prettydiff** [comment] 2015-09-02 13:57
Exactly what I was looking for. I will need to add support for:

* create a new type in the parser `pragma`, which will include SGML tags, XML pragmas, and: cfset, cfhttp
* cfelse needs to be added as a template "else" type in my parser.
* self-closing tags:  cfinput, cfgridcolumn, cfset, cfinclude, cfimport

I am having trouble finding a comprehensive list of CF11 tags and then having more diffecultly still determining which of those tags does not require an end tag.  If I know which tags are self-closing tags I can ensure they are treated as self-closing tags even if they end with `>` instead of `/>`.

The parser will not be intelligent enough to know if a custom tag should be self-closing by tag name alone.  These tags will be treated as self-closing tags if they terminate with `/>` otherwise they will be start tags that increase indentation.

**Comment by prettydiff** [comment] 2015-09-02 15:09
I will be performing all following work at: https://github.com/prettydiff/prettydiff/issues/158

**Comment by Glavin001** [comment] 2015-11-19 21:39
Closing as duplicate of #354.

**Closed by Glavin001** 2015-11-19 21:39 UTC

**Comment by Glavin001** [comment] 2016-03-21 16:56
Published to v0.28.23
