### ISSUE TITLE
Add grammar for .html.eex

### ISSUE THREAD

**Issue by brentjanderson** [Glavin001/atom-beautify#1401] opened 2016-12-07 03:03 UTC
Eex (Embedded Elixir) is used to inline Elixir in HTML (and possibly other languages). HTML formatted as Eex may work if treated as normal HTML when being beautified.

An existing grammar for Atom document recognition and colorization is here: https://github.com/elixir-lang/language-elixir

_(I searched for a matching issue and found none containing "eex")_

**Comment by prettydiff** [comment] 2016-12-07 09:26
I believe this is a duplicate of https://github.com/Glavin001/atom-beautify/issues/1383

**Closed by prettydiff** 2016-12-07 09:26 UTC
Labels: duplicate
