### ISSUE TITLE
beautify on save adds > behind </html> tag

### ISSUE THREAD

**Issue by ikeamanual** [Glavin001/atom-beautify#1236] opened 2016-09-30 15:04 UTC
# Description

HI,

When I have invalid html, by removing the second " of the href, and do Ctrl-S, an extra > is added behind the </html> tag. Like so:
```
<html>

    <body>
        <a href="#>link</a> </body>

</html>
>
```
If I right-click and choose beautify, it works ok. So it has something to do with the beautify on save option...

# Expected Results

The beautified code should have looked like:

```
<html>

    <body>
        <a href="#>link</a> </body>

</html>
```

# Steps to Reproduce

1. Add code to Atom editor, with missing end "
2. Ctrl-S  ( with auto save on )
3. an > is added behind </html>

# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/2ce03368bcc78bad7660e11ef186282f

# Checklist

- [ x] I have tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [ x] I have reloaded (or restarted) Atom to ensure it is not a caching issue
- [ x] Searched for existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [ x] Generated debugging information and added link for `debug.md` Gist to this issue

**Comment by prettydiff** [comment] 2016-09-30 15:32
I could not reproduce on http://jsbeautifier.org/ so I am wondering if this is somehow related to https://github.com/Glavin001/atom-beautify/issues/1213

I am not sure where the defect is coming from, so for now I will mark as a bug to be extra defensive.

**Comment by Glavin001** [comment] 2016-09-30 16:43
I'm going to close this as a duplicate of https://github.com/Glavin001/atom-beautify/issues/1213

It definitely appears to be an issue with `Beautify On Save` and not specific to HTML, JavaScript, or any one beautifier.

**Closed by Glavin001** 2016-09-30 16:43 UTC
Labels: bug, duplicate
