### ISSUE TITLE
Beautify HTML within PHP

### ISSUE THREAD

**Issue by streamworksaudio** [Glavin001/atom-beautify#1204] opened 2016-09-18 17:58 UTC
Hi,

Thanks for this great package!  

I was wondering, is it possible (or is planned) to select some HTML within a PHP file and beautify it using the HTML beautifiers? 

Cheers

**Comment by vnt** [comment] 2016-12-10 13:09
I need html + php, how do you activate it?

**Comment by Glavin001** [comment] 2017-01-03 01:14
Looks like a duplicate of https://github.com/Glavin001/atom-beautify/issues/457 feature request.

**Closed by Glavin001** 2017-01-03 01:14 UTC
Labels: question
