### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by k3rn31** [Glavin001/atom-beautify#198] opened 2015-01-30 22:00 UTC
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:53:11)
LoadingView.module.exports.LoadingView.show (/Users/davide/.atom/packages/atom-beautify/lib/loading-view.coffee:38:11)
```

**Comment by Glavin001** [comment] 2015-02-03 21:02
Duplicate of #191.

**Closed by Glavin001** 2015-02-03 21:02 UTC
Labels: deprecated-atom-api, high priority
