### ISSUE TITLE
Support for Groovy

### ISSUE THREAD

**Issue by brennonobst** [Glavin001/atom-beautify#969] opened 2016-05-10 18:26 UTC
### Description

Groovy syntax missing
### Expected Results

The beautified code should have looked like: 

```
node{
  withGitCredentials { 
    stage 'checkout' 
    checkout scm 
    stage 'export' 
    shell '''
      export PYENV_ROOT=/opt/pyenv export
      PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games '''
    stage 'docker poop' 
    shell ''' docker --debug=true ps -a -q | xargs -r docker
      --debug=true rm -f -v docker --debug=true images -q | xargs -r docker
      --debug=true rmi -f || true docker --debug=true run --rm --workdir /app --volume
      `pwd`:/app python:2.7 make distclean ''' 
    stage 'make develop' 
    shell ''' 
      time make develop . build/venv/bin/activate ''' stage 'make systemtest' time make
      PYTEST_FLAGS="-s --junit-xml build/systemtest.junit" systemtest ''' 
  }
}
```

 beautified but I got:

```
node{ withGitCredentials { stage 'checkout' checkout scm stage 'export' shell '''
export PYENV_ROOT=/opt/pyenv export
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games '''
stage 'docker poop' shell ''' docker --debug=true ps -a -q | xargs -r docker
--debug=true rm -f -v docker --debug=true images -q | xargs -r docker
--debug=true rmi -f || true docker --debug=true run --rm --workdir /app --volume
`pwd`:/app python:2.7 make distclean ''' stage 'make develop' shell ''' time
make develop . build/venv/bin/activate ''' stage 'make systemtest' time make
PYTEST_FLAGS="-s --junit-xml build/systemtest.junit" systemtest ''' }
}

```
### Steps to Reproduce
1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

**Comment by Glavin001** [comment] 2017-01-02 16:00
This issue is a duplicate of https://github.com/Glavin001/atom-beautify/issues/371

**Closed by Glavin001** 2017-01-02 16:00 UTC
