### ISSUE TITLE
Make spyware opt in or delete

### ISSUE THREAD

**Issue by beautispy** [Glavin001/atom-beautify#919] opened 2016-04-14 16:36 UTC
It's so sad such a great plugin has to be destroyed on default with spyware. The stuff your collecting is not okay.  I saw my cached files sending ash keys and passwords because of another plugins configuration to you.  Especially since third parties are involved I think this needs to be opt out.

Can I fork the code and remove all the spyware? Would that be okay with you? I don't want others to experience issues like this.

Thanks.

**Comment by Glavin001** [comment] 2016-04-14 23:53
> The stuff your collecting is not okay. I saw my cached files sending ash keys and passwords because of another plugins configuration to you.

I'm not sure what you are talking about with regards to cached files, SSH (ash?) keys and passwords. Maybe another package?

Note that Atom-Beautify *does* track some usage information, specifically regarding what language you are beautifying with.
The applicable code can be found at: https://github.com/Glavin001/atom-beautify/blob/c43556f6366c4dc1e85ba363b6c5dc24a21e79f9/src/beautifiers/index.coffee#L284-L308

```
 analytics.track
            userId : atom.config.get("atom-beautify.general._analyticsUserId")
            event : "Beautify"
            properties :
              language : language?.name
              grammar : grammar
              extension : fileExtension
              version : version
              options : allOptions
              label : language?.name
              category : version
```

This is very useful for seeing which languages are more popular and therefore should be prioritized for support (since time is very limited) and also if users are upgrading to the latest releases, etc.

@prettydiff articulates the position I agree with in his comment: https://github.com/Glavin001/atom-beautify/issues/565#issuecomment-210078645

> Especially since third parties are involved I think this needs to be opt out.

Yes, analytics in Atom-Beautify will continue to be opt-out.

For those interested in disabling analytics, feel free to do so quickly and easily by changing the `Anonymous Analytics` setting in Atom-Beautify package settings:
![image](https://cloud.githubusercontent.com/assets/1885333/14547124/06b3f468-0281-11e6-812b-fa76bd204282.png)

---

I am closing this issue as a duplicate of https://github.com/Glavin001/atom-beautify/issues/565#issuecomment-210078645

**Comment by Glavin001** [comment] 2016-04-15 00:20
For those interested in this issue, I would be open to reviewing and merging a Pull Request that implements all the following changes:
- [ ] Change default value of `analytics` in `general` group to `false`
  - See file: https://github.com/Glavin001/atom-beautify/blob/c43556f6366c4dc1e85ba363b6c5dc24a21e79f9/src/config.coffee#L9
- [ ] Add option `_analyticsExplained` to `general` group
  - See file: https://github.com/Glavin001/atom-beautify/blob/c43556f6366c4dc1e85ba363b6c5dc24a21e79f9/src/config.coffee#L2
  - Option details:
    - description: Verify that the user has seen the analytic explanation notification
    - type: `boolean`
    - default: `false`
- [ ] In `beautify` method of `Beautifiers` class, check if `atom?.config.get('atom-beautify.general._analyticsExplained')` is `false` 
  - See file: https://github.com/Glavin001/atom-beautify/blob/c43556f6366c4dc1e85ba363b6c5dc24a21e79f9/src/beautifiers/index.coffee#L284-L285 
  - If it is `false` then
    - Create a notification with `addWarning`
      - See https://atom.io/docs/api/v1.7.0/NotificationManager 
      - `dismissible=true` such that Users must read, acknowledge it and dismiss it manually
      - `detail` = The message should describe what is being sent in the analytics, why it is important, and how users can easily disable analytics (Atom-Beautify package settings -> General -> Analytics, toggle off)
      - Set `general._analyticsExplained` to `true`
  - If it is `true` then we already have told users about analytics and how they can disable it. Continue to beautify and send analytics until they opt out / disable analytics, as instructed.


With the above, it guarantees that everyone has been notified about Atom-Beautify's analytics once and they know they can quickly and easily disable it if they want to :+1:.

---

The many contributors of Atom-Beautify are working towards a great project that meets their expectations. We are taking time away from our friends, family, school, and work to do so.
If this issue is important to you then the onus is on you to contribute (via submitting a Pull Request) with us and develop a project that everyone can be happy with. Thank you.

**Closed** 2016-04-15 00:21 UTC
Labels: duplicate, question

**Comment by Glavin001** [comment] 2016-04-15 02:28
Please note that I just removed the `options: allOptions` field of the payload used for analytics tracking.
This change will be in the next release.

As said in the commit message:
> Originally tracking `options` was intended to help with debugging errors, and making sure Atom-Beautify was working for the users.
However, we now have that `Help Debug Editor` command that users can use on their own when submitting an Issue for Atom-Beautify on GitHub.
Thus, tracking the `options` is not being used for analytics (yet) and it is more advantageous to remove to reduce the information being tracked.

Now all that is tracked is basically what language you are using, and related information such as file extension. For instance, because Atom-Beautify tracks the extension, if it turns out that the language is detected as "None" and the extension is something that can be recognized later as an extension for a particular language, it indicates that users would likely want support for that language or at least add that extension to be mapped to the language within Atom-Beautify.

**Comment by jbreckmckye** [comment] 2016-04-15 15:36
The entitlement of OSS end users is frankly staggering. If you are using someone's tooling for free, you have no right to unilaterally demand they implement new behaviour and jettison anonymized analytics data vital to the project's upkeep. If you want the software to behave differently, submit a pull request of your own.

If you expect the vendors of your tools to service these kind of shrieking, aggressive requests in future, I would suggest you actually try paying for your tooling.
