### ISSUE TITLE
Can't select words.. if i disable the atom-beautify.. then no problem

### ISSUE THREAD

**Issue by SachinKodagoda** [Glavin001/atom-beautify#1803] opened 2017-08-10 05:46 UTC
# Description

The results of beautification are not what I expect.

# Input Before Beautification

This is what the code looked like before:

```
<INSERT CODE HERE>
```

# Expected Output

The beautified code should have looked like this:

```
<INSERT CODE HERE>
```

# Actual Output

The beautified code actually looked like this:

```
<INSERT CODE HERE>
```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Debug

Here is a link to the `debug.md` Gist: <INSERT GIST HERE>

# Checklist

I have:
- [ ] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [ ] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [ ] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [ ] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [ ] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by szeck87** [comment] 2017-08-10 17:57
Hi SachinKodagoda, can you please post the version of Atom you are running along with your OS?  Steps to reproduce would also be helpful.

**Comment by SachinKodagoda** [comment] 2017-08-11 08:47
OS: Windows10 with latest update
Atom Version: latest version (updated)
the problem occurs only when "beautify on save" is selected

**Comment by SachinKodagoda** [comment] 2017-08-11 08:58
words seems like blinking. can't select anything on that page.
if i remove beautify on save or disable the atom-beautify the problem is fine..

**Comment by szeck87** [comment] 2017-08-11 16:39
Thanks. Caused by https://github.com/Glavin001/atom-beautify/issues/1721. A temporary workaround is to disable beautify on save and do it via the menu command. Fix should be ready soon.

**Comment by Glavin001** [comment] 2017-08-12 01:25
This is caused by https://github.com/Glavin001/atom-beautify/issues/1721 . I will close this as a duplicate.

Workaround: disable "Beautify On Save" until fixed.

Upcoming fix: https://github.com/Glavin001/atom-beautify/pull/1804

**Comment by Glavin001** [comment] 2017-08-12 01:25
Published to v0.30.5

**Closed by Glavin001** 2017-08-12 01:25 UTC
