### ISSUE TITLE
beautifying toggles trailing comma instead of consistently inserting it

### ISSUE THREAD

**Issue by nicolasartman** [Glavin001/atom-beautify#1087] opened 2016-07-24 01:09 UTC
# Description

Beautifying the file resulted in the trailing comma on a list being inserted/removed on every other beautify run, despite the setting clearly saying it should simply be inserted if absent.
# Expected Results

The beautified code should have looked like:

N/A
# Steps to Reproduce
1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor` multiple times
3. Observe that the trailing comma in the proptypes appears/disappears on alternating beautify runs rather than simply being inserted and staying there.
# Debug

Here is a link to the `debug.md` Gist on the first run (where the comma is added): https://gist.github.com/anonymous/d8d49d89c78e2fbcc8001ad05db1ad92

and the second where it is removed:
https://gist.github.com/anonymous/231cf29e7475bae12895c35fc93dad42
# Checklist
- [x] I have tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] I have reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched for existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
  so I know this is not a duplicate issue
- [x] Generated debugging information and added link for `debug.md` Gist to this issue

Thanks for the excellent tool! All of my other rules are working wonderfully.

**Comment by prettydiff** [comment] 2016-07-24 02:16
I can reproduce the defect in Atom Beautify but not elsewhere.  Atom Beautify currently uses version 1.16.37 of Pretty Diff which is a few months behind.  It is the last stable version in NPM.  Pretty Diff will be updated in Atom Beautify once I can find an alternative to NPM.... which I am working on right now at https://github.com/prettydiff/biddle

**Comment by nicolasartman** [comment] 2016-07-24 08:52
thanks for the super quick reply! in the meantime, is there an easy way i could just not use that option? leaving it unchecked/setting it to false actually consistently removes the trailing comma. It's ok if i have to add trailing commas myself, but I'd like to be able to beautify with prettydiff without it being auto-removed.

**Comment by prettydiff** [comment] 2016-07-24 12:23
Unfortunately, no.  At the present Pretty Diff always ensure the trailing comma is either absent or present for consistency (provided there is no defect in Pretty Diff).  A third option could be added to leave this alone, but it would still require an update to Pretty Diff, so either way you are still waiting on a distribution solution.

The manual resolution is to clone the Pretty Diff project and copy those files over Atom Beautify's Pretty Diff files.

* In POSIX it is something like .atom/packages/atom-beautify/node_modules/prettydiff
* in Windows it is something like appData/atom/packages/atom-beautify/node_modules/prettydiff

**Comment by nicolasartman** [comment] 2016-07-25 02:47
Gotcha. Any chance this plugin could simply fetch prettydiff on install (directly) or bundle it in? I would love to use the latest prettydiff but manually patching each system on my team doesn't sound great.

**Comment by prettydiff** [comment] 2016-07-25 03:39
The application I am working on is far from complete, but here is how it will basically work.

* It will have a publish command to compress a directory into a zip file and add the publication to a list of publications by application name with a list of published versions.  Along with the zip file a hash file will also be written.
* It will have an install command which will request a published resource and its hash file across HTTP.  The downloaded zip file will be hashed and this hash will be compared against the hash in the downloaded hash file.  If the hashes match the zip file will be unzipped to a location of your choosing and added to a list of installed applications by name and then by version number.  Otherwise, the zip will be moved to a downloads location for manual action and an error will be thrown.
* There will be other features as well, but the above points are the primary goals.

**Comment by nicolasartman** [comment] 2016-07-25 06:40
I think it's awesome you're creating a better alternative to a system that may be going about it wrong, but I would love to be able to use this excellent atom plugin with prettydiff in the meantime if there's a way to do so without forking it :)

**Comment by nicolasartman** [comment] 2016-07-26 03:28
I actually manually updated my local install to prettydiff 2.1 and the inconsistency actually still seems to be there. Must be an issue purely with atom-beautify.

**Comment by Glavin001** [comment] 2016-07-26 12:58
@nicolasartman have you reloaded Atom since updating?

**Comment by nicolasartman** [comment] 2016-07-26 17:24
yep. reloaded, restarted, rebooted, and reinstalled from scratch and re-patched! I'll edit the beautify script to log some stuff and see if I can get any insight.

On a related note, I tried pasting the following into the website ui for prettydiff to beautify and it complains about an unterminated regex despite correctly noticing that it's JSX. I note this because this is a file I've been using to test the comma behavior.

```
import React from 'react';
import classes from './Counter.scss';

export const Counter = (props) => (
  <div>
    <h2 className={classes.counterContainer}>Counter: {' '}
      <span className={classes['counter--green']} test="true">
        {props.counter}
      </span>
    </h2>
    <button className="btn btn-default" onClick={props.increment}>
      Increment
    </button>
    {' '}
    <button className="btn btn-default" onClick={props.doubleAsync}>
      Double (Async)
    </button>
  </div>
);

Counter.propTypes = {
  doubleAsync: React.PropTypes.func.isRequired,
  increment: React.PropTypes.func.isRequired,
  counter: React.PropTypes.number
};

export default Counter;
```

**Comment by prettydiff** [comment] 2017-10-10 16:32
Latest version of Pretty Diff has landed in Atom Beautify, which I believe resolves this issue.  If I am in error please reopen it.

**Closed by prettydiff** 2017-10-10 16:32 UTC
