### ISSUE TITLE
Support for QML

### ISSUE THREAD

**Issue by pierremtb** [Glavin001/atom-beautify#541] opened 2015-09-09 14:09 UTC
This would be awesome.

**Comment by prettydiff** [comment] 2015-09-09 21:30
https://github.com/Glavin001/atom-beautify/wiki/Requesting-support-for-a-new-language

Do you know where I could find more information about QML?

**Comment by prettydiff** [comment] 2015-09-09 21:35
https://en.wikipedia.org/wiki/QML

Assuming that is the same language it looks similar to JSON, except new line characters or semicolons separate list items instead of commas.  Provided the syntax is as clean and minimal as confined to those code samples and there is not grammar dependent variance an existing JSON beautifier could be modified to support this language.  This is not on my agenda though.

**Comment by nohe427** [comment] 2015-09-24 16:19
I would like to request this enhancement as well

**Comment by vrince** [comment] 2016-02-25 16:15
It almost work in fact, I notice that ending each line with ";" give expected result with javascript model.
But ending ; is optional in qml ...

Is there guide lines to implement / contribute a new model into prettydiff ?

**Comment by prettydiff** [comment] 2016-02-25 17:05
@vrince No, I have failed to write contribution documentation.  I need to write this and it to the project's documentation page.

I would need to write a new option for the tool so that the application specifically knows the language is QML.  This would allow me to write custom extensions without massive regression into everything else.

The key technical qualities to consider

* The default property separator is line termination
* Semicolons optionally separate properties without need for line termination
* I must deliberately not employ the automatic semicolon insertion that I enforce on JavaScript

I do have a question though.  Look at the first example at https://en.wikipedia.org/wiki/QML#States  Do you see that a block is declared to `states:` with a colon where the other block declarations do not have a colon.  What does this mean?  I gather from the text that it is a declaration of `states` which is probably a sort of dynamic or transitive typing compared to the other declarations.

**Comment by vrince** [comment] 2016-02-26 16:29
@prettydiff qml allow list of children (massively use in qt3d project for example)

see for exemaple : http://doc.qt.io/qt-5/qt3drenderer-scene3d-animatedentity-qml.html 
 
    ...
    Entity {
        id: sphereEntity
        components: [ sphereMesh, material, sphereTransform ]
    }

Note: qml allow shader / js code as string do you think this could be complex to handle ?

Exemple : http://doc.qt.io/qt-5/qt3drenderer-deferred-renderer-qml-sceneeffect-qml.html
(See `vertexShaderCode: ...`)

**Comment by prettydiff** [comment] 2016-02-26 17:03
@vrince Those strings would be something else to account for.  They are multiline strings.  Normally I would identify such as a parse error, because they are a parse error in JavaScript.  I could extend the code to support this though.

**Comment by prettydiff** [comment] 2016-02-26 17:05
@vrince Could you move all further discussion to https://github.com/prettydiff/prettydiff/issues/278 so that I can these technical items when I start working on this.

**Comment by marco-piccolino** [comment] 2016-04-13 20:21
would love to see this

**Comment by ldanzinger** [comment] 2016-04-13 20:26
would also like this

**Comment by prettydiff** [comment] 2016-06-28 23:23
QML support is added to the 2.1.0 branch of prettydiff if you guys would like to test it out.

**Comment by marco-piccolino** [comment] 2016-06-29 05:57
Awesome thank you, will check it out!
Il 29 giu 2016 1:23 AM, "Austin Cheney" <notifications@github.com> ha
scritto:

**Comment by vrince** [comment] 2016-06-29 15:53
Nice ! testing it today :)

**Comment by prettydiff** [comment] 2017-10-10 16:54
I can not reproduce the latest defects as mentioned in https://github.com/Glavin001/atom-beautify/issues/541#issuecomment-229400911 and the latest version of Pretty Diff recently landed in Atom Beautify.

**Closed by prettydiff** 2017-10-10 16:54 UTC
Labels: add-language
