### ISSUE TITLE
Could not find 'php'. The program may not be installed.

### ISSUE THREAD

**Issue by modytiger123** [Glavin001/atom-beautify#768] opened 2016-01-24 20:41 UTC
Hey, Please help after installing php-cs-fixer and setting default path it doesn't give me any errors about it but now it gives me this

Error: Could not find 'php'. The program may not be installed.
    at PHPCSFixer.module.exports.Beautifier.commandNotFoundError (file:///C:/Users/Mohammed/.atom/packages/atom-beautify/src/beautifiers/beautifier.coffee:178:14)
    at file:///C:/Users/Mohammed/.atom/packages/atom-beautify/src/beautifiers/beautifier.coffee:274:25
    at tryCatcher (C:\Users\Mohammed\AppData\Local\atom\app-1.4.0\resources\app.asar\node_modules\babel-core\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._settlePromiseFromHandler (C:\Users\Mohammed\AppData\Local\atom\app-1.4.0\resources\app.asar\node_modules\babel-core\node_modules\bluebird\js\main\promise.js:507:31)
    at Promise._settlePromiseAt (C:\Users\Mohammed\AppData\Local\atom\app-1.4.0\resources\app.asar\node_modules\babel-core\node_modules\bluebird\js\main\promise.js:581:18)
    at Promise._settlePromises (C:\Users\Mohammed\AppData\Local\atom\app-1.4.0\resources\app.asar\node_modules\babel-core\node_modules\bluebird\js\main\promise.js:697:14)
    at Async._drainQueue (C:\Users\Mohammed\AppData\Local\atom\app-1.4.0\resources\app.asar\node_modules\babel-core\node_modules\bluebird\js\main\async.js:123:16)
    at Async._drainQueues (C:\Users\Mohammed\AppData\Local\atom\app-1.4.0\resources\app.asar\node_modules\babel-core\node_modules\bluebird\js\main\async.js:133:10)
    at MutationObserver.Async.drainQueues (C:\Users\Mohammed\AppData\Local\atom\app-1.4.0\resources\app.asar\node_modules\babel-core\node_modules\bluebird\js\main\async.js:15:14)
    at process._tickCallback (node.js:368:9)

**Comment by prettydiff** [comment] 2016-01-24 22:31
Appears to be a duplicate of https://github.com/Glavin001/atom-beautify/issues/753

**Comment by modytiger123** [comment] 2016-01-25 22:03
Oh, Thanks dude ! ^_^

**Comment by modytiger123** [comment] 2016-01-25 22:07
Umm, My mistake but i only read titles :smile:

**Closed** 2016-06-02 02:10 UTC
Labels: duplicate

**Comment by Glavin001** [comment] 2017-06-04 18:26
I really want to focus on improving the installation experience for users. I have created a new Issue, #1687, to target this problem. Please provide your feedback! Thanks in advance.
