### ISSUE TITLE
HTML5 void elements in Swig

### ISSUE THREAD

**Issue by ttsirkia** [Glavin001/atom-beautify#463] opened 2015-07-17 15:51 UTC
If I have markup like this in a Swig file:
```html
<div>
  <img>
  <img>
</div>
```

The result will be:
```html
<div>
  <img>
    <img></div>
```

It seems that it cannot handle the HTML5 void elements correctly. However, If I manually change the language to HTML, everything works and the result is the expected.

If I understood correctly, the Swig formatter uses the same formatter as HTML, ie. there is no special formatter for Swig. What could cause this difference?

**Comment by ttsirkia** [comment] 2015-07-17 16:07
OK, it seems that it is using `prettydiff` in this case. And the reason for this problem is in `prettydiff.coffee`:

```
        when "SGML", "Swig"
          lang = "markup"
```

**Comment by ttsirkia** [comment] 2015-07-17 16:20
This seems to work:
```
        when "Handlebars", "Mustache", "Spacebars", "Swig"
          lang = "handlebars"
```

**Comment by Glavin001** [comment] 2015-07-17 20:20
Looks like `Swig` was put under `markup` instead of `handlebars` Pretty Diff syntax? Great, easy fix!

I would love to merge a Pull Request for this. Thanks in advance.

**Comment by ttsirkia** [comment] 2015-07-17 20:21
I can create a PR. I'm just wondering that does this cause some other problems that I haven't noticed...

**Comment by Glavin001** [comment] 2015-07-17 20:23
If you submit a Pull Request, Travis CI and AppVeyor will test it for you.

It should not cause any problems for other languages, only for Swig.

@prettydiff would you saw `Swig` should be `handlebars` or `markup`?

**Comment by ttsirkia** [comment] 2015-07-17 20:24
Yeah. Question is that does this change some other formatting issues in Swig templates in a way that something will break... Unit tests won't probably notice these issues.

**Comment by Glavin001** [comment] 2015-07-17 20:25
If the Unit tests don't notice it then @prettydiff is the only one who could answer that for you.

**Comment by prettydiff** [comment] 2015-07-17 20:52
The markup code in question is being evaluated with XML rules instead of HTML rules.  The HTML rules would internally reclassify something like `<img>` from a start tag to a self-closing tag.

The bigger challenge here, given this specific code sample, is that I don't have enough information from the markup to say that this should be XML or HTML.  You can force the later by setting prettydiff's `html` option to true.

**Comment by ttsirkia** [comment] 2015-07-17 20:54
That was a piece of HTML5 markup.

**Comment by ttsirkia** [comment] 2015-07-17 20:58
The most important question is that what is the difference between `handlebars` and `html`. I chose `handlebars` because also Swig templates have markup such as `{{ myVariable }}` in a same way as in `handlebars`.

**Comment by prettydiff** [comment] 2015-07-17 21:00
I could guess it is HTML code by looking at the tag names, but it would increase my risk profile to make this assumption a precedent for a large application given that, in this example, there are only two tag names that could easily exist in either HTML or XML.

I really need to create support for something like a `.jshintrc` file so that users can store configurations and force any conventions they wish in a location that is stored and easily available.

**Comment by ttsirkia** [comment] 2015-07-17 21:03
Yes, it is HTML. In HTML5 elements `area, base, br, col, command, embed, hr, img, input,
keygen, link, meta, param, source, track, wbr` can be so that they are not closed, as in example - they are called void elements. In `markup` mode `prettydiff` cannot handle this.

**Comment by prettydiff** [comment] 2015-07-17 21:03
In the mean time I will add support for language name `swig` that during language auto detection automatically evaluates to HTML just like handlebars.  I could likely have this released tonight.

@Glavin001 FYI, I have to go on a 3 week camping trip with my part time job so I will be out of pocket for a little while.

**Comment by prettydiff** [comment] 2015-07-17 21:08
@ttsirkia The behavior is intentional and hidden behind a flag evaluating for HTML support: https://github.com/prettydiff/prettydiff/blob/master/prettydiff.js#L9457

The problem is that HTML should be automatically set to true as a condition of the `swig` language setting.  This is what I plan to fix tonight.

**Comment by ttsirkia** [comment] 2015-07-17 21:12
Yes, I understand that. The original question here is that when `atom-beautify` calls `prettydiff` should it specify the language as `markup` as it is now (it causes this issue because it cannot handle HTML5 elements correctly) or `handlebars` which seems to work and has similar syntax or `html`.

**Comment by ttsirkia** [comment] 2015-07-17 21:14
The original example was just few HTML tags, but the Swig template can be something like this:

```html
{% block content %}
<div>
  <p>Welcome {{ username }}!</p>
  <img src="{{ picture }}">
</div>
{% endblock %}
```

**Comment by ttsirkia** [comment] 2015-07-17 21:15
So is there any difference between `html` and `handlebars` language option, for example?

**Comment by prettydiff** [comment] 2015-07-17 21:23
No difference. I try to support as many different template tags out of the box natively. The only template languages I require special identification for are React JSX and Dust.js, because their template tags use a less specific syntax.  Thanks for the code sample.  I will have this fixed up for you soon.

**Comment by ttsirkia** [comment] 2015-07-17 21:30
OK, thanks! Then I think that #464 will fix this issue in `atom-beautify`.

**Comment by Glavin001** [comment] 2015-07-17 23:54
> > > So is there any difference between html and handlebars language option, for example?
> > No difference. 
> Then I think that #464 will fix this issue in atom-beautify.

~~If there is no difference then would #464 even change anything?~~
In #464 we are moving from `markup` to `handlebars` (same as `html`) for `Swig`. Either of which should work. I like it. This should work. Thanks!

I am going to merge now.

**Closed** 2015-07-17 23:55 UTC
Labels: bug, high priority, quick-todo
