### ISSUE TITLE
Where to set Pretty Diff options?

### ISSUE THREAD

**Issue by astanciu** [Glavin001/atom-beautify#1191] opened 2016-09-12 22:38 UTC
I'm using the JSX PrettyDiff formatter, which per their docs, have a lot more options that can be set, such as `formatObject`. I cannot figure out where to set these extra options though. 

I tried .jsbeautifyrc and .prettydiffrc but didn't seem to take.

**Comment by Glavin001** [comment] 2016-09-13 01:27
Pretty Diff is growing all of the time. Currently Atom-Beautify supports many of the options and is missing others: https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/prettydiff.coffee#L10
If the option you want is unavailable, I recommend submitting a Pull Request to add support for it! I'd recommend taking a look at https://github.com/Glavin001/atom-beautify/blob/master/docs/add-languages-and-beautifiers.md to get started.

**Comment by Glavin001** [comment] 2016-09-13 01:54
I'm going to close this as a duplicate of https://github.com/Glavin001/atom-beautify/issues/524 which details other Pretty Diff beautifier options that need to be added.

**Closed by Glavin001** 2016-09-13 01:54 UTC
Labels: question
