### ISSUE TITLE
Uncaught Error: tunneling socket could not be established, statusCode=504

### ISSUE THREAD

**Issue by zhujie** [Glavin001/atom-beautify#1715] opened 2017-06-12 07:20 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Mac OS X 10.12.4
**Thrown From**: [atom-beautify](https://github.com/Glavin001/atom-beautify) package 0.29.26

### Stack Trace

Uncaught Error: tunneling socket could not be established, statusCode=504

```
At stream.js:74

Error: tunneling socket could not be established, statusCode=504
    at ClientRequest.onConnect (/packages/atom-beautify/node_modules/tunnel-agent/index.js:166:19)
    at ClientRequest.g (events.js:286:16)
    at emitThree (events.js:116:13)
    at ClientRequest.emit (events.js:194:7)
    at Socket.socketOnData (_http_client.js:393:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:543:20)
```

### Commands

```
     -2:17 docblockr:parse-enter (input.hidden-input)
     -2:17 editor:newline (input.hidden-input)
  3x -2:02.1.0 core:backspace (input.hidden-input)
     -1:58.2.0 emmet:insert-formatted-line-break-only (input.hidden-input)
     -1:58.2.0 docblockr:parse-enter (input.hidden-input)
     -1:58.2.0 editor:newline (input.hidden-input)
     -1:56.4.0 core:backspace (input.hidden-input)
     -1:54.5.0 autocomplete-plus:confirm (input.hidden-input)
  2x -1:49.1.0 core:backspace (input.hidden-input)
     -1:36 core:move-right (input.hidden-input)
     -1:34.1.0 emmet:insert-formatted-line-break-only (input.hidden-input)
     -1:34.1.0 docblockr:parse-enter (input.hidden-input)
     -1:34.1.0 editor:newline (input.hidden-input)
     -1:26.5.0 core:save (input.hidden-input)
     -0:36 settings-view:open (input.hidden-input)
     -0:28.2.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
dracula-syntax 2.0.5 
atom-beautify 0.29.26 
atom-bootstrap3 1.2.12 
busy-signal 1.4.3 
docblockr 0.10.3 
dracula-syntax 2.0.5 
emmet 2.4.3 
file-icons 2.1.7 
intentions 1.1.2 
language-vue 0.23.0 
language-vue-component 0.5.0 
laravel 0.7.1 
linter 2.1.4 
linter-php 1.3.2 
linter-ui-default 1.6.0 
vue2-autocomplete 0.1.0-alpha.4 
```

**Comment by Glavin001** [comment] 2017-06-12 23:49
Looks like it may be duplicate of https://github.com/request/tunnel-agent/issues/28

**Closed by Glavin001** 2017-06-12 23:49 UTC
