### ISSUE TITLE
Add Spacebars support.

### ISSUE THREAD

**Issue by dnichk** [Glavin001/atom-beautify#306] opened 2015-05-04 05:39 UTC
It would be great if your code formatter supported Spacebars.
https://atom.io/packages/language-spacebars

This is part of the templating language for meteor.js

**Comment by Glavin001** [comment] 2015-05-04 05:44
Duplicate of #217.

Is it not working for you? Could you run the Atom Beautify's command `Help Debug Editor`

**Closed by Glavin001** 2015-05-04 05:44 UTC
