### ISSUE TITLE
Add support for Laravel .blade.php templates

### ISSUE THREAD

**Issue by calvinchoy** [Glavin001/atom-beautify#448] opened 2015-07-06 12:53 UTC
Hi,

Anyone know where I can add the .blade.php of laravel blade templating so that beautifier recognise it? For example format it like html, which might work out of the box. 

Thanks

**Comment by Glavin001** [comment] 2015-07-06 15:01
- Please provide an example to be added to the tests
- Does PHP work? The grammar and extension could be added here: https://github.com/Glavin001/atom-beautify/blob/master/src/languages/php.coffee#L9-L18
- If it's not pure HTML or PHP then I would want to add it as a new language. See https://github.com/Glavin001/atom-beautify/blob/master/docs/add-languages-and-beautifiers.md#how-to-add-a-language for details.

I am always open to reviewing Pull Requests.

**Comment by calvinchoy** [comment] 2015-07-07 07:26
I added the `Blade` grammar and `.blade.php` to the `html.coffee` file. The formatting worked actually pretty good except for some cases. 

I will try to fix those problems.

**Comment by Glavin001** [comment] 2015-07-14 18:43
`html` is handled by `JS Beautify` beautifier by default. This means we should be able to add `Blade` language and then use `JS Beautify` and quickly get going.

I will review and accept Pull Requests for this. See https://github.com/Glavin001/atom-beautify/blob/master/docs/add-languages-and-beautifiers.md#how-to-add-a-language for documentation. Feel free to ask any questions. Thanks.

**Comment by bojidar-bg** [comment] 2015-07-20 11:13
:+1:

**Comment by kmare** [comment] 2016-02-08 09:48
any news on that? it'd be quite cool..

**Comment by ubeyou** [comment] 2016-03-03 09:42
Thanks calvinchoy, it works! 

uses Auto-Intent before Beautify, it works great on my side.

add the `Blade` grammar and `php` to the `html.coffee` file. 

```
  ###
  Supported Grammars
  ###
  grammars: [
    "HTML",
    "Blade"
  ]

  ###
  Supported extensions
  ###
  extensions: [
    "html",
    "php"
  ]
```

**Comment by ArtworkAD** [comment] 2016-08-22 17:15
👍 where is the html.coffee? would like to see this merged

**Comment by Glavin001** [comment] 2016-08-22 19:42
@ArtworkAD : This is the `html.coffee` file: https://github.com/Glavin001/atom-beautify/blob/master/src/languages/html.coffee#L17-L26

**Comment by goemaeret** [comment] 2016-10-17 19:15
Any update on this one?

**Comment by slottybon** [comment] 2016-10-27 11:13
Yeah, any update? 
Using the `html.coffee` file does work for the html part in my `blade.php` files, but obviously not for the blade part.

Meaning this:
```
@section('scripts')
	{{ HTML::script('http://code.highcharts.com/highcharts.js') }}
	{{ HTML::script('js/app/nav.js') }}
	{{ HTML::script('js/app/stream/scrollTop.js') }}
	{{ HTML::script('js/jquery-sticky/jquery.sticky.js') }}
	{{ HTML::script('js/app/partials/sidebar.js') }}
@stop
```
becomes this: 
```
@section('scripts') {{ HTML::script('http://code.highcharts.com/highcharts.js') }} {{ HTML::script('js/app/nav.js') }} {{ HTML::script('js/app/stream/scrollTop.js') }} {{ HTML::script('js/jquery-sticky/jquery.sticky.js') }} {{ HTML::script('js/app/partials/sidebar.js') }} @stop
```
So, yeah ... did anybody get further than this?

**Comment by whereisjefe** [comment] 2016-11-09 17:58
Just wanted to add to what @slottybon said, if there is a temp fix that would be great

**Comment by Sangramchahal** [comment] 2016-11-30 05:06
when can we expect to see built in support for blade.php files?

**Comment by maxvaser** [comment] 2016-12-15 18:07
I love this library! Format on save is fantastic! Adding formatting support for the Blade syntax and HTML would be very useful!  or even just recognizing  .blade.php  file extensions to allow the regular HTML portion to be formatted on save would be awesome!

 I tried modifying the html.coffee file and it had no effect.

**Comment by Glavin001** [comment] 2017-01-03 00:38
> when can we expect to see built in support for blade.php files?

As soon as someone submits a Pull Request implement it 😜.

See https://github.com/Glavin001/atom-beautify/blob/master/docs/add-languages-and-beautifiers.md for how to add a language and a beautifier to Atom-Beautify.
Let me know if you have any questions! It looks like @ubeyou commented what was necessary: https://github.com/Glavin001/atom-beautify/issues/448#issuecomment-191680738
However, I would prefer to add a new language (separate from existing HTML) for Blame as it is not simply HTML.

For example:

```coffeescript
module.exports = {

  name: "Blade"
  namespace: "blade"
  fallback: ["html"]

  ###
  Supported Grammars
  ###
  grammars: [
    "HTML",
    "Blade"
  ]

  ###
  Supported extensions
  ###
  extensions: [
    "html",
    "php"
  ]

}
```

**Comment by nckrtl** [comment] 2017-02-10 08:44
Would really love blade support as well!

**Comment by ryaposov** [comment] 2017-04-14 10:15
Blade support would be a great thing!

**Comment by sogeniusio** [comment] 2017-05-08 16:54
Waiting for some support as well...

**Comment by Glavin001** [comment] 2017-05-08 17:13
@nckrtl @ryaposov @sogeniusio : The power is yours 😜 . Pull Requests are welcome! See https://github.com/Glavin001/atom-beautify/issues/448#issuecomment-270036847 for details. If you have questions about how to make the Pull Request, please let me know.

Also, to new users, please do not create unproductive comments for "+1" or similar, and instead *do* put your 👍  on the Issue body at the top: 
![image](https://cloud.githubusercontent.com/assets/1885333/25815812/74009ba8-33f8-11e7-89ae-b6dddd1f8ee0.png)
Thank you!

**Comment by 1e4** [comment] 2017-07-06 08:22
Has there been any more progress by anyone on this? Judging by the thread, the temp fix seems to have some pitfalls.

**Comment by Glavin001** [comment] 2017-07-06 13:21
@1e4 no progress planned on my end. I await a Pull Request. Thanks!

**Comment by jhkueh** [comment] 2017-09-03 13:43
Hi, I had submitted a Pull Request (#1817) to add basic support for this not too long ago.

The problem is that Blade syntax don't indent properly yet. I am hoping if anyone could point me to the right direction or give me some tips, so I could further work on it.

**Comment by szeck87** [comment] 2017-11-04 03:01
Disregard the previous comment.

**Comment by hosquiat** [comment] 2017-11-05 19:47
Whew, thanks!

**Comment by DevBodin** [comment] 2017-12-06 17:34
I'd be interested in helping out with this if anyone's got something going. Not very experienced with Coffeescript (or Github for that matter), but with a little hand-holding I could make it happen.

**Comment by jhkueh** [comment] 2017-12-07 09:18
@DevBodin I had submitted a PR (#1817) for this that add basic support a few months ago. It still need some works before it's accepted, which I had been unable to do due to the busyness of life. Since it's holiday season now, I will be able to resume working on it.

**Comment by darron1217** [comment] 2018-03-18 10:34
@jhkueh Will you send a PR for this issue again?

**Comment by jhkueh** [comment] 2018-03-18 13:55
@darron1217 feel free to pick up from where I left off in this PR (#1817), if possible. Because I no longer use Atom as it doesn't suit my needs, I have since moved on to VS Code now.

**Comment by darron1217** [comment] 2018-03-19 02:34
@jhkueh Does VS Code support blade template well ?

**Comment by ahmedalmulki** [comment] 2018-03-28 09:26
Hi is there any news about supporting blade , I am really need that .

**Comment by darron1217** [comment] 2018-03-29 00:14
@ahmedalmulki I've created PR #2087 and passed tests, but not yet merged...
Due to lack of knowledge about beautifying, I could just implement basic level (just arranging HTML) of Blade Template.
If anyone can make my PR better, please let me know :)

**Comment by HDVinnie** [comment] 2018-04-10 02:06
please add blade support

**Comment by HexagonStorms** [comment] 2018-04-11 13:44
Pretty frustrating seeing that this issue is 2 & a half years old and still lacking Blade support... Especially since there is an open pull request that we're just waiting on to be merged into master.

**Comment by darron1217** [comment] 2018-04-11 14:06
@Glavin001 Ping

**Comment by HDVinnie** [comment] 2018-04-11 15:58
@HexagonStorms I agree and its not like blade is not widely used by many people. Laravel is quiet popular.

**Comment by szeck87** [comment] 2018-05-14 20:07
Published to v0.32.3.

**Closed by szeck87** 2018-05-14 20:07 UTC
Labels: add-language

**Comment by shawnfromportland** [comment] 2019-10-04 18:23
> @HexagonStorms I agree and its not like blade is not widely used by many people. Laravel is quiet popular.

@HexagonStorms 😂😂😂
