### ISSUE TITLE
Can't update from  0.29.14 to 0.29.16

### ISSUE THREAD

**Issue by Guy-Markman** [Glavin001/atom-beautify#1445] opened 2017-01-05 10:04 UTC
# Description

I'm trying to update it from 0.29.14 to 0.29.16 using cmd (apm update) and I always get errors.

Installing atom-beautify@0.29.16 to C:\Users\Guy and Noam\.atom\packages failed

> atom-beautify@0.29.16 postinstall C:\Users\GUYAND~1\AppData\Local\Temp\apm-ins
tall-dir-11705-444-ipu1g2\node_modules\atom-beautify
> npm run build-options

C:\Users\GUYAND~1\AppData\Local\Temp\apm-install-dir-11705-444-ipu1g2
`-- (empty)

npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm WARN deprecated minimatch@0.2.12: Please update to minimatch 3.0.2 or higher
 to avoid a RegExp DoS issue
npm WARN deprecated node-uuid@1.4.0: use uuid module instead
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher
 to avoid a RegExp DoS issue
'C:\Users\Guy' is not recognized as an internal or external command,
operable program or batch file.
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\GUYAND~1\AppDa
ta\Local\Temp\apm-install-dir-11705-444-ipu1g2\package.json'
npm WARN apm-install-dir-11705-444-ipu1g2 No description
npm WARN apm-install-dir-11705-444-ipu1g2 No repository field.
npm WARN apm-install-dir-11705-444-ipu1g2 No README data
npm WARN apm-install-dir-11705-444-ipu1g2 No license field.
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Users\\Guy and Noam\\AppData\\Local\\atom\\app-1.12.9\\resour
ces\\app\\apm\\bin\\node.exe" "C:\\Users\\Guy and Noam\\AppData\\Local\\atom\\ap
p-1.12.9\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconf
ig" "C:\\Users\\Guy and Noam\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Gu
y and Noam\\.atom\\.apmrc" "install" "C:\\Users\\GUYAND~1\\AppData\\Local\\Temp\
\d-11705-444-1wtk6mo\\package.tgz" "--runtime=electron" "--target=1.3.13" "--arc
h=ia32" "--global-style"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! atom-beautify@0.29.16 postinstall: `npm run build-options`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the atom-beautify@0.29.16 postinstall script 'npm run build-o
ptions'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the atom-beautify package
,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build-options
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs atom-beautify
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls atom-beautify
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\GUYAND~1\AppData\Local\Temp\apm-install-dir-11705-444-ipu1
g2\npm-debug.log
npm ERR! code 1
# Input Before Beautification
no code

# Expected Output

no  code
# Actual Output

no code

# Steps to Reproduce
Open cmd, wrote "apm update" and enter when I was asked to update atom-beutify

# Debug

Here is a link to the `debug.md` Gist: <INSERT GIST HERE>

# Checklist

I have:
- [ ] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [ ] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [ ] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [ ] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [ ] Generated debugging information and added link for `debug.md` Gist to this issue

**Comment by jolsenmultiad** [comment] 2017-01-05 14:25
I think this is a duplicate of #1043

**Comment by jolsenmultiad** [comment] 2017-01-05 14:43
And #1434, which is now closed by means of atom/apm#666

**Closed** 2017-01-05 15:57 UTC
