### ISSUE TITLE
Add support for Unix Shell Files

### ISSUE THREAD

**Issue by jfisbein** [Glavin001/atom-beautify#580] opened 2015-10-01 09:39 UTC
Atom Beautify could not determine a supported beautifier to handle this file with grammar "Shell Script" and extension "sh".

Thanks!!!

**Comment by quilicicf** [comment] 2016-09-23 12:26
+1, would be really helpful !

**Comment by Glavin001** [comment] 2016-09-25 21:55
Waiting on Pull Request to be merged: https://github.com/Glavin001/atom-beautify/pull/1220

**Comment by Glavin001** [comment] 2016-09-25 22:00
Sounds like a duplicate of #451.

**Closed** 2016-09-25 22:00 UTC
Labels: add-language, duplicate
