### ISSUE TITLE
Uncaught TypeError: Cannot read property 'setScrollTop' of null

### ISSUE THREAD

**Issue by Mohammadaasim99** [Glavin001/atom-beautify#1181] opened 2016-09-08 05:35 UTC
# Description

The results of beautification are not what I expect.

# Expected Results

The beautified code should have looked like:

```
<INSERT CODE HERE>
```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/2758c7700d3d34b8bfa4bfc576f24bfd

# Checklist

- [ ] I have tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [ ] I have reloaded (or restarted) Atom to ensure it is not a caching issue
- [ ] Searched for existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [ ] Generated debugging information and added link for `debug.md` Gist to this issue

**Comment by MAYDAY1993** [comment] 2016-09-08 07:42
I came up with the same problem

**Comment by CraneJen** [comment] 2016-09-08 17:23
I came up with the same problem too

**Comment by Moriarty02** [comment] 2016-09-09 06:35
I came up with the same problem too

**Comment by cainaf** [comment] 2016-09-09 16:36
I came up with the same problem too

**Comment by Glavin001** [comment] 2016-09-10 01:30
Applicable line of code: https://github.com/Glavin001/atom-beautify/blob/master/src/beautify.coffee#L35

I will accept Pull Requests resolving this issue. Thanks!

**Comment by atomr-web** [comment] 2016-09-16 16:59
I came up with the same problem too

**Comment by Glavin001** [comment] 2016-09-16 17:16
tl;dl: Did you run beautify and close the TextEditor tab quickly after? This could occur if beautification is in progress and tries to set the scroll position after you have closed your TextEditor tab.

---

Looking at the applicable section of code found at https://github.com/Glavin001/atom-beautify/blob/master/src/beautify.coffee#L33-L35 

```
setScrollTop = (editor, value) ->
  view = atom.views.getView(editor)
  view.setScrollTop value
```

The reason is likely because the TextEditor View no longer exists which could be because that TextEditor tab was closed.

**Comment by adamboche** [comment] 2016-09-19 02:35
> The reason is likely because the TextEditor View no longer exists which could be because that TextEditor tab was closed.

That is true in my case

**Comment by prajankya** [comment] 2016-09-20 10:38
Me Too..

**Comment by wollardj** [comment] 2016-09-20 16:51
Saw the same. In my case I was able to reproduce the issue on demand by using split views.

1. open a file
2. create a split pane (View -> Panes -> Split *)
3. open that same file in the new pane
4. make some changes to the file
5. close one of the panes (in my case I'd closed the newest pane)
6. save your changes in your remaining pane / tab.
7. _you should be looking at the error at this step_

HTH

**Comment by dacodekid** [comment] 2016-09-22 18:07
This is happening to me when I close a `Split` screen as @wollardj pointed out.

**Comment by steventhanna** [comment] 2016-09-24 00:18
I don't know if this is related, but I get the same error only when I have `end_with_newline: false` in my js beautify. If I set it to `true`, the error disappears.

**Closed** 2016-09-25 17:52 UTC
Labels: bug, in-progress

**Comment by Glavin001** [comment] 2016-09-25 18:37
Published to v0.29.13.

**Comment by Zubin-Teherani** [comment] 2016-09-29 00:43
I'm still getting this error. If I'm using two panes, then it moves my cursor to the bottom of the pane and gets stuck.

I think it might have to also do if I have two panes with the same file open. Anyone else having this issue?

**Comment by wskn** [comment] 2016-09-29 11:23
@Zubin-Teherani yes. Check ```End with newline``` in atom-beautify  setting page.

**Comment by Glavin001** [comment] 2016-09-30 13:35
It appears the issue is still occurring.

I am moving this over to #977 and closing this as a duplicate.
