### ISSUE TITLE
Can't install on Windows

### ISSUE THREAD

**Issue by yossi787** [Glavin001/atom-beautify#858] opened 2016-03-17 20:16 UTC
I am getting this error:
![screenshot_3](https://cloud.githubusercontent.com/assets/6242723/13859823/00645282-ec8e-11e5-8a83-478595732aa7.jpg)
Thanks.

**Comment by Glavin001** [comment] 2016-03-30 13:48
This is a duplicate of many others issues regarding the `postinstall` script of cross-spawn for Windows: https://github.com/Glavin001/atom-beautify/search?q=postinstall&type=Issues&utf8=%E2%9C%93

**Closed by Glavin001** 2016-03-30 13:48 UTC
Labels: duplicate, windows

**Comment by Glavin001** [comment] 2016-04-16 23:14
I just published a patch in release v0.29.4 that makes `cross-spawn` dependency optional. 
The [`cross-spawn`](https://github.com/IndigoUnited/node-cross-spawn) package depends on [`spawn-sync`](https://github.com/ForbesLindesay/spawn-sync) and has been causing problems when installing Atom-Beautify for many users. By making this dependency optional, users will be able to easily install Atom-Beautify and, in the case that [`cross-spawn`](https://github.com/IndigoUnited/node-cross-spawn) fails to install, will fallback to the builtin [`spawn`](https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options) method.
