### ISSUE TITLE
Not working for python (autopep8 error)

### ISSUE THREAD

**Issue by revernus** [Glavin001/atom-beautify#728] opened 2016-01-02 07:59 UTC
Whenever I try to use beautify, it raises an error related to autopep8 usage:

Usage: autopep8 [options] [filename [filename ...]] Use filename '-' for stdin.
autopep8: error: no such option: --indent-size

Here is a printscreen: http://i.imgur.com/o8uGNNC.png

**Comment by Glavin001** [comment] 2016-01-02 14:44
Duplicate of https://github.com/Glavin001/atom-beautify/issues/419

Updating `autopep8` should resolve this issue.

**Closed by Glavin001** 2016-01-02 14:44 UTC

**Comment by revernus** [comment] 2016-01-02 16:13
It should be updated to which version? I have version 0.9.1 installed.

**Comment by Glavin001** [comment] 2016-01-03 03:57
> It should be updated to which version? I have version 0.9.1 installed.

Version 1.5.7

See https://github.com/Glavin001/atom-beautify/issues/419#issuecomment-115438486
