### ISSUE TITLE
Failed to activate the atom-beautify package

### ISSUE THREAD

**Issue by funny123** [Glavin001/atom-beautify#1367] opened 2016-11-18 06:00 UTC
Cannot find module 'event-kit'
Hide Stack Trace
Error: Cannot find module 'event-kit'
    at Module._resolveFilename (module.js:440:15)
    at Module._resolveFilename (/usr/share/atom/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/fma/.atom/packages/atom-beautify/src/beautify.coffee:7:25)
    at Object.<anonymous> (/home/fma/.atom/packages/atom-beautify/src/beautify.coffee:2:1)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:201:21)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app.asar/src/package.js:741:27)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:174:16)
    at /usr/share/atom/resources/app.asar/src/package.js:821:25
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:240:20)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/usr/share/atom/resources/app.asar/src/atom-environment.js:1136:28)
    at EventEmitter.outerCallback (/usr/share/atom/resources/app.asar/src/application-delegate.js:319:25)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)

**Comment by prettydiff** [comment] 2016-11-18 10:24
Marking as duplicate of https://github.com/Glavin001/atom-beautify/issues/1366

**Closed by prettydiff** 2016-11-18 10:24 UTC
Labels: duplicate

**Comment by dooley1023** [comment] 2016-11-21 19:24
Hi I am receiving the same message. I am on windows 8.1 I have tried reinstalling and receive the same error again.
`
Error: Cannot find module 'event-kit'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (C:\Users\"userid"\AppData\Local\atom\app-1.12.5\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (C:\Users\"userid"\AppData\Local\atom\app-1.12.5\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (C:\Users\"userid"\AppData\Local\atom\app-1.12.5\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/"userid"/.atom/packages/atom-beautify-master/src/beautify.coffee:7:25)
    at Object.<anonymous> (file:///C:/Users/"userid"/.atom/packages/atom-beautify-master/src/beautify.coffee:2:1)
    at Module._compile (C:\Users\"userid"\AppData\Local\atom\app-1.12.5\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.value [as .coffee] (C:\Users\"userid"\AppData\Local\atom\app-1.12.5\resources\app.asar\src\compile-cache.js:201:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (C:\Users\"userid"\AppData\Local\atom\app-1.12.5\resources\app.asar\src\native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (C:\Users\"userid"\AppData\Local\atom\app-1.12.5\resources\app.asar\src\package.js:741:27)
    at Package.module.exports.Package.activateNow (C:\Users\"userid"\AppData\Local\atom\app-1.12.5\resources\app.asar\src\package.js:174:16)
    at C:\Users\"userid"\AppData\Local\atom\app-1.12.5\resources\app.asar\src\package.js:821:25
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\"userid"\AppData\Local\atom\app-1.12.5\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\"userid"\AppData\Local\atom\app-1.12.5\resources\app.asar\node_modules\event-kit\lib\emitter.js:129:28)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\"userid"\AppData\Local\atom\app-1.12.5\resources\app.asar\src\command-registry.js:240:20)
    at CommandRegistry.handleCommandEvent (C:\Users\"userid"\AppData\Local\atom\app-1.12.5\resources\app.asar\src\command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\"userid"\AppData\Local\atom\app-1.12.5\resources\app.asar\src\command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (C:\Users\"userid"\AppData\Local\atom\app-1.12.5\resources\app.asar\src\atom-environment.js:1136:28)
    at EventEmitter.outerCallback (C:\Users\"userid"\AppData\Local\atom\app-1.12.5\resources\app.asar\src\application-delegate.js:319:25)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
`

**Comment by CuteToUniverse** [comment] 2017-02-10 05:02
I also meet this issue now! I'm so sad that I do not find way to do with it. Who can tell me how to deal with it?(device: nootbook  system: windows10)

**Comment by prettydiff** [comment] 2017-02-10 12:22
The recommendation in the past is to reinstall Atom Beautify.  The problem is likely from a corrupt or missing dependency.  Please let me know if this fails to solve the problem.
