### ISSUE TITLE
Add support for Stylus files ".styl"

### ISSUE THREAD

**Issue by marcorosas1991** [Glavin001/atom-beautify#1261] opened 2016-10-10 17:59 UTC
# Description

Beautify doesn't support Stylus files
# Actual Output

Atom Beautify could not find a supported beautifier for this file
Atom Beautify could not determine a supported beautifier to handle this file with grammar "Stylus" and extension "styl". If you would like to request support for this file and its language, please create an issue for Atom Beautify at https://github.com/Glavin001/atom-beautify/issues
# Steps to Reproduce
1. Add Stylus code to Stylus file in Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

**Comment by alanaasmaa** [comment] 2016-11-06 10:16
+1

**Comment by prettydiff** [comment] 2016-11-07 20:03
The project website is likely http://stylus-lang.com/

Could you guys see if this is already supported in Pretty Diff?  http://prettydiff.com/

**Comment by alanaasmaa** [comment] 2016-11-07 20:13
Yes project website is right, but i dont think that prettydiff supports stylus.

Thanks for your reply !

**Comment by prettydiff** [comment] 2016-11-07 20:15
Yeah, I just took a closer look and realized that the code does not have curly braces.

**Comment by alanaasmaa** [comment] 2016-11-07 20:17
Yes you dont have to use them but i personally like to use them, code looks cleaner for me. Its optional

**Comment by alanaasmaa** [comment] 2016-11-27 16:13
If i select SCSS as an grammar it works pretty good.

**Comment by prettydiff** [comment] 2016-11-28 00:15
Strange Pretty Diff is the only beautifier included with support for SCSS.  Pretty Diff doesn't support SASS.

**Comment by cristianounix** [comment] 2017-02-16 13:10
@alanaasmaa yes if select SCSS works but the visualy is ugly, see stylus and SCSS colors in the file .styl:
![screen shot 2017-02-16 at 11 07 39](https://cloud.githubusercontent.com/assets/694280/23022506/6379720a-f438-11e6-95e2-5c4ec2623654.png)

![screen shot 2017-02-16 at 11 07 54](https://cloud.githubusercontent.com/assets/694280/23022507/638066a0-f438-11e6-893a-811ec7625a83.png)

**Comment by Glavin001** [comment] 2017-04-09 21:42
Closing this Stylus issue as a duplicate of https://github.com/Glavin001/atom-beautify/issues/318

**Closed by Glavin001** 2017-04-09 21:42 UTC
Labels: add-language
