### ISSUE TITLE
'Beautifier is not a constructor'

### ISSUE THREAD

**Issue by rzjnzk** [Glavin001/atom-beautify#2269] opened 2018-11-22 04:05 UTC
**Atom**: 1.32.1 x64
**Electron**: 2.0.9
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [atom-beautify](https://github.com/Glavin001/atom-beautify) package 0.33.4

### Stack Trace

Failed to activate the atom-beautify package

```
At Beautifier is not a constructor

TypeError: Beautifier is not a constructor
    at /packages/atom-beautify/src/beautifiers/index.coffee:121:7
    at arrayMap (/packages/atom-beautify/node_modules/lodash/lodash.js:639:23)
    at Function.map (/packages/atom-beautify/node_modules/lodash/lodash.js:9556:14)
    at /packages/atom-beautify/src/beautifiers/index.coffee:119:22)
    at /packages/atom-beautify/src/beautify.coffee:10:14)
    at /packages/atom-beautify/src/beautify.coffee:2:1)
    at /packages/atom-beautify/src/beautify.coffee:2:1)
    at Module.get_Module._compile (E:/d/User/Software Projects/#atom/Atom x64/resources/app/static/<embedded>:11:146385)
    at Object.value [as .coffee] (E:/d/User/Software Projects/#atom/Atom x64/resources/app/static/<embedded>:11:149932)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (internal/module.js:11:18)
    at customRequire (E:/d/User/Software Projects/#atom/Atom x64/resources/app/static/<embedded>:1:622321)
    at Package.requireMainModule (E:/d/User/Software Projects/#atom/Atom x64/resources/app/static/<embedded>:11:3044031)
    at Package.activateNow (E:/d/User/Software Projects/#atom/Atom x64/resources/app/static/<embedded>:11:3032165)
    at string.e.trim.length.activationHookSubscriptions.add.packageManager.onDidTriggerActivationHook (E:/d/User/Software Projects/#atom/Atom x64/resources/app/static/<embedded>:14:2445)
    at Function.simpleDispatch (E:/d/User/Software Projects/#atom/Atom x64/resources/app/static/<embedded>:11:1186953)
    at Emitter.emit (E:/d/User/Software Projects/#atom/Atom x64/resources/app/static/<embedded>:11:1188394)
    at deferredActivationHooks.triggeredActivationHooks.forEach.e (E:/d/User/Software Projects/#atom/Atom x64/resources/app/static/<embedded>:11:380240)
    at Set.forEach (<anonymous>)
    at PackageManager.activatePackage (E:/d/User/Software Projects/#atom/Atom x64/resources/app/static/<embedded>:11:380202)
    at E:/d/User/Software Projects/#atom/Atom x64/resources/app/static/<embedded>:11:913914
    at r (E:/d/User/Software Projects/#atom/Atom x64/resources/app/static/<embedded>:11:908520)
    at o (E:/d/User/Software Projects/#atom/Atom x64/resources/app/static/<embedded>:14:1037411)
    at ChildProcess.n.process.on.e (E:/d/User/Software Projects/#atom/Atom x64/resources/app/static/<embedded>:14:1037617)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
```

### Commands

```
     -2:46.5.0 core:paste (input.hidden-input)
 19x -2:26.3.0 intentions:highlight (input.hidden-input)
     -2:18.4.0 core:copy (input.hidden-input)
     -2:17.7.0 intentions:highlight (input.hidden-input)
     -2:17.3.0 core:paste (input.hidden-input)
     -2:16.6.0 intentions:highlight (input.hidden-input)
     -2:16.5.0 core:paste (input.hidden-input)
 31x -2:13.5.0 intentions:highlight (input.hidden-input)
     -2:12.1.0 core:paste (input.hidden-input)
  8x -2:11.3.0 core:backspace (input.hidden-input)
  3x -1:42.4.0 intentions:highlight (input.hidden-input)
     -1:41.9.0 core:cut (input.hidden-input)
     -1:40.6.0 core:backspace (input.hidden-input)
     -1:32.7.0 intentions:highlight (input.hidden-input)
     -1:32.6.0 core:paste (input.hidden-input)
 16x -0:38.5.0 core:backspace (input.hidden-input)
```

### Non-Core Packages

```
achievements 0.9.0 
ask-stack 2.2.0 
atom-beautify 0.33.4 
atom-comment-highlighter 0.0.0 
atom-ctags 5.1.2 
atom-discord 2.0.1 
atom-esthetique-syntax 0.0.0 
atom-html-preview 0.2.5 
atom-ide-debugger-node 0.7.3 
atom-ide-ui 0.13.0 
atom-jump-to-line-end 0.0.0 
atom-project-template-manager 0.0.0 
atom-snippets-focus-point-highlight 0.0.0 
atom-snippets-nesting 0.0.0 
auto-indent 0.5.0 
autocomplete-clang 0.11.5 
autocomplete-cmake 0.3.1 
autocomplete-java 1.2.7 
autocomplete-js-import 1.4.0 
autocomplete-json 5.5.2 
autocomplete-modules 2.2.5 
autocomplete-paths 2.12.2 
autocomplete-sql 0.5.0 
autocomplete-xml 0.10.1 
better-git-blame 0.4.7 
build-cmake 0.12.0 
busy-signal 1.4.3 
close-unmodified-tabs 1.0.4 
color-picker 2.3.0 
ctags-status 1.3.7 
declarations 1.1.3 
emmet 2.4.3 
file-icons 2.1.26 
git-blame 1.8.0 
git-plus 8.1.0 
git-time-machine 2.1.0 
github-user-datatip 0.3.2 
gpp-compiler 3.0.7 
highlight-selected 0.14.0 
hover-tooltips 0.3.0 
Hydrogen 2.6.0 
ide-cpp 0.0.3 
intentions 1.1.5 
language-cmake 1.1.0 
language-cpp14 0.6.2 
language-qml 1.1.0 
language-qt-qrc 3.0.0 
language-qtpro 0.7.0 
linter 2.2.0 
linter-cppcheck 0.2.3 
linter-cpplint 2.0.1 
linter-eslint 8.4.1 
linter-jscs 4.1.3 
linter-jshint 3.1.9 
linter-ui-default 1.7.1 
minimap 4.29.9 
minimap-find-and-replace 4.5.2 
minimap-highlight-selected 4.6.1 
minimap-pigments 0.2.2 
move-fast 0.0.1 
node-debugger 1.10.1 
node-requirer 0.1.12 
open-recent 5.0.0 
pigments 0.40.2 
platformio-ide-terminal 2.8.4 
preview 0.19.0 
project-manager 3.3.6 
sourcefetch-stackoverflow 0.5.0 
swackets 0.35.0 
teletype 0.13.3 
template-generator 0.16.0 
todo-show 2.3.2 
zentabs 0.8.9 
```

# Checklist

I have:
- [* ] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [* ] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [*, the issue has been reported, though closed automatically by a bot ] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [N/A ] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [N/A, not accessible ] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by Glavin001** [comment] 2018-11-22 04:31
I've seen reinstalling and/or restarting Atom helps. See https://github.com/Glavin001/atom-beautify/issues/952#issuecomment-214869463 for one example. Let me know how that goes.

Duplicate of https://github.com/Glavin001/atom-beautify/issues/2200

**Comment by rzjnzk** [comment] 2018-11-22 06:00
I've tried that with no success unfortunately.

Additionally, this error was displayed on the settings install page:

`Installing` “atom-beautify@0.33.4” failed.Hide output…
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open 'E:\d\User\Software Projects\#atom\.atom\packages\atom-beautify\.github\issuecomplete.yml'`

**Comment by rzjnzk** [comment] 2018-11-28 13:32
Following the advice of this commenter solved my problem. https://github.com/Glavin001/atom-beautify/issues/1923#issuecomment-340983237

Closing issue.

**Closed** 2018-11-28 13:32 UTC
Labels: question
