### ISSUE TITLE
sass: cannot assign & to a var

### ISSUE THREAD

**Issue by fly1ted** [Glavin001/atom-beautify#1376] opened 2016-11-23 08:38 UTC
# Description
I'm trying to solve what's discussed [here](http://stackoverflow.com/a/33176587/6671934). It looks like I cannot assign ampersand to a var. For now I've it hardcoded as `$_: '.foo';`.

# Input Before Beautification

This is what the code looked like before:

```
.foo{
  $_: &;
  
  &--bar{
    & #{$_}-baz{
      text-align:center;
    }
  }
}
```

# Expected Output

The beautified code should have looked like this:

```
.foo--bar .foo-baz {
  text-align: center;
}
```

# Actual Output

The beautified code actually looked like this:

```
Unsupported beautification result 'Parsing error: Please check the validity of the block starting from line #4
```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Debug

Here is a link to the `debug.md` Gist: <INSERT GIST HERE>

# Checklist

I have:
- [ ] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [ ] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [ ] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [ ] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [ ] Generated debugging information and added link for `debug.md` Gist to this issue

**Comment by prettydiff** [comment] 2016-11-23 11:28
Would you mind doing me a huge favor and producing the debug.md file.  The beautifier is probably Pretty Diff, but I just want to make sure I have all my facts straight.  https://github.com/Glavin001/atom-beautify/blob/master/docs/troubleshooting.md

**Comment by prettydiff** [comment] 2016-11-23 11:34
I just read your issue more closely and examined the Stackoverflow link.  Code beautifiers aren't going to provide this kind of service for you.  You need to find a compiler or transpiler.

**Comment by fly1ted** [comment] 2016-11-23 11:35
I don't want the beautifier to compile the code, I want it to not complain about it on saving since I have enabled 'On save'.

**Comment by prettydiff** [comment] 2016-11-23 19:05
Yeah, sorry I misunderstood.  That is definitely a bug.  What beautifier are you using?

**Comment by fly1ted** [comment] 2016-11-23 19:32
CSScomb

**Comment by fly1ted** [comment] 2016-11-23 19:38
I've just tried Pretty Diff and it doesn't complain, thereby it looks like it's CSSComb's problem. Also I mistakenly tried inputting the sass code here http://csscomb.com/online and it produces similar err. Can it be that you beautify sass with CSSComb before compilation?

**Comment by prettydiff** [comment] 2016-11-23 20:35
@fly1ted I am not sure if that is a preference of the csscomb library, but in my opinion its a bug.  It is a design decision that is absolutely failing you as a user.  What likely happened is that they built their tool for an easily reproducible environment, like their web tool.  This makes testing and maintenance much faster for the core team, but it makes you lethargic and complacent to the concerns of dependent applications.  I am saying this from my own experience because Pretty Diff has had a nearly identical bug in the past (returning an error message instead of code).

I would recommend opening an issue with csscomb and linking back to this issue.

**Comment by fly1ted** [comment] 2016-12-11 16:37
@prettydiff I've investigated the issue and came to this conclusion. cssomb is a css parser, hence the name, the reason it worked for scss is just it uses [gonzales-pe](https://github.com/tonyganch/gonzales-pe) parser that in turn supports scss. The latest csscomb uses relatively old gonzales-pe thus I think it maybe the reason why it doesn't work.

**Comment by prettydiff** [comment] 2016-12-11 16:50
@fly1ted Thank you for this updated information.  I suggest opening an issue with csscomb so that they can update their dependency.

**Comment by Glavin001** [comment] 2017-01-03 02:51
For future issues:

> Please follow the [issue template](https://github.com/Glavin001/atom-beautify/blob/master/ISSUE_TEMPLATE.md) provided. More specifically, [adding a link to the required `debug.md` Gist](https://github.com/Glavin001/atom-beautify/blob/master/docs/troubleshooting.md#how-to-create-debugmd-gist) which includes debugging information that answers our most commonly asked questions.
Thank you.

I am closing this as a CSSComb bug: https://github.com/csscomb/csscomb.js/issues/494

**Closed by Glavin001** 2017-01-03 02:51 UTC
Labels: third-party-bug
