### ISSUE TITLE
Support for swift

### ISSUE THREAD

**Issue by Austinthemighty** [Glavin001/atom-beautify#1629] opened 2017-04-27 00:54 UTC
can you add support for swift please

**Comment by prettydiff** [comment] 2017-04-27 03:57
Marking as duplicate of https://github.com/Glavin001/atom-beautify/issues/675

**Closed by prettydiff** 2017-04-27 03:57 UTC
Labels: add-language, duplicate

**Comment by Glavin001** [comment] 2017-05-14 03:43
@issue-manager duplicates test

**Comment by Glavin001** [comment] 2017-05-14 03:46
@issue-manager duplicates test

**Comment by Glavin001** [comment] 2017-05-14 03:50
@issue-manager duplicates test

**Comment by Glavin001** [comment] 2017-05-14 03:51
@issue-manager duplicates test

**Comment by Glavin001** [comment] 2017-05-14 03:58
@issue-manager duplicates test

**Comment by Glavin001** [comment] 2017-05-14 04:09
@issue-manager duplicates test
