### ISSUE TITLE
Doesn't indent @keyframes correctly in SCSS

### ISSUE THREAD

**Issue by AchoArnold** [Glavin001/atom-beautify#500] opened 2015-08-07 19:01 UTC
Hello

``` scss
@keyframes infinite-spinning {
  from {
    transform: rotate(0deg);
  }
  to {
    transform: rotate(360deg);
  }
}
```

Gets beautified to 

``` css
@keyframes infinite-spinning {
    from {
        transform: rotate(0deg);
    }

to {
        transform: rotate(360deg);
    }
}
```

**Comment by Glavin001** [comment] 2015-08-07 19:20
Sass/SCSS is handled by Pretty Diff: https://github.com/Glavin001/atom-beautify/blob/master/src/languages/sass.coffee#L21

I would recommend forwarding this issue over to @prettydiff at https://github.com/prettydiff/prettydiff/issues 
Add a link back to this Issue on Atom Beautify when you create the new Issue on Pretty Diff: that way we can see if it is closed on Pretty Diff. Thanks!

**Comment by prettydiff** [comment] 2015-08-07 23:28
I am not able to reproduce the error in the Pretty Diff tool.

**Comment by Glavin001** [comment] 2015-08-08 01:16
Hmm. @najela could you run `Atom Beautify: Help Debug Editor` from the command palette, create a Gist, paste those results into a Markdown Gist (extension `.md`), and provide the link here for debugging. Thanks!

**Comment by najela** [comment] 2015-08-08 09:01
This is the link to the gist https://gist.github.com/najela/09c57d78f8853df1bf1e

**Comment by ArekSredzki** [comment] 2015-08-13 05:54
Should be fixed in prettydiff/prettydiff#142

**Comment by Glavin001** [comment] 2015-08-13 15:18
Once Pretty Diff has merged the pull request, and published a new release to npm, you can trigger Atom to update Atom Beautify's dependencies by uninstalling and reinstalling Atom Beautify. Be sure to restart Atom, in case there are problems cleaning up the old loaded package.

**Comment by prettydiff** [comment] 2017-10-10 15:49
This looks like a long resolved issue.

**Closed by prettydiff** 2017-10-10 15:49 UTC
Labels: third-party-bug
