### ISSUE TITLE
[Request] - Allow additional Commands to be ran within specific Language Settings

### ISSUE THREAD

**Issue by ggedde** [Glavin001/atom-beautify#2040] opened 2018-02-13 21:58 UTC
I know that with the work on Unibeautify this may seem not needed.
However, until then a way to make HTML work inside PHP would be to allow me to set an additional Beautifier to run when PHP is triggered.

So in the settings of PHP there would just be another setting [text field] for additional commands to run.  From there I can just paste in "Atom Beautify: Beautify Language Html"
Or something to that affect.

This could also be used for other commands that other devs need,

**Comment by Glavin001** [comment] 2018-02-13 22:59
Please subscribe to https://github.com/Unibeautify/unibeautify/issues/29 and https://github.com/Glavin001/atom-beautify/issues/1174 😃 .

Unfortunately, it is unlikely to be included in the current version of Atom-Beautify, as I am focusing as much of my attention on Unibeautify as possible. @szeck87 is working on upgrading Atom-Beautify to using Unibeautify, such as with this PR https://github.com/Glavin001/atom-beautify/pull/1935 .

While this means it will take more time for this feature to exist in Atom-Beautify, Unibeautify will have much better support overall and great new features coming. Please be patient and keep these ideas coming! Thank you for your interest in Atom-Beautify and Unibeautify!

---

Sign up for Unibeautify CI: https://goo.gl/jmM4QN
Help improve Atom-Beautify by completing the quick questionnaire: https://goo.gl/iEHBNr

**Comment by Glavin001** [comment] 2018-02-13 23:02
Closing as a duplicate of https://github.com/Unibeautify/unibeautify/issues/29 and https://github.com/Glavin001/atom-beautify/issues/457 and https://github.com/Glavin001/atom-beautify/issues/1185 and others. Please subscribe to those and 👍 to show your interest!

**Closed by Glavin001** 2018-02-13 23:02 UTC
Labels: feature
