### ISSUE TITLE
Could not find 'X'. The program may not be installed. on Windows 10

### ISSUE THREAD

**Issue by seanmars** [Glavin001/atom-beautify#1392] opened 2016-12-03 15:25 UTC
# Description

When open atom with right click menu, it's always get "Could not find 'X'. The program may not be installed. ", But when open atom with shortcut it's work find.

# Debug

Here is a link to the debug.md Gist: 
https://gist.github.com/anonymous/27d26ff481383bae07f7971a1bcc2f97

**Comment by prettydiff** [comment] 2016-12-04 04:02
This appears to be a duplicate of #1052

**Closed by prettydiff** 2016-12-04 04:02 UTC
Labels: duplicate, third-party bug

**Comment by Glavin001** [comment] 2017-06-04 18:24
I really want to focus on improving the installation experience for users. I have created a new Issue, #1687, to target this problem. Please provide your feedback! Thanks in advance.
