### ISSUE TITLE
Array spread operator in combination with JSX elements

### ISSUE THREAD

**Issue by derwaldgeist** [Glavin001/atom-beautify#1697] opened 2017-05-31 09:24 UTC
I have the following statement array construction statement:

```jsx
    const globalOptions = [
      <option key="global">Global</option>,
      ...options
    ];
```
where `options` is another array of <option> elements.

atom-beautify / PrettyDiff turns this into:

```jsx
    const globalChannelOptions = [ < option key = "global" > Global < /option>,
      ...channelOptions
    ];
```
which is quite different from the input and breaks the JSX parser due to the additional blanks.

Even worse, any following regular JSX code will break, too. For instance, if you place this code right after the code above inside a render() method:
```jsx
return <div className="option-group">
      <div className="option">
        <span className="caption">Channel</span>
        <select className="channel">
          {globalChannelOptions}
        </select>
      </div>
</div>;
```
it turns into this:
```jsx
    return <div className="option-group">
      <div className="option">
        <span className="caption">Channel</span > <select className="channel">
      {globalChannelOptions}
    </select> < /div>
    </div >;
```
with a lot of code-breaking spaces inserted, too. Seems as if some internal flag is not being reset correctly. If I remove the array spread statement, the jsx code below would not be touched at all.

Update: Just noticed this behaviour does not relate to the spread operator. It also happens if you place a JSX element in an array like this: 

```jsx
    const globalOptions = [<option key="global">Global</option>];
```

However, it works if you place the element in expression parenthesis:
```jsx
const globalOptions = [(<option key="global">Global</option>)];
```
As far as I understand JSX, this is optional, but I might be wrong.

**Comment by prettydiff** [comment] 2017-05-31 20:22
This looks like a defect to me.  I am investigating.

**Comment by prettydiff** [comment] 2017-06-01 01:56
I can reproduce this defect in old Pretty Diff.  I cannot reproduce it in the current Pretty Diff, however your code samples did indicate a recent regression issue with JSX code.  I just committed a fix.

**Comment by prettydiff** [comment] 2017-10-10 16:00
Resolved as an updated version of Pretty Diff has made it into Atom Beautify.

**Closed by prettydiff** 2017-10-10 16:00 UTC
Labels: third-party-bug
