### ISSUE TITLE
sqlformat error

### ISSUE THREAD

**Issue by nyaaao** [Glavin001/atom-beautify#1717] opened 2017-06-12 16:44 UTC
# Description

When beautifying a `.sql` file I'm getting the following error:
```
usage: sqlformat  [OPTIONS] FILE, ...
sqlformat: error: argument --indent_width: invalid int value: 'tab'
```
sqlformat version: 0.2.2
OS: Ubuntu 17.04

# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/nyaaao/12bd9b08491f4d531c6c97d203375e8e

# Checklist

I have:
- [+] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [+] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [+] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [+] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [+] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by Glavin001** [comment] 2017-06-12 17:05
Looks like a duplicate of https://github.com/Glavin001/atom-beautify/issues/1287

Hopefully that helps. Let me know! 😄

**Closed by Glavin001** 2017-06-12 17:05 UTC

**Comment by nyaaao** [comment] 2017-06-12 17:20
@Glavin001 while setting it manualy in the `.editorconfig` (set `indent_size` to 1) allowed to run the beautify, it did so using spaces. is this expected?
another question: I tried to set the indent size explicitly for the SQL beautifier in the settings without any success, is it getting picked up at all?

PS: thank you for the quick response

**Comment by Glavin001** [comment] 2017-06-12 20:22
Indent size should work. See https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/sqlformat.coffee#L21

I will need your new `debug.md` Gist for any more questions. Also feel free to create a new Issue if it is a new issue. Try reading through your `debug.md` logs and the `sqlformat.coffee` code to see if it *should* work as you expect. If there is a feature you want which is unsupported please feel free to submit a Pull Request and ask questions if you need help contributing 😄 .
