### ISSUE TITLE
SQL beautify not working error is  --indent_width: invalid int value: 'tab' 

### ISSUE THREAD

**Issue by pauldhawk** [Glavin001/atom-beautify#1287] opened 2016-10-20 17:09 UTC
# Can not beautify Sql

errors with --indent_width: invalid int value: 'tab'  not sure where its gettting the indent with value from

```
<INSERT CODE HERE>
```
# Steps to Reproduce
1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!
# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/6c81c11688b893a630ba40674ec458e8
# Checklist
- [x] I have tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [ ] I have reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched for existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
  so I know this is not a duplicate issue
- [x] Generated debugging information and added link for `debug.md` Gist to this issue

**Comment by Glavin001** [comment] 2017-01-01 20:36
Your EditorConfig has been extracted to:

```json
{
    "_default": {
        "end_of_line": "lf",
        "insert_final_newline": true,
        "indent_style": "tab",
        "trim_trailing_whitespace": false,
        "charset": "utf-8",
        "indent_size": "tab",
        "indent_char": "\t",
        "indent_with_tabs": true
    }
}
```

Notice `"indent_size": "tab",` which is incorrect (not a number).

The applicable code is: https://github.com/Glavin001/atom-beautify/blob/604b6340d6a34d13a1b0285cc341da6afeb447d3/src/beautifiers/index.coffee#L554-L558

It looks like this issue is a duplicate of https://github.com/Glavin001/atom-beautify/issues/339
The workaround is manually setting `indent_size = 1` in your EditorConfig file, if you are using `indent_style = tab`.

**Closed by Glavin001** 2017-01-01 20:36 UTC
