### ISSUE TITLE
Save file after "Beautify on save"

### ISSUE THREAD

**Issue by janwerkhoven** [Glavin001/atom-beautify#337] opened 2015-05-08 04:19 UTC
Atom marks files that are "beautified on save" as unsaved. In the tabs in the top of Atom, the circle icon appears next the files that have been "saved and beautified". Would you be able to make your package so that it saves right after beautifying?

Love your work :)

Jan

**Comment by Glavin001** [comment] 2015-05-08 14:33
Duplicate of #314

Published fix to v0.27.1

Please let me know if this works for you.

**Closed by Glavin001** 2015-05-08 14:33 UTC

**Comment by janwerkhoven** [comment] 2015-05-11 01:19
Thanks for the quick response.

I am now on version 0.27.1 and now no beautification happens at all on save, unfortunately. I have tried checking and unchecking both "Beautify Entire File on Save" and  "DEPRECATED: Beauty on Save". No combination seems to work for me.

Atom-beautify v0.21.1
Atom v0.198.0
Mac OS X v10.10.3

Any suggestions?

Kind regards, Jan

**Comment by Glavin001** [comment] 2015-05-11 15:29
Have you checked/enabled the "beautify on save" for your desired language (e.g. check `Language Config - <your langauge> - Beautify On Save`)? Beautify on save is now opt-in and no longer global.
