### ISSUE TITLE
Formatting swift files : Atom Beautify could not find a supported beautifier for this file

### ISSUE THREAD

**Issue by RanaRanvijaySingh** [Glavin001/atom-beautify#1585] opened 2017-04-08 08:13 UTC
# Description

The results of beautification are not what I expect.

# Input Before Beautification

This is what the code looked like before:

```
public class GetSimpleRequests {
    public static func getRequestWithParam() -> Routes {
      var routes = Routes()
      routes.add(method: .get, uri: Constants.Apis.GET_REQUEST_WITH_PARAMS,
      handler: {
        request, response in {
          response.setHeader(.contentType, value: Constants
          .ContentTypes.TEXT_HTML)
          response.appendBody(string: getRequestParam(request))
          response.completed()
        }
      })
         }
}
```

# Expected Output

The beautified code should have looked like this:

```
public class GetSimpleRequests {
    public static func getRequestWithParam() -> Routes {
      var routes = Routes()
      routes.add(method: .get, uri: Constants.Apis.GET_REQUEST_WITH_PARAMS,
      handler: {
        request, response in {
          response.setHeader(.contentType, value: Constants
          .ContentTypes.TEXT_HTML)
          response.appendBody(string: getRequestParam(request))
          response.completed()
        }
      })
    }
}

```

# Actual Output

Got this message

```
Atom Beautify could not determine a supported beautifier to handle this file with grammar "Swift" and extension "swift". If you would like to request support for this file and its language, please create an issue for Atom Beautify at https://github.com/Glavin001/atom-beautify/issues
```

**Comment by Glavin001** [comment] 2017-04-09 18:20
Swift is not yet supported.

Duplicate of https://github.com/Glavin001/atom-beautify/issues/675

**Closed by Glavin001** 2017-04-09 18:20 UTC
Labels: add-language
