### ISSUE TITLE
Please run Atom command 'Atom-Beautify: Migrate Settings'. You have unsupported options: _analyticsUserId

### ISSUE THREAD

**Issue by funk77** [Glavin001/atom-beautify#1001] opened 2016-06-01 17:07 UTC
Please run Atom command 'Atom-Beautify: Migrate Settings'.
You have unsupported options: _analyticsUserId
how 2 cure?

**Comment by Glavin001** [comment] 2016-06-01 19:37
Did you successfully run the `Atom-Beautify: Migrate Settings` command?
If no, then duplicate of https://github.com/Glavin001/atom-beautify/issues/936

**Closed by Glavin001** 2016-06-01 19:37 UTC

**Comment by funk77** [comment] 2016-06-06 16:12
ty, ctrl+alt+p - cure ;)

2016-06-01 22:37 GMT+03:00 Glavin Wiechert <notifications@github.com>:
