### ISSUE TITLE
Plugin not working with php-cs-fixer

### ISSUE THREAD

**Issue by swirly** [Glavin001/atom-beautify#1576] opened 2017-03-30 20:52 UTC
Mac OS X
Latest atom version
whatever the langage, following error 

Bad argument
Hide Stack Trace
TypeError: Bad argument
    at TypeError (native)
    at ChildProcess.spawn (internal/child_process.js:289:26)
    at exports.spawn (child_process.js:392:9)
    at /Users/laurent/.atom/packages/atom-beautify/src/beautifiers/beautifier.coffee:136:17
    at Promise._execute (/Users/laurent/.atom/packages/atom-beautify/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/Users/laurent/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:481:18)
    at new Promise (/Users/laurent/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:77:14)
    at PHPCSFixer.module.exports.Beautifier.getShellEnvironment (/Users/laurent/.atom/packages/atom-beautify/src/beautifiers/beautifier.coffee:116:16)
    at /Users/laurent/.atom/packages/atom-beautify/src/beautifiers/beautifier.coffee:269:38
    at tryCatcher (/Users/laurent/.atom/packages/atom-beautify/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/laurent/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Users/laurent/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Users/laurent/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/laurent/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/Users/laurent/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:636:18)
    at PromiseArray._resolve (/Users/laurent/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise_array.js:125:19)
    at PromiseArray._promiseFulfilled (/Users/laurent/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise_array.js:143:14)
    at Promise._settlePromise (/Users/laurent/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:572:26)
    at Promise._settlePromise0 (/Users/laurent/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/laurent/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/Users/laurent/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:636:18)
    at PromiseArray._resolve (/Users/laurent/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise_array.js:125:19)
    at PromiseArray._promiseFulfilled (/Users/laurent/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise_array.js:143:14)
    at Promise._settlePromise (/Users/laurent/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:572:26)
    at Promise._settlePromise0 (/Users/laurent/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/laurent/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/Users/laurent/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/laurent/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:143:10)
    at Async.drainQueues (/Users/laurent/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:17:14)

# Checklist

I have:
- [x ] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x ] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [ x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [ -] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [ -] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by swirly** [comment] 2017-03-30 21:10
Okay, generated debug information, seems to be PHP problem. php-cs-fixer is installed, in path, but PHP is "Bad argument" for atom-beautify

https://gist.github.com/swirly/db5d5080ed9a52ef67f2472f156259d0

**Comment by cahya6d6d6e** [comment] 2017-04-05 03:16
#1541 
newer php-cs-fixer has different arguments with the older one. --config-file changed to --config, --fixers and --level merged into --rules.

**Comment by Glavin001** [comment] 2017-04-09 19:23
Closing as duplicate of https://github.com/Glavin001/atom-beautify/issues/1465

**Closed by Glavin001** 2017-04-09 19:23 UTC
