### ISSUE TITLE
Settings UI shows update but none exists

### ISSUE THREAD

**Issue by smlombardi** [Glavin001/atom-beautify#896] opened 2016-04-06 14:32 UTC
The UI shows there is an update to 0.29.1, I have 0.28.28

However, if I click the update button, it spins indefinitely and spikes the cpu and never updates.

If I use `apm update` in the Terminal, I get "empty" -- no updates.

I tried uninstalling beautify and re-installing.  Still 0.28.28, still says there is the update, and `apm update` still says no update.

![screen shot 2016-04-06 at 10 28 22 am](https://cloud.githubusercontent.com/assets/835148/14320380/d3d2ae4e-fbe2-11e5-8a22-e42748e909f4.png)

**Comment by Glavin001** [comment] 2016-04-06 14:38
Duplicate of #841 and #401 and #391.

This issue should have been resolved when we added the `deactivate` method in Pull Request https://github.com/Glavin001/atom-beautify/pull/501
However still experiencing issues...

I recommend joining the discussion at https://github.com/atom/settings-view/issues/532 for this apparent Settings-View bug.

**Closed by Glavin001** 2016-04-06 14:38 UTC

**Comment by frankhale** [comment] 2016-04-06 15:10
Unfortunately that issue referenced on settings-view doesn't appear to be making any headway. @Glavin001, have you not experienced issues updating Atom-Beautify? If you haven't, how are you updating?

**Comment by Glavin001** [comment] 2016-04-06 15:17
I have the Atom-Beautify package linked (`apm link`) since I am actively developing it on my computer. So I essentially update with `npm update` or `npm install` when applicable, which of course works fine. The issue lies in how `apm install atom-beautify` or `apm update atom-beautify` works and then the Settings-View component rendering that process.
It also does not take very long for me to update (with `npm update`), which is another issue that other users have reported experiencing. I wonder if `apm` is deleting the original package contents and doing a fresh install each time, which definitely would take a fair amount of time.
I am currently working on my honours thesis for my bachelors so I won't have time to investigate much further until beginning of May. Hopefully this issue is resolved by then.

**Comment by frankhale** [comment] 2016-04-06 15:22
>  I wonder if apm is deleting the original package contents and doing a fresh install each time, which definitely would take a fair amount of time.

I don't have any supporting evidence other than my perceptions and my computer grinding for several minutes but yes I think this is absolutely correct. The updates are indeed very long and CPU intensive.
