### ISSUE TITLE
 Beautify Entire File On Save

### ISSUE THREAD

**Issue by fionser** [Glavin001/atom-beautify#458] opened 2015-07-13 08:02 UTC
I was strange that I had disable this option; and restart the Atom.
But it keep beautify the file when I save the file.

**Comment by Glavin001** [comment] 2015-07-13 13:36
Sounds like a duplicate of #455. Could you please confirm that this is the same issue and we could continue discussion over at #455 instead?

**Closed by Glavin001** 2015-07-13 13:36 UTC
