### ISSUE TITLE
Add beautify for elixir/phoenix

### ISSUE THREAD

**Issue by RomarioLopezC** [Glavin001/atom-beautify#1040] opened 2016-07-02 00:44 UTC

**Comment by Glavin001** [comment] 2016-07-02 03:23
Please provide a link to the language's documentation, including example code. Thank you.

**Comment by ssijak** [comment] 2016-07-07 18:13
@Glavin001 [http://elixir-lang.org/](http://elixir-lang.org/)  [http://elixir-lang.org/docs/stable/elixir/Kernel.html](http://elixir-lang.org/docs/stable/elixir/Kernel.html)

**Comment by RomarioLopezC** [comment] 2016-07-07 20:40
@Glavin001 Phoenix is a web framework written in Elixir

http://www.phoenixframework.org/
https://hexdocs.pm/phoenix/Phoenix.html

**Comment by rubencaro** [comment] 2016-08-17 12:17
This could be a duplicate of #545

**Closed** 2016-08-17 12:31 UTC
Labels: add-language, duplicate
