### ISSUE TITLE
Support for .gql

### ISSUE THREAD

**Issue by gijo-varghese** [Glavin001/atom-beautify#1914] opened 2017-10-30 06:32 UTC
Currently, `atom-beautify` doesn't support **.gql** files (GraphQL Query files). It would be great if that's possible :)

**Comment by szeck87** [comment] 2017-10-30 17:12
Duplicate of https://github.com/Glavin001/atom-beautify/issues/1896.

**Closed by szeck87** 2017-10-30 17:12 UTC
Labels: duplicate
