### ISSUE TITLE
Wrong indentation with chained jquery ajax

### ISSUE THREAD

**Issue by DrakeXiang** [Glavin001/atom-beautify#1230] opened 2016-09-27 02:44 UTC
# Description

I use [atom-jquery-snippets](https://github.com/james2doyle/atom-jquery-snippets) for jquery, everything worked out fine except when beautifying the ajax snippet generated from it, the indentation of the first parenthesis should be on the same level with $.ajax
# Expected Results

The beautified code should have looked like:

```
                $.ajax({
                    url: '/path/to/file',
                    type: 'default GET (Other values: POST)',
                    dataType: 'default: Intelligent Guess (Other values: xml, json, script, or html)',
                    data: {param1: 'value1'}
                })
                .done(function() {
                    console.log("success");
                })
                .fail(function() {
                    console.log("error");
                })
                .always(function() {
                    console.log("complete");
                });

```
# Steps to Reproduce
1. Install [atom-jquery-snippets](https://github.com/james2doyle/atom-jquery-snippets)
2. type `ajax`, select `$.ajax()` and hit enter to generate snippet
3. Run command `Atom Beautify: Beautify Editor`
4. This beautified code does not look right!
# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/anonymous/5c97f4f66cb0a0b055144f60aa47b71d

I found https://github.com/Glavin001/atom-beautify/issues/847#issue-138443092 this issue seems similar to mine, if duplicated please close this one
# Checklist
- [check ] I have tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [check ] I have reloaded (or restarted) Atom to ensure it is not a caching issue
- [check ] Searched for existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
  so I know this is not a duplicate issue
- [check ] Generated debugging information and added link for `debug.md` Gist to this issue

**Comment by prettydiff** [comment] 2016-09-27 12:26
@bitwiseman  It looks like the OP was wanting the `data` object to be on a single line.

**Comment by bitwiseman** [comment] 2016-09-27 13:05
@prettydiff 
This is a duplicate of #847.

The settings included: 
```
{
    "brace_style": "collapse"
}
```

The actual output was:
```
$.ajax({
        url: '/path/to/file',
        type: 'default GET (Other values: POST)',
        dataType: 'default: Intelligent Guess (Other values: xml, json, script, or html)',
        data: {
            param1: 'value1'
        }
    })
    .done(function() {
        console.log("success");
    })
    .fail(function() {
        console.log("error");
    })
    .always(function() {
        console.log("complete");
    });
```

If the settings included this instead: 
```
{
    "brace_style": "collapse-preserve-inline"
}
```

It becomes clear this is the same as #847:
```
   $.ajax({
           url: '/path/to/file',
           type: 'default GET (Other values: POST)',
           dataType: 'default: Intelligent Guess (Other values: xml, json, script, or html)',
           data: { param1: 'value1' }
       })
       .done(function() {
           console.log("success");
       })
       .fail(function() {
           console.log("error");
       })
       .always(function() {
           console.log("complete");
       });
```

**Comment by DrakeXiang** [comment] 2016-09-27 14:48
@prettydiff 
@bitwiseman was right, my issue is not about the data object, sorry my English made you think that way. I believe this pic could show you what I meant.
![sample](https://cloud.githubusercontent.com/assets/2898841/18878704/2ca90266-8504-11e6-8231-c1ccf44ee9a9.jpg)

**Comment by Glavin001** [comment] 2017-01-01 04:54
Closing as duplicate of #847.

**Closed by Glavin001** 2017-01-01 04:54 UTC
Labels: duplicate, third-party bug
