### ISSUE TITLE
Uncaught TypeError: Cannot read property 'setScrollTop' of null

### ISSUE THREAD

**Issue by Foadsf** [Glavin001/atom-beautify#1475] opened 2017-01-17 22:23 UTC
I have had this issue for a long time now but unfortunately I haven't been able to solve it. I even had to ask for help in StackOverflow and some dudes apparently have sent the repo admins pull requests. but no updates has came so far. I would appreciate if you could solve this. it is irritating.
you may find the complete explanation in this SO post:
http://stackoverflow.com/questions/41351215/atom-editor-atom-beautify-plugin-error-uncaught-typeerror-cannot-read-propert

**Comment by prettydiff** [comment] 2017-01-17 22:39
This appears to be a duplicate of #1339.  Thank your for the SO link as the additional information may prove very helpful.

**Closed by prettydiff** 2017-01-17 22:39 UTC
Labels: bug, duplicate
