### ISSUE TITLE
"Beautified" code is copied and re-inserted at cursor position. (v0.28.11 - Windows 7)

### ISSUE THREAD

**Issue by cgddrd** [Glavin001/atom-beautify#507] opened 2015-08-12 08:42 UTC
Following update to v0.28.11, running Atom Beautify now causes editor contents to *on occasion* be **copied and re-pasted from the current cursor position**.

While not all languages have been tested, this behaviour does appear to take place with both Javascript and HTML files, so it is clear that this issue is not limited to a single language. 

Due to the 'erratic' copying behaviour, this issue can **break user's code** if the result of the issue is not immediately visible (as happened to me yesterday). 

This issue is visible on Atom v1.0.6, running on Windows 7 with Atom Beautify v0.28.11. Other configurations have not been tested at this time.

**Comment by Glavin001** [comment] 2015-08-12 17:10
> Following update to v0.28.11

What version were you on before? This has only started happening recently?

> Due to the 'erratic' copying behaviour, this issue can **break user's code**

Absolutely, it would.

> running Atom Beautify now causes editor contents to on occasion be copied and re-pasted from the current cursor position.

There are other issues that describe this happening, especially when you have *selected* text with your cursor. Check out a few at https://github.com/Glavin001/atom-beautify/search?utf8=%E2%9C%93&q=duplicate+code&type=Issues

The only way this makes sense is if Atom Beautify is detecting that you have text selected when it attempts to re-apply your beautified code back to your editor. I would recommend doing some debugging yourself -- I have been unable to reproduce this bug since people started experiencing it. First, you should add some additional logging.
See https://github.com/Glavin001/atom-beautify/blob/df569a9f4ed80dc22d4bcd345ba709851067fa16/src/beautify.coffee#L115-L123 for the applicable code.
It would be important and useful to see that Atom Beautify is choosing to `setTextInBufferRange` instead of simply replacing the entire editor's contents with `setText`. I would recommend adding logging statements for both of those conditions.

If `setText` is being called and it is causing this issue where it duplicates your code at the cursor position, then this is an Atom bug, since `setText` should replace the entire text editor buffer. I doubt this will be the case.

If `setTextInBufferRange` is being called then the problem is with Atom Beautify detection if the User has currently selected text. See https://github.com/Glavin001/atom-beautify/blob/df569a9f4ed80dc22d4bcd345ba709851067fa16/src/beautify.coffee#L115
for code `if not forceEntireFile and isSelection`. I would recommend also logging the `forceEntireFile` and `isSelection` variables. If this is the case, which I think you will find it is, then it has to do with the code at https://github.com/Glavin001/atom-beautify/blob/df569a9f4ed80dc22d4bcd345ba709851067fa16/src/beautify.coffee#L116 `selectedBufferRange = editor.getSelectedBufferRange()`, for incorrectly retrieving the selected buffer ranges of your cursor. This means that Atom has detected you have selected text, and is beautifying and replacing the text of only your selected text.

Note that the logic for detecting if a user has selected text and for replacing only the selected areas, is performed in the `beautifyCompleted` callback. I think this is where the bug could be. Part Atom Beautify bug, part human-error: if the user were to run beautify, then select some text, even accidently, then when the beautification is complete it would then detect if the user has selected text. Since the user originally did not have selected text, it took the entire file and beautified it. See https://github.com/Glavin001/atom-beautify/blob/df569a9f4ed80dc22d4bcd345ba709851067fa16/src/beautify.coffee#L166-L172 for applicable code.
Then when `beautifyCompleted`, the user had selected text now and it replaced only that text area, with the beautification results of the *entire file* which was beautified.

Let me know what you think and how the debugging goes. I may look in to improving the current code such the logic for detecting if the user has selected text is outside of the `beautifyCompleted` callback. If my assumptions are correct, then this will fix this bug. However, if you do not have selected text, and it is calling `editor.setText` then this is an Atom bug, which would be surprising.

**Comment by cgddrd** [comment] 2015-08-18 09:39
Hi,

My sincere apologies for the delay in getting back to you. After restarting my machine on Friday, I have been trying to replicate the issue I was experiencing, but I have failed to do so. 

I have no idea what went wrong, but it seems to have fixed itself following a restart of the PC. 

In hindsight, I should have definitely checked this before adding a new GH issue, for which I apologise. - I won't make the same rookie mistake again!

Unless anyone else has reported this issue, I would say this issue can now be closed. Should I experience any of the symptoms again, I will follow the debug instructions first prior to raising another bug.

**Comment by cgddrd** [comment] 2015-08-18 14:23
**Update:**

One thing that I have noticed this afternoon (but not sure if it is necessarily related) is this:

Take this LESS code:

```
div.panel {
    padding: 0 !important;
    border: 0 !important;
    margin: 0 !important;
    border-radius: 0 !important;

    > div.panel-heading {
    border: 0 !important;
    background-color: #f3f3f4 !important;
    }
    > div.panel-body {
      padding: 0 !important;
    }
  }
```

After I run Beautify on it, I get left with this:

```
  div.panel {
  padding: 0;
  border: 0 !important !important;
  margin: 0;
  border-radius: 0 !important !important;
  > div.panel-heading {
    border: 0 !important;
    background-color: #f3f3f4 !important;
  }
  > div.panel-body {
    padding: 0 !important;
  }
}
```

(All indentation is exactly as returned by Atom Beautify).

This obviously causes issues with the LESS compiler (e.g. `!important !important`). If you agree, I will raise this as a new bug. 

Thanks

**Comment by Glavin001** [comment] 2015-09-05 11:56
> After restarting my machine on Friday, I have been trying to replicate the issue I was experiencing, but I have failed to do so.

I am going to close this issue then.

Glad to hear it is working :smiley:.

---

For the other problems, please create a new issue, if you are still experiencing it.

**Closed by Glavin001** 2015-09-05 11:56 UTC
Labels: bug
