### ISSUE TITLE
Beautify Not Working in Laravel 

### ISSUE THREAD

**Issue by PSNAppz** [Glavin001/atom-beautify#1200] opened 2016-09-17 06:28 UTC
# Description

The results of beautification are not what I expect.
# Expected Results

The beautified code should have looked like:

```
<INSERT CODE HERE>
```
# Steps to Reproduce
1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!
# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/c174a24461ec772819c7dea161b298b2
# Checklist
- [x] I have tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] I have reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched for existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
  so I know this is not a duplicate issue
- [x] Generated debugging information and added link for `debug.md` Gist to this issue

**Comment by prettydiff** [comment] 2016-09-17 17:31
Could you provide a brief description of the problem?  This will help us know what to look for.

**Comment by PSNAppz** [comment] 2016-09-18 04:13
When I try beautify in a blade.php file it just shows he loading image and nothing is changed.

**Comment by Glavin001** [comment] 2017-01-03 00:34
Closing as a duplicate of https://github.com/Glavin001/atom-beautify/issues/448

**Closed by Glavin001** 2017-01-03 00:34 UTC
Labels: add-language, duplicate
