### ISSUE TITLE
Beautifying sometimes lets the cursor go to top

### ISSUE THREAD

**Issue by WebFreak001** [Glavin001/atom-beautify#433] opened 2015-06-29 20:27 UTC
Sometimes when I beautify my file the text cursor goes all the way to the first character of the file. This can be fairly annoying for larger files. When hitting undo a few times it shows that it completely erases and then replaces the text instead of replacing it in place. I'm using uncrustify and D.

EDIT: Sometimes it even completely erases the file. Would be terrible if the editor crashes then.

**Comment by Glavin001** [comment] 2015-06-29 23:36
> When hitting undo a few times it shows that it completely erases and then replaces the text instead of replacing it in place.

Your entire buffer is replaced with the beautified form of the text. See https://github.com/Glavin001/atom-beautify/blob/master/src/beautify.coffee#L118-L122
I am using the `TextEditor::setText` Atom API. If Atom team wants to implement the replacement of text in place with a diff, instead of replacing the entire buffer on `setText`, then that would be great. I'd recommend you letting them know.

> Sometimes it even completely erases the file.

This is not good. If you could find the reproducible steps to causing this to happen, please let me know.

**Comment by Glavin001** [comment] 2015-06-29 23:38
I almost forgot: the cursor should return to it's correct, original position after calling `setText`. See https://github.com/Glavin001/atom-beautify/blob/master/src/beautify.coffee#L111 and https://github.com/Glavin001/atom-beautify/blob/master/src/beautify.coffee#L125
If that is not working, then we have an issue. If you could provide a way to reproduce this, let me know.

**Comment by Glavin001** [comment] 2015-06-29 23:44
The cursor issue looks like the same as #338, however that has been resolved and published a while ago. I am going to close this issue, however if you are up-to-date, then please let me know the reproducible steps that consistently create this error of cursor resetting to top. We can reopen this issue then if we have something to go on. It may also be worthwhile to talk to the Atom team to make sure there is not an internal bug in their TextEditor APIs.

**Closed by Glavin001** 2015-06-29 23:44 UTC
Labels: question
