### ISSUE TITLE
Support newline-between-rules for CSS 

### ISSUE THREAD

**Issue by langdonx** [Glavin001/atom-beautify#211] opened 2015-02-11 15:50 UTC
It exists as a checkbox on the settings screen, and I've set it to true in my `.jsbeautifyrc` file, but neither seem to have any effect.

js-beautify supports the feature through `-N` or `--newline-between-rules`.

Side note: `-L` or `--selector-separator-newline` also seem to not be supported, but appear to be the default anyway.

**Comment by sebastiankade** [comment] 2015-02-16 07:33
+1

Also "preserve_newlines" does not seem to be respected for LESS files.

**Comment by prettydiff** [comment] 2015-03-18 13:19
This is a duplicate of issue #180 

The bug is due to a difference in default values for the node-library compared to the web tool for prettydiff.

**Comment by Glavin001** [comment] 2015-03-18 13:46
CSS is handled by js-beautify and LESS and SASS is handled by Prettydiff.
So @sebastiankade your issue is with Prettydiff, while @langdonx can you confirm that you are beautifying CSS and not LESS or SASS.

**Comment by langdonx** [comment] 2015-03-18 22:12
@Glavin001 Correct, I do not use LESS/SASS.

**Comment by sebastiankade** [comment] 2015-03-19 02:46
@Glavin001 I just checked and prettydiff correctly handles newlines in less when the 'preserve' option is set to 'all' or 'css'. In my beautify settings I have 'preserve_newlines' set to true but this doesnt seem to make it through to prettydiff for less files.

**Comment by Glavin001** [comment] 2015-03-19 23:32
@sebastiankade you are correct, currently those options do not get passed to prettydiff. See https://github.com/Glavin001/atom-beautify/blob/master/lib/langs/css-prettydiff-beautify.coffee#L4-L10
This should be an easy fix. If you have not already done so, please create another issue for this LESS/SCSS & Prettydiff support bug on Atom Beautify.

--

@langdonx this may be an issue with js-beautify itself. Those options are passed directly to js-beautify, so anything you can put into your `.jsbeautifyrc` will work with js-beautify, if js-beautify in fact supports it. If this is a new feature of js-beautify then I may need to update our js-beautify dependency to resolve this.

**Comment by Glavin001** [comment] 2015-05-03 00:53
Fixed in #245.

**Closed by Glavin001** 2015-05-03 00:53 UTC
Labels: third-party bug
