### ISSUE TITLE
autopep8: error: no such option: --indent-size

### ISSUE THREAD

**Issue by tsouhaieb** [Glavin001/atom-beautify#659] opened 2015-11-13 18:45 UTC
when i open a python file(.py) and i click on "Beautify editor content" 
it show error,atom 1.01.9, atom-beautify 0.28.17

```
   Usage: autopep8 [options] [filename [filename ...]] Use filename '-' for stdin.
   autopep8: error: no such option: --indent-size
```

and the stack trace is 
```
Error: Usage: autopep8 [options] [filename [filename ...]]
Use filename '-'  for stdin.
autopep8: error: no such option: --indent-size
  at /home/unknown/.atom/packages/atom-beautify/src/beautifiers/beautifier.coffee:258:27
  at tryCatcher (/usr/share/atom/resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/util.js:26:23)
  at Promise._settlePromiseFromHandler (/usr/share/atom/resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/promise.js:507:31)
  at Promise._settlePromiseAt (/usr/share/atom/resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/promise.js:581:18)
  at Promise._settlePromises (/usr/share/atom/resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/promise.js:697:14)
  at Async._drainQueue (/usr/share/atom/resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/async.js:123:16)
  at Async._drainQueues (/usr/share/atom/resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/async.js:133:10)
  at MutationObserver.Async.drainQueues (/usr/share/atom/resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/async.js:15:14)
  at process._tickCallback (node.js:365:9)
```

**Comment by Glavin001** [comment] 2015-11-14 16:57
Looks like a duplicate of https://github.com/Glavin001/atom-beautify/issues/419

Please update autopep8

**Closed by Glavin001** 2015-11-14 16:57 UTC
