### ISSUE TITLE
Could not get Shell Environment. Exit code: 1, Signal: null

### ISSUE THREAD

**Issue by hcj1009** [Glavin001/atom-beautify#1539] opened 2017-03-02 20:11 UTC
# Description

Beautify command cannot get Shell Environment when shell is using multiplexer like Tmux.

# Input Before Beautification

Some code.

# Expected Output

Beautifully formatted code.

# Actual Output

````
Error: Could not get Shell Environment. Exit code: 1, Signal: null
    at ChildProcess.<anonymous> (/home/nick/.atom/packages/atom-beautify/src/beautifiers/beautifier.coffee:147:31)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
````

# Steps to Reproduce
In `.zshrc`:
````
[[ $- != *i* ]] && return
[[ -z "$MC_SID" && -z "$TMUX" && -z "$SSH_CLIENT" && -z "$SSH_TTY" ]] \
    && exec tmux
````
Then run `Atom Beautify: Beautify Editor`.

If either line is commented out in `.zshrc`, atom-beautify works perfectly fine and is absolutely awesome.

# Debug

Here is a link to the debug.md Gist: [debug.md.txt](https://github.com/Glavin001/atom-beautify/files/814967/debug.md.txt)

*I had to save it as txt to upload it.

# Checklist

I have:
- [x] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [x] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [x] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by maksimf** [comment] 2017-03-16 23:06
Same issue

**Comment by hcj1009** [comment] 2017-03-17 03:36
It would be nicer if, when running atom-beautify, a certain global variable is defined beforehand so that it is possible to check for that variable in `.zshrc`, just like what I did for `mc` and `ssh`. Providing an option to customize what shell environment or command to use might also resolve the problem? (so that it is possible to use other shells, or just prevent `zsh` from loading `.zshrc`)

**Comment by Glavin001** [comment] 2017-04-20 13:37
Great idea @hcj1009 ! Pull Requests welcome 😃

**Comment by Glavin001** [comment] 2017-05-06 21:01
Closing as duplicate of https://github.com/Glavin001/atom-beautify/issues/1113

Please discuss of at https://github.com/Glavin001/atom-beautify/issues/1113

**Closed by Glavin001** 2017-05-06 21:01 UTC
Labels: feature
