### ISSUE TITLE
Intermediate state in undo stack - duplicated text for JS files

### ISSUE THREAD

**Issue by crizzis** [Glavin001/atom-beautify#1533] opened 2017-02-28 14:21 UTC
With 'beautify on save' enabled for js files, 'Edit/Undo' occasionally results in a state in which several bottom lines are duplicated. 

This is especially annoying for large files where this fact is not immediately visible.

**Comment by prettydiff** [comment] 2017-02-28 20:47
Looks like a duplicate of #1213

**Closed by prettydiff** 2017-02-28 20:47 UTC
