### ISSUE TITLE
support cjsx

### ISSUE THREAD

**Issue by Dreampie** [Glavin001/atom-beautify#639] opened 2015-11-04 15:45 UTC
Atom Beautify could not find a supported beautifier for this file
Atom Beautify could not determine a supported beautifier to handle this file with grammar "CoffeeScript (JSX)" and extension "cjsx". If you would like to request support for this file and its language, please create an issue for Atom Beautify at https://github.com/Glavin001/atom-beautify/issues

**Comment by prettydiff** [comment] 2015-11-04 22:10
Duplicate of https://github.com/Glavin001/atom-beautify/issues/608

**Comment by Dreampie** [comment] 2015-11-05 01:51
I see, but  how can i  format it?

**Comment by prettydiff** [comment] 2015-11-05 02:45
A CJSX beautifier would need to be included in the atom-beautify package.  Do you know of a CJSX beautifier?

**Closed** 2015-11-06 03:55 UTC
Labels: add-language, duplicate
