### ISSUE TITLE
Beautification in progress... Html...

### ISSUE THREAD

**Issue by xuetham** [Glavin001/atom-beautify#1483] opened 2017-01-24 17:16 UTC
# Description

The results of beautification are not what I expect.

# Input Before Beautification

This is what the code looked like before:

```
<INSERT CODE HERE>
```

# Expected Output

The beautified code should have looked like this:

```
<INSERT CODE HERE>
```

# Actual Output

The beautified code actually looked like this:

```
<INSERT CODE HERE>
```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Debug

Here is a link to the `debug.md` Gist: <INSERT GIST HERE>

# Checklist

I have:
- [ ] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [ ] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [ ] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [ ] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [ ] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by Glavin001** [comment] 2017-01-25 02:06
Duplicate of #1432.

Published fix of #1432 to v0.29.17! Thank you for your patience!

**Closed by Glavin001** 2017-01-25 02:06 UTC

**Comment by xuetham** [comment] 2017-01-28 19:27
Ubuntu--->Atom--->New update plugin!!! Thanks, all is fine now!!! Thank you
so much!

2017-01-24 21:06 GMT-05:00 Glavin Wiechert <notifications@github.com>:

**Comment by Glavin001** [comment] 2017-05-14 04:17
@issue-manager duplicates test
