### ISSUE TITLE
Duplicate Code

### ISSUE THREAD

**Issue by edpirone** [Glavin001/atom-beautify#356] opened 2015-05-22 04:15 UTC
Just updated beautify and when I run it, beautify duplicates my entire chunk of code. Going through it now to see if there is a tag left open or something that might be causing the error.

**Comment by Glavin001** [comment] 2015-05-22 11:28
Thanks for letting me know. Duplicate of #331. Let's continue discussions there. 

>  Going through it now to see if there is a tag left open or something that might be causing the error.

Is this an error in Atom Beautify or are you saying that when beautifying code that has a syntax error it duplicates the code?

**Closed by Glavin001** 2015-05-22 11:28 UTC

**Comment by edpirone** [comment] 2015-05-22 12:29
I actually can't tell. I couldn't find the error in my code and it just stopped happening. I normally work really quick so i save and then immediately beautify if i forgot to. Ao i noticed if i do that too quick this happened. If i pause for 2 seconds after save it didn't. That could just be coincidence. But it stopped happening if i paused from what i could tell. 


——

Ed Pirone
Director of Digital Media @ SharpHat
o. 201.503.0020 ext. 205
epirone@sharphat.com

SharpHat Inc.
333 Sylvan Ave. Suite 324
Englewood Cliffs, NJ 07632
www.sharphat.com
