### ISSUE TITLE
Cant install Beautify on clean windows install with space in user name

### ISSUE THREAD

**Issue by Akumetsu-Dev** [Glavin001/atom-beautify#1490] opened 2017-01-27 21:48 UTC
# Description

Cant install Beautify.

# Steps to Reproduce

1. Open Atom
2. Go to Settings > Install
3. Search beautify > install

# Debug

> atom-beautify@0.29.17 postinstall C:\Users\WALDDY~1\AppData\Local\Temp\apm-install-dir-117027-5532-1budd7f\node_modules\atom-beautify
> npm run build-options

C:\Users\WALDDY~1\AppData\Local\Temp\apm-install-dir-117027-5532-1budd7f
`-- (empty)

npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm WARN deprecated minimatch@0.2.12: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated node-uuid@1.4.0: use uuid module instead
(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at TLSSocket.addListener (events.js:239:17)
    at TLSSocket.Readable.on (_stream_readable.js:673:33)
    at Request.<anonymous> (C:\Users\Walddys Emmanuel\AppData\Local\atom\app-1.13.1\resources\app\apm\node_modules\npm-registry-client\lib\request.js:153:7)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at ClientRequest.<anonymous> (C:\Users\Walddys Emmanuel\AppData\Local\atom\app-1.13.1\resources\app\apm\node_modules\request\request.js:823:10)
    at emitOne (events.js:82:20)
    at ClientRequest.emit (events.js:169:7)
    at tickOnSocket (_http_client.js:502:7)
    at onSocketNT (_http_client.js:514:5)
(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at TLSSocket.addListener (events.js:239:17)
    at TLSSocket.Readable.on (_stream_readable.js:673:33)
    at Request.<anonymous> (C:\Users\Walddys Emmanuel\AppData\Local\atom\app-1.13.1\resources\app\apm\node_modules\npm-registry-client\lib\request.js:153:7)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at ClientRequest.<anonymous> (C:\Users\Walddys Emmanuel\AppData\Local\atom\app-1.13.1\resources\app\apm\node_modules\request\request.js:823:10)
    at emitOne (events.js:82:20)
    at ClientRequest.emit (events.js:169:7)
    at tickOnSocket (_http_client.js:502:7)
    at onSocketNT (_http_client.js:514:5)
(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at TLSSocket.addListener (events.js:239:17)
    at TLSSocket.Readable.on (_stream_readable.js:673:33)
    at Request.<anonymous> (C:\Users\Walddys Emmanuel\AppData\Local\atom\app-1.13.1\resources\app\apm\node_modules\npm-registry-client\lib\request.js:153:7)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at ClientRequest.<anonymous> (C:\Users\Walddys Emmanuel\AppData\Local\atom\app-1.13.1\resources\app\apm\node_modules\request\request.js:823:10)
    at emitOne (events.js:82:20)
    at ClientRequest.emit (events.js:169:7)
    at tickOnSocket (_http_client.js:502:7)
    at onSocketNT (_http_client.js:514:5)
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at TLSSocket.addListener (events.js:239:17)
    at TLSSocket.Readable.on (_stream_readable.js:673:33)
    at Request.<anonymous> (C:\Users\Walddys Emmanuel\AppData\Local\atom\app-1.13.1\resources\app\apm\node_modules\npm-registry-client\lib\request.js:153:7)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at ClientRequest.<anonymous> (C:\Users\Walddys Emmanuel\AppData\Local\atom\app-1.13.1\resources\app\apm\node_modules\request\request.js:823:10)
    at emitOne (events.js:82:20)
    at ClientRequest.emit (events.js:169:7)
    at tickOnSocket (_http_client.js:502:7)
    at onSocketNT (_http_client.js:514:5)
(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at TLSSocket.addListener (events.js:239:17)
    at TLSSocket.Readable.on (_stream_readable.js:673:33)
    at Request.<anonymous> (C:\Users\Walddys Emmanuel\AppData\Local\atom\app-1.13.1\resources\app\apm\node_modules\npm-registry-client\lib\request.js:153:7)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at ClientRequest.<anonymous> (C:\Users\Walddys Emmanuel\AppData\Local\atom\app-1.13.1\resources\app\apm\node_modules\request\request.js:823:10)
    at emitOne (events.js:82:20)
    at ClientRequest.emit (events.js:169:7)
    at tickOnSocket (_http_client.js:502:7)
    at onSocketNT (_http_client.js:514:5)
(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at TLSSocket.addListener (events.js:239:17)
    at TLSSocket.Readable.on (_stream_readable.js:673:33)
    at Request.<anonymous> (C:\Users\Walddys Emmanuel\AppData\Local\atom\app-1.13.1\resources\app\apm\node_modules\npm-registry-client\lib\request.js:153:7)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at ClientRequest.<anonymous> (C:\Users\Walddys Emmanuel\AppData\Local\atom\app-1.13.1\resources\app\apm\node_modules\request\request.js:823:10)
    at emitOne (events.js:82:20)
    at ClientRequest.emit (events.js:169:7)
    at tickOnSocket (_http_client.js:502:7)
    at onSocketNT (_http_client.js:514:5)
(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at TLSSocket.addListener (events.js:239:17)
    at TLSSocket.Readable.on (_stream_readable.js:673:33)
    at Request.<anonymous> (C:\Users\Walddys Emmanuel\AppData\Local\atom\app-1.13.1\resources\app\apm\node_modules\npm-registry-client\lib\request.js:153:7)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at ClientRequest.<anonymous> (C:\Users\Walddys Emmanuel\AppData\Local\atom\app-1.13.1\resources\app\apm\node_modules\request\request.js:823:10)
    at emitOne (events.js:82:20)
    at ClientRequest.emit (events.js:169:7)
    at tickOnSocket (_http_client.js:502:7)
    at onSocketNT (_http_client.js:514:5)
(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at TLSSocket.addListener (events.js:239:17)
    at TLSSocket.Readable.on (_stream_readable.js:673:33)
    at Request.<anonymous> (C:\Users\Walddys Emmanuel\AppData\Local\atom\app-1.13.1\resources\app\apm\node_modules\npm-registry-client\lib\request.js:153:7)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at ClientRequest.<anonymous> (C:\Users\Walddys Emmanuel\AppData\Local\atom\app-1.13.1\resources\app\apm\node_modules\request\request.js:823:10)
    at emitOne (events.js:82:20)
    at ClientRequest.emit (events.js:169:7)
    at tickOnSocket (_http_client.js:502:7)
    at onSocketNT (_http_client.js:514:5)
(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at TLSSocket.addListener (events.js:239:17)
    at TLSSocket.Readable.on (_stream_readable.js:673:33)
    at Request.<anonymous> (C:\Users\Walddys Emmanuel\AppData\Local\atom\app-1.13.1\resources\app\apm\node_modules\npm-registry-client\lib\request.js:153:7)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at ClientRequest.<anonymous> (C:\Users\Walddys Emmanuel\AppData\Local\atom\app-1.13.1\resources\app\apm\node_modules\request\request.js:823:10)
    at emitOne (events.js:82:20)
    at ClientRequest.emit (events.js:169:7)
    at tickOnSocket (_http_client.js:502:7)
    at onSocketNT (_http_client.js:514:5)
(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at TLSSocket.addListener (events.js:239:17)
    at TLSSocket.Readable.on (_stream_readable.js:673:33)
    at Request.<anonymous> (C:\Users\Walddys Emmanuel\AppData\Local\atom\app-1.13.1\resources\app\apm\node_modules\npm-registry-client\lib\request.js:153:7)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at ClientRequest.<anonymous> (C:\Users\Walddys Emmanuel\AppData\Local\atom\app-1.13.1\resources\app\apm\node_modules\request\request.js:823:10)
    at emitOne (events.js:82:20)
    at ClientRequest.emit (events.js:169:7)
    at tickOnSocket (_http_client.js:502:7)
    at onSocketNT (_http_client.js:514:5)
(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at TLSSocket.addListener (events.js:239:17)
    at TLSSocket.Readable.on (_stream_readable.js:673:33)
    at Request.<anonymous> (C:\Users\Walddys Emmanuel\AppData\Local\atom\app-1.13.1\resources\app\apm\node_modules\npm-registry-client\lib\request.js:153:7)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at ClientRequest.<anonymous> (C:\Users\Walddys Emmanuel\AppData\Local\atom\app-1.13.1\resources\app\apm\node_modules\request\request.js:823:10)
    at emitOne (events.js:82:20)
    at ClientRequest.emit (events.js:169:7)
    at tickOnSocket (_http_client.js:502:7)
    at onSocketNT (_http_client.js:514:5)
(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at TLSSocket.addListener (events.js:239:17)
    at TLSSocket.Readable.on (_stream_readable.js:673:33)
    at Request.<anonymous> (C:\Users\Walddys Emmanuel\AppData\Local\atom\app-1.13.1\resources\app\apm\node_modules\npm-registry-client\lib\request.js:153:7)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at ClientRequest.<anonymous> (C:\Users\Walddys Emmanuel\AppData\Local\atom\app-1.13.1\resources\app\apm\node_modules\request\request.js:823:10)
    at emitOne (events.js:82:20)
    at ClientRequest.emit (events.js:169:7)
    at tickOnSocket (_http_client.js:502:7)
    at onSocketNT (_http_client.js:514:5)
(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at TLSSocket.addListener (events.js:239:17)
    at TLSSocket.Readable.on (_stream_readable.js:673:33)
    at Request.<anonymous> (C:\Users\Walddys Emmanuel\AppData\Local\atom\app-1.13.1\resources\app\apm\node_modules\npm-registry-client\lib\request.js:153:7)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at ClientRequest.<anonymous> (C:\Users\Walddys Emmanuel\AppData\Local\atom\app-1.13.1\resources\app\apm\node_modules\request\request.js:823:10)
    at emitOne (events.js:82:20)
    at ClientRequest.emit (events.js:169:7)
    at tickOnSocket (_http_client.js:502:7)
    at onSocketNT (_http_client.js:514:5)
(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at TLSSocket.addListener (events.js:239:17)
    at TLSSocket.Readable.on (_stream_readable.js:673:33)
    at Request.<anonymous> (C:\Users\Walddys Emmanuel\AppData\Local\atom\app-1.13.1\resources\app\apm\node_modules\npm-registry-client\lib\request.js:153:7)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at ClientRequest.<anonymous> (C:\Users\Walddys Emmanuel\AppData\Local\atom\app-1.13.1\resources\app\apm\node_modules\request\request.js:823:10)
    at emitOne (events.js:82:20)
    at ClientRequest.emit (events.js:169:7)
    at tickOnSocket (_http_client.js:502:7)
    at onSocketNT (_http_client.js:514:5)
"C:\Users\Walddys" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\WALDDY~1\AppData\Local\Temp\apm-install-dir-117027-5532-1budd7f\package.json'
npm WARN apm-install-dir-117027-5532-1budd7f No description
npm WARN apm-install-dir-117027-5532-1budd7f No repository field.
npm WARN apm-install-dir-117027-5532-1budd7f No README data
npm WARN apm-install-dir-117027-5532-1budd7f No license field.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Users\\Walddys Emmanuel\\AppData\\Local\\atom\\app-1.13.1\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Walddys Emmanuel\\AppData\\Local\\atom\\app-1.13.1\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Walddys Emmanuel\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Walddys Emmanuel\\.atom\\.apmrc" "install" "C:\\Users\\WALDDY~1\\AppData\\Local\\Temp\\d-117027-5532-1xozv3p\\package.tgz" "--runtime=electron" "--target=1.3.13" "--arch=ia32" "--global-style"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! atom-beautify@0.29.17 postinstall: `npm run build-options`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the atom-beautify@0.29.17 postinstall script 'npm run build-options'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the atom-beautify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build-options
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs atom-beautify
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls atom-beautify
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\WALDDY~1\AppData\Local\Temp\apm-install-dir-117027-5532-1budd7f\npm-debug.log
npm ERR! code 1

# Checklist

I have:
- [x] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [ ] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [ ] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by fthylmz** [comment] 2017-02-05 22:11
Same problem, you can see complete log in [here](http://pastebin.com/zC66gb8e).

Maybe something related space character used in username which is "K#zey O#GB" in my situation? 

_# is censored._

**Comment by prettydiff** [comment] 2017-02-07 16:21
Additional similar failures at #1502 and #1504.

**Comment by prettydiff** [comment] 2017-02-13 12:40
It sounds like related issues are fixed with Atom 1.14.1.  Please update and let us know if the problem is still present.

**Comment by laxas** [comment] 2017-02-27 13:59
I have the same Problem with Atom 1.14.3 x64

**Comment by xariaD** [comment] 2017-04-13 04:12
same problem with Atom 1.16.0

**Comment by Glavin001** [comment] 2017-04-13 10:31
> "C:\Users\Walddys" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\WALDDY1\AppData\Local\Temp\apm-install-dir-117027-5532-1budd7f\package.json'

This is an issue with `apm` and users having spaces in their user home path.

See https://github.com/atom/apm/issues/666 . This should be resolved already. Regardless, if it is not working for you I still recommend creating an issue over at https://github.com/atom/apm/issues and please link back to this Issue so others can follow along. Thanks!

**Comment by Glavin001** [comment] 2017-04-15 22:58
I've merged https://github.com/Glavin001/atom-beautify/pull/1598 which should resolve these issues.

Published to v0.29.21.

**Closed by Glavin001** 2017-04-15 22:58 UTC
Labels: install-failed, third-party-bug
