### ISSUE TITLE
Support Embedded Elixir

### ISSUE THREAD

**Issue by tahmina8765** [Glavin001/atom-beautify#1215] opened 2016-09-22 16:30 UTC
# Description

I need beautification support for Embedded Elixir, because is template for elixir which use markup same as html
# Expected Results

The beautified code should have looked like same as html
# Example Code

```
<div class="jumbotron">
  <p><%= handler_info @conn %></p>

  <h3>Keys for the conn Struct</h3>

  <%= for key <- connection_keys @conn do %>
    <%= render "key.html", key: key %>
  <% end %>
</div>
```

Link: [http://www.phoenixframework.org/docs/templates](http://www.phoenixframework.org/docs/templates)

**Comment by Glavin001** [comment] 2016-09-22 16:38
Could you provide some links to documentation and/or example code so we can test? Thank you,

**Comment by tahmina8765** [comment] 2016-09-22 18:57
I have added link and also example code now.

**Comment by prettydiff** [comment] 2016-09-22 21:15
@tahmina8765 Could you try submitting some of the Embedded Elixir code samples through http://prettydiff.com/?m=beautify

If that works for you then this becomes a very simple enhancement.

**Comment by tahmina8765** [comment] 2016-09-23 09:04
Yes, it works perfectly fine, except it shows an error on elixir syntax <%= %>

**Comment by prettydiff** [comment] 2016-09-23 11:22
@tahmina8765 Could you be more specific or provide an example of code that fails?  I will get a fix published in the next version.

**Comment by tahmina8765** [comment] 2016-09-23 12:39
Please check attached image. It works perfectly fine, but shows some red cross in left side.

[embeded-elixer.jpg](http://postimg.org/image/xh4t7awh7/)

Thanks for quick response.

**Comment by tahmina8765** [comment] 2016-09-23 12:55
By the way, according to contributors doc, I tried to added this language in following repository -
https://github.com/tahmina8765/atom-beautify

I can not understand how to test it, I have run it in travis-ci, and there is 2 jobs failed but not for my code.

**Comment by prettydiff** [comment] 2016-09-23 13:15
Adding a new language for use with an existing beautifier should be a matter of a simple configuration update, such as: https://github.com/Glavin001/atom-beautify/blob/master/docs/add-languages-and-beautifiers.md#how-to-add-a-language

You can see all the other language file settings as examples in: https://github.com/Glavin001/atom-beautify/tree/master/src/languages

But, if you are continuing to notice a defect in testing code samples against a supported beautifier that is either a defect or enhancement that has to be worked separately from that beautifier.

**Comment by Glavin001** [comment] 2017-06-04 02:46
Closing as duplicate of https://github.com/Glavin001/atom-beautify/issues/545

**Closed by Glavin001** 2017-06-04 02:46 UTC
Labels: add-language
