### ISSUE TITLE
not work code format php

### ISSUE THREAD

**Issue by jecky2013** [Glavin001/atom-beautify#1390] opened 2016-12-02 07:49 UTC
# Description

The results of beautification are not what I expect.

# Expected Results

The beautified code should have looked like:

```
<INSERT CODE HERE>
```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/c284d645976658823fc79f1e1b02e3d1

# Checklist

- [ ] I have tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [ ] I have reloaded (or restarted) Atom to ensure it is not a caching issue
- [ ] Searched for existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [ ] Generated debugging information and added link for `debug.md` Gist to this issue

**Comment by vnt** [comment] 2016-12-10 13:22
I have the same problem with PHP or PHP + HTML

**Comment by Glavin001** [comment] 2017-01-03 01:15
Duplicate of https://github.com/Glavin001/atom-beautify/issues/457 which will allow both PHP and HTML beautifier applied to single file.

**Closed by Glavin001** 2017-01-03 01:15 UTC
Labels: question
