### ISSUE TITLE
ColdFusion (CFML) Removing Lines from Within <cfquery> Tag

### ISSUE THREAD

**Issue by Jaredra** [Glavin001/atom-beautify#1447] opened 2017-01-05 16:22 UTC
# Description

Just came across this one and it seems to be a big problem. It's actually removing whole lines of code from within a <cfquery> tag. I've isolated it with the code below and it should be reproduce-able. @prettydiff @Glavin001 Edit: Added the debug.md below. Thanks!

# Input Before Beautification

This is what the code looked like before:

```
<cfquery name="getParent" datasource="#datasource#">
	 select	Name as parentname
	 from 	BlogCategory
</cfquery>
```

# Expected Output

The beautified code should have looked like this:

```
<cfquery name="getParent" datasource="#datasource#">
	 select	Name as parentname
	 from 	BlogCategory
</cfquery>
```

# Actual Output

The beautified code actually looked like this:

```
<cfquery name="getParent" datasource="#datasource#">
	 select	Name as parentname

</cfquery>
```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Checklist

I have:
- [x] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [x] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
https://gist.github.com/Jaredra/e7de28a489bb60189914e7fcc92e7a18

**Comment by Jaredra** [comment] 2017-01-05 16:36
https://gist.github.com/Jaredra/e7de28a489bb60189914e7fcc92e7a18

**Comment by prettydiff** [comment] 2017-01-05 19:09
I cannot reproduce this defect in either the latest version of Pretty Diff or in the 1.16.37 version used in Atom Beautify.  I can reproduce the defect though in Atom.  I ran some tests and conclude the defect is in lib/markuppretty.js of Pretty Diff on line 2585.

I will modify the logic to solve for this problem.

**Comment by Jaredra** [comment] 2017-01-05 19:17
Thank you! I really appreciate the speedy turnaround. I'd be looking at some really ugly code without Pretty Diff, so I'm glad I can continue using it.

**Comment by Glavin001** [comment] 2017-04-15 14:48
Looks like this has been resolved in Pretty Diff: https://github.com/prettydiff/prettydiff/issues/402

**Closed by Glavin001** 2017-04-15 14:48 UTC
Labels: third-party-bug
