### ISSUE TITLE
Could not get Shell environment for python

### ISSUE THREAD

**Issue by mehdibaha** [Glavin001/atom-beautify#1459] opened 2017-01-10 13:47 UTC
# Description

When I try to beautify a .py script, I get an error.

# Input Before Beautification

Any .py file

# Expected Output

Expecting a beautified file as output.

# Actual Output

I get an error.

```
Could not get Shell Environment. Exit code: 1, Signal: null
```

# Steps to Reproduce

1. Add beautifier to atom
2. Run command `Atom Beautify` to a python file.
3. An error is returned.

# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/mehdibaha/692c19ce132dc218af277dc3944a37fb

# Checklist

I have:
- [x] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [x] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [x] Generated debugging information and added link for `debug.md` Gist to this issue

**Comment by mehdibaha** [comment] 2017-01-17 13:41
?

**Comment by prettydiff** [comment] 2017-01-17 20:21
I have not been involved with the integration of autopep8 or yapf.  I can the error is generating from here: https://github.com/Glavin001/atom-beautify/search?utf8=%E2%9C%93&q=could+not+get+shell+environment

There are similar issues like this in the past: https://github.com/Glavin001/atom-beautify/search?q=could+not+get+shell+environment&type=Issues&utf8=%E2%9C%93

Is yapf installed on your system?

**Comment by mehdibaha** [comment] 2017-01-18 13:29
Yapf is installed on my system, in addition to autopep8...

**Comment by prettydiff** [comment] 2017-01-18 16:24
Adding @Glavin001

**Comment by juliaanvaneijndt** [comment] 2017-01-26 10:39
I seem to have the same issue with Latex.
Here is my debug file 
https://gist.github.com/juliaanvaneijndt/11ec5f1d00dc40a2d30ba3b794528bc9

**Comment by ostrokach** [comment] 2017-03-13 02:59
What do you get when you run `$(which yapf)` from the command line?

I used conda to install `yapf`, and adding the following line to my Atom init script fixed it for me:

    process.env.PATH = '/home/username/anaconda/bin:' + process.env.PATH

**Comment by mehdibaha** [comment] 2017-03-14 03:41
I get this : `/usr/local/bin/yapf`
Afraid this is not going to help :(

**Comment by Glavin001** [comment] 2017-05-06 21:01
Closing as duplicate of https://github.com/Glavin001/atom-beautify/issues/1113

Please discuss of at https://github.com/Glavin001/atom-beautify/issues/1113

**Closed by Glavin001** 2017-05-06 21:01 UTC
Labels: bug, duplicate
