### ISSUE TITLE
Request for Assembly support.

### ISSUE THREAD

**Issue by VextaRelos** [Glavin001/atom-beautify#1580] opened 2017-04-05 13:33 UTC
Requesting for support from atom-beautify to support the assembly language.

**Comment by Glavin001** [comment] 2017-04-09 18:36
There two open Assembly feature request issues:
- https://github.com/Glavin001/atom-beautify/issues/578
- https://github.com/Glavin001/atom-beautify/issues/804

If you are requesting another Assembly language specifically, please add more details (preferably a link to language documentation) for your specific language, and we can reopen this. If not, then I'm closing this now as a duplicate of the existing issues. Thanks!

**Closed by Glavin001** 2017-04-09 18:36 UTC

**Comment by Glavin001** [comment] 2017-05-14 04:15
@issue-manager duplicates test
