### ISSUE TITLE
Fail to Update to 0.29.16

### ISSUE THREAD

**Issue by pingshunhuangalex** [Glavin001/atom-beautify#1464] opened 2017-01-11 23:52 UTC
# Description

It's been a while now. Since the recent version of atom-beautify is released, I just can't get it to update to 0.29.16 with the error message below. The current version is 0.29.14

```
> atom-beautify@0.29.16 postinstall C:\Users\PINGSH~1\AppData\Local\Temp\apm-install-dir-117012-12520-1rfdoly\node_modules\atom-beautify
> npm run build-options

C:\Users\PINGSH~1\AppData\Local\Temp\apm-install-dir-117012-12520-1rfdoly
`-- (empty)


npm WARN deprecated node-uuid@1.4.7: use uuid module instead
npm WARN deprecated minimatch@0.2.12: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated node-uuid@1.4.0: use uuid module instead
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
'C:\Users\Pingshun' is not recognized as an internal or external command,
operable program or batch file.
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\PINGSH~1\AppData\Local\Temp\apm-install-dir-117012-12520-1rfdoly\package.json'
npm WARN apm-install-dir-117012-12520-1rfdoly No description
npm WARN apm-install-dir-117012-12520-1rfdoly No repository field.
npm WARN apm-install-dir-117012-12520-1rfdoly No README data
npm WARN apm-install-dir-117012-12520-1rfdoly No license field.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Users\\Pingshun Huang\\AppData\\Local\\atom\\app-1.12.9\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Pingshun Huang\\AppData\\Local\\atom\\app-1.12.9\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Pingshun Huang\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Pingshun Huang\\.atom\\.apmrc" "install" "C:\\Users\\PINGSH~1\\AppData\\Local\\Temp\\d-117012-12520-48h38b\\package.tgz" "--runtime=electron" "--target=1.3.13" "--arch=ia32" "--global-style" "--msvs_version=2015"
npm ERR! node v4.4.5
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! atom-beautify@0.29.16 postinstall: `npm run build-options`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the atom-beautify@0.29.16 postinstall script 'npm run build-options'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the atom-beautify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build-options
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs atom-beautify
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls atom-beautify
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\PINGSH~1\AppData\Local\Temp\apm-install-dir-117012-12520-1rfdoly\npm-debug.log
npm ERR! code 1
```

# Steps to Reproduce

1. Just run the update (either within Atom or in command line)

# Checklist

I have:
- [x] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [ ] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [x] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [ ] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by prettydiff** [comment] 2017-01-12 00:58
This is probably a duplicate of #1462 After examining a couple of these defects from multiple users it appears the probably is with the space (in your name for a directory) in the directory path.  I am not sure of the cause of the defect and am wondering if it is NPM related.

**Comment by pingshunhuangalex** [comment] 2017-01-12 01:01
But it worked well previously. Could be because the installation is too slow. Atom tends to delete the installation file before it finishes if it's taking too long.

**Comment by prettydiff** [comment] 2017-01-12 01:14
I really don't know yet.  I will see if Glavin has any insight on what could be causing this.

**Comment by campusman** [comment] 2017-01-12 04:58
I am chiming in to report the same issue...Atom 1.13.0 on Windows 10 x64. Been about a week or more now, same failure to update error, am currently on atom-beautify 0.29.14.

**Comment by Glavin001** [comment] 2017-01-13 17:26
> 'C:\Users\Pingshun' is not recognized as an internal or external command,

and

> with the space (in your name for a directory) in the directory path

This is a duplicate issue: https://github.com/Glavin001/atom-beautify/issues/1434
Which is actually an `apm` bug: https://github.com/atom/apm/issues/666
Which has been fixed with https://github.com/atom/apm/commit/e8b28ce31dc55890ca978ebe889a3de945d7cd99

Also, these installation issues are almost always outside of the control of Atom-Beautify. See https://github.com/Glavin001/atom-beautify/issues/1462#issuecomment-272494075 for my explanation.

@pingshunhuangalex's issue described above is a space in the name which is apparent because of the error report which shows a truncated path:

> 'C:\Users\Pingshun' is not recognized as an internal or external command,

And it has already been addressed as an `apm` bug.

If you are experiencing installation issues, I recommend contacting `apm` team over at https://github.com/atom/apm as it will be highly unlikely Atom-Beautify has control over the issue. Atom-Beautify uses both `npm` and `apm` which are official / standard registries supported for Atom packages. The only difference from other Atom packages is we also use `postinstall` script, which is supposed to be supported by `apm`. So if there are installation issues, then it is likely `apm`'s domain. If there are network issues, it is absolutely going to be `apm` or `npm`'s domain.

Please let me know if you have any questions, and feel free to CC me on your issues over at `apm`. I would love to help, however it will need to be fixes on `apm` most of the time for issues like this :wink:. Thanks!

**Closed by Glavin001** 2017-01-13 17:26 UTC
Labels: bug, duplicate, high priority
