### ISSUE TITLE
Format .TSS as using the 'JS/JSON' formatting

### ISSUE THREAD

**Issue by Pinesy** [Glavin001/atom-beautify#216] opened 2015-02-19 16:48 UTC
Hi, I had it set up where TSS(titanium style sheets) was using JSON formatting, and it works fine for beautifying (great spacing, formatting, etc). However, I have installed a tss syntax package and no longer will the Beautify run on the .tss files(invalid grammar). I was wondering if there's a way to force .tss files to be beautified with the json/js formatter? I tried to look at the source code and couldn't figure out where I could just make it get formatted with the JS/JSON formatter.

This would be a great help to any tss users.

Before JS formatting:
```
".container": {
  backgroundImage:'images/bgbg-builder.png',
  width: 1024,
  height: 752,
  top:0,
  left:0
},
"#blackArrow": {
  touchEnabled: false,
  backgroundImage: 'images/arrow-builder.png',
  width: 15,
  height: 10,
  top: 128,
  left: 165,
  pos0: {
    left: 165,
    duration: 200
  },
  pos1: {
    left: 301,
    duration: 200
  },
  pos2: {
    left: 437,
    duration: 200
  },
  pos3: {
    left: 573,
    duration: 200
  }
},
```

after.. 

```
".container": {
    backgroundImage: 'images/bgbg-builder.png',
    width: 1024,
    height: 752,
    top: 0,
    left: 0
},
"#blackArrow": {
    touchEnabled: false,
    backgroundImage: 'images/arrow-builder.png',
    width: 15,
    height: 10,
    top: 128,
    left: 165,
    pos0: {
        left: 165,
        duration: 200
    },
    pos1: {
        left: 301,
        duration: 200
    },
    pos2: {
        left: 437,
        duration: 200
    },
    pos3: {
        left: 573,
        duration: 200
    }
},
```

**Comment by Glavin001** [comment] 2015-02-20 08:20
I am away for the next few days and when I am back I have exams, so it is unlikely I will resolve this issue personally. If you want to get this feature added, it sounds like you could submit a simple Pull Request with the appropriate grammar added to https://github.com/Glavin001/atom-beautify/blob/master/lib/language-options.coffee#L399 and with a sample TSS test file that passes it's beautification tests. Hope that helps!

**Comment by Glavin001** [comment] 2015-03-16 05:24
Duplicate of #122 

By the way, thanks to @prettydiff, this is almost ready to be published!

**Closed by Glavin001** 2015-03-16 05:24 UTC
Labels: feature
