### ISSUE TITLE
Beautifying hangs and also freezes up Atom

### ISSUE THREAD

**Issue by foutrelis** [Glavin001/atom-beautify#1733] opened 2017-06-20 10:57 UTC
Starting with v0.30.0, atom-beautify hangs while beautifying code (tried C and Go files). There is a `bash -ilc env` process that uses 100% of one core while other cores are tied up by Atom/Electron processes.

Doing a quick `git bisect` shows commit bc21afd424728591ea45eb8c1153df0a1b719a70 as the first commit that displays this behavior.

I'm using Atom 1.18 (running on Electron 1.4.16) on Arch Linux x86_64.

**Comment by Glavin001** [comment] 2017-06-20 11:48
> There is a bash -ilc env process that uses 100% of one core while other cores are tied up by Atom/Electron processes.

Interesting, this child process for `bash -ilc env` should not be blocking. This is good to know so I can focus my investigations!

---

Closing this as a duplicate of https://github.com/Glavin001/atom-beautify/issues/1728 . Would you be able to copy over any additional debugging information you have discovered? I want to keep all of the same discussion on https://github.com/Glavin001/atom-beautify/issues/1728 . Thank you!

**Closed by Glavin001** 2017-06-20 11:48 UTC

**Comment by vinayait** [comment] 2018-08-30 22:58
Atom beautify stuck in 'Beautification in progress'. Can someone help ? Using version 1.30.0
