### ISSUE TITLE
Feature request: Groovy support

### ISSUE THREAD

**Issue by rbatllet** [Glavin001/atom-beautify#739] opened 2016-01-11 09:45 UTC
Could you add support in the near future to the groovy language as well?

http://www.groovy-lang.org/documentation.html#languagespecification

Thank you!

**Comment by tobilarscheid** [comment] 2016-04-05 18:45
Seems like a duplicate of https://github.com/Glavin001/atom-beautify/issues/371

**Comment by prettydiff** [comment] 2016-04-05 18:58
Thanks @tobilarscheid 

Closing as this is a duplicate.

**Closed by prettydiff** 2016-04-05 18:58 UTC
Labels: add-language, duplicate
