### ISSUE TITLE
Add support elixir

### ISSUE THREAD

**Issue by yaBliznyk** [Glavin001/atom-beautify#1431] opened 2016-12-30 03:32 UTC
"ex" and "exs" : {
    "indent_size": 2,
    "indent_char": " ",
    "other": " ",
    "indent_level": 0,
    "indent_with_tabs": false,
    "preserve_newlines": true,
    "max_preserve_newlines": 2,
    "jslint_happy": true,
    "indent_handlebars": true
  }

"html.eex" like "html"

**Comment by Glavin001** [comment] 2016-12-30 05:15
Please clarify what you are asking for.

**Comment by yaBliznyk** [comment] 2016-12-30 05:21
Please add support to [elixir lang](http://elixir-lang.org/)
http://joxi.ru/v29785xu3GkV4r - .exs files
http://joxi.ru/gmvjNQ0sLxJ7Bm - .ex like .exs
and http://joxi.ru/EA4axDRhwDGLar - .html.eex like html

**Comment by Glavin001** [comment] 2016-12-30 05:32
Duplicate of https://github.com/Glavin001/atom-beautify/issues/545

**Closed by Glavin001** 2016-12-30 05:32 UTC
Labels: waiting-for-user-information
