### ISSUE TITLE
Could not find 'php-cs-fixer'. The program may not be installed.

### ISSUE THREAD

**Issue by EvKoh** [Glavin001/atom-beautify#584] opened 2015-10-02 20:41 UTC
See https://github.com/FriendsOfPHP/PHP-CS-Fixer for program installation instructions.
Your program is properly installed if running 'which php-cs-fixer' in your Terminal returns an absolute path to the executable. If this does not work then you have not installed the program correctly and so Atom Beautify will not find the program. Atom Beautify requires that the program be found in your PATH environment variable. 
Note that this is not an Atom Beautify issue if beautification does not work and the above command also does not work: this is expected behaviour, since you have not properly installed your program. Please properly setup the program and search through existing Atom Beautify issues before creating a new issue. See https://github.com/Glavin001/atom-beautify/search?q=php-cs-fixer&type=Issues for related Issues and https://github.com/Glavin001/atom-beautify/tree/master/docs for documentation. If you are still unable to resolve this issue on your own then please create a new issue and ask for help.

Error: Could not find 'php-cs-fixer'. The program may not be installed.
  at PHPCSFixer.module.exports.Beautifier.commandNotFoundError (/home/dev/.atom/packages/atom-beautify/src/beautifiers/beautifier.coffee:178:14)
  at /home/dev/.atom/packages/atom-beautify/src/beautifiers/beautifier.coffee:274:25
  at tryCatcher (/usr/share/atom/resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/util.js:26:23)
  at Promise._settlePromiseFromHandler (/usr/share/atom/resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/promise.js:507:31)
  at Promise._settlePromiseAt (/usr/share/atom/resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/promise.js:581:18)
  at Promise._settlePromises (/usr/share/atom/resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/promise.js:697:14)
  at Async._drainQueue (/usr/share/atom/resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/async.js:123:16)
  at Async._drainQueues (/usr/share/atom/resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/async.js:133:10)
  at MutationObserver.Async.drainQueues (/usr/share/atom/resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/async.js:15:14)
  at process._tickCallback (node.js:365:9)

which php-cs-fixer ---> null

![capture d ecran de 2015-10-02 22 40 27](https://cloud.githubusercontent.com/assets/1309463/10257253/82511e62-6956-11e5-8b92-7c1fe0934928.png)

**Comment by vitkabele** [comment] 2015-10-05 18:56
Hey, i've the same issue. It's installed, but not working. I think its neccessary to change the PHP-cs-fixer execution path

**Comment by Glavin001** [comment] 2015-10-05 19:16
@EvKoh :

If you run `which php-cs-fixer` and it does not return a path then it was not installed properly. You should see https://github.com/FriendsOfPHP/PHP-CS-Fixer to install the executable.

> apm install php-cs-fixer

You just installed another package: https://atom.io/packages/php-cs-fixer 
Did you read the error message instructions and look at https://github.com/FriendsOfPHP/PHP-CS-Fixer for the installation instructions?

Please follow the instructions that Atom Beautify tells you to follow:
> See https://github.com/FriendsOfPHP/PHP-CS-Fixer for program installation instructions.
Your program is properly installed if running 'which php-cs-fixer' in your Terminal returns an absolute path to the executable. If this does not work then you have not installed the program correctly and so Atom Beautify will not find the program. Atom Beautify requires that the program be found in your PATH environment variable. 
Note that this is not an Atom Beautify issue if beautification does not work and the above command also does not work: this is expected behaviour, since you have not properly installed your program. Please properly setup the program and search through existing Atom Beautify issues before creating a new issue. See https://github.com/Glavin001/atom-beautify/search?q=php-cs-fixer&type=Issues for related Issues and https://github.com/Glavin001/atom-beautify/tree/master/docs for documentation. If you are still unable to resolve this issue on your own then please create a new issue and ask for help.

---

@vitkabele :
>  I think its neccessary to change the PHP-cs-fixer execution path
You are correct. If you run `which php-cs-fixer` and it does not work and returns without displaying the path for the php-cs-fixer executable then you need to setup your PATH environment variable.

I'd recommend taking a read of some of the other related issues if you need more help: https://github.com/Glavin001/atom-beautify/search?q=php-cs-fixer&type=Issues

**Comment by Glavin001** [comment] 2015-10-05 19:17
I am closing this issue because the instructions given in the error were obviously not followed.

The first line of the error's instructions were:
> See https://github.com/FriendsOfPHP/PHP-CS-Fixer for program installation instructions.
And instead `apm install php-cs-fixer` was run.

Please re-read the errors that have been written to help you.

**Closed by Glavin001** 2015-10-05 19:17 UTC

**Comment by vitkabele** [comment] 2015-10-07 12:47
Hey i'm not so stupid. I did so, then i posted the comment

**Comment by Glavin001** [comment] 2015-10-07 13:54
>  I did so, then i posted the comment

@vitkabele , if you were referring to the comment:
> I am closing this issue because the instructions given in the error were obviously not followed.

That was not aimed at *you*. I expect you did follow the installation instructions at https://github.com/FriendsOfPHP/PHP-CS-Fixer and you did not run `apm install php-cs-fixer`, which was not indicated in any of the installation documentation.

For you (and anyone else for that matter), I had recommended reading the [other related Issues](https://github.com/Glavin001/atom-beautify/search?q=php-cs-fixer&type=Issues) as it will help answer your questions and with fixing your PATH environment variable such that Atom Beautify can detect your `php-cs-fixer` executable path.
You can manually set the absolute path to your php-cs-fixer executable using the `PHP-CS-Fixer Path` option: https://github.com/Glavin001/atom-beautify/blob/master/docs/options.md#php---php-cs-fixer-path

It depends on if you are running on Windows or Mac/Linux.
- For Windows, take a look at these: https://github.com/Glavin001/atom-beautify/search?utf8=%E2%9C%93&q=php-cs-fixer+not+found+windows&type=Issues
- For Mac/Linux: https://github.com/Glavin001/atom-beautify/search?utf8=%E2%9C%93&q=php-cs-fixer+not+found+mac&type=Issues

Here are some steps:
  - Run (Mac/Linux) `which php-cs-fixer` or (Windows) `where php-cs-fixer` in your shell to retrieve the path to your executable path
    - If this does work and returns a path, then your PATH environment variable is working and setup. Try to restart Atom and see if that helps, it may need to reload your PATH environment variable.
    - If this does not return a valid path, then your PATH environment variable is not working and not yet setup properly. Depending on your operating system, Windows or Linux or Mac, you will have to add the path of your php-cs-fixer's installation path to your PATH environment variable. Read issues from the links above or Google for more help.

**Comment by Glavin001** [comment] 2017-06-04 18:28
I really want to focus on improving the installation experience for users. I have created a new Issue, #1687, to target this problem. Please provide your feedback! Thanks in advance.

**Comment by phamthanhnghia** [comment] 2018-01-31 01:35
**I fixed this.** You need uninstall **atom-beautify**

**Comment by sravanikadali69** [comment] 2020-01-20 09:16
Hi Team,
Can Php fixer CS can be used on Xcode.
Your reply would be appreciated.
