### ISSUE TITLE
phpcbf 3 refuses to process any file with no extension

### ISSUE THREAD

**Issue by scragz** [Glavin001/atom-beautify#1684] opened 2017-05-27 08:36 UTC
# Description

On OSX at least, Atom Beautify copies the file to a tmp file, e.g. /var/folders/fb/w7b6kjt94s7gv28m5jw7wlmr0000gn/T/temp117427-5607-7khx6t.2fzvtsatt9

However, phpcbf (3.0) will never process any file without an extension.

In phpcbf source code:

function shouldProcessFile($path) {
// Check that the file's extension is one we are checking.
// We are strict about checking the extension and we don't
// let files through with no extension or that start with a dot.

I am going to work around this by modifying my local phpcbf install but maybe Beautify should preserve the file extension when making the tmp file as there doesn't seem to be any option that will override phpcbf's extension checking (--extension=whatever check happens after they check that there is any extension).

**Comment by Glavin001** [comment] 2017-05-28 05:39
I think this should be solved with https://github.com/Glavin001/atom-beautify/pull/1649 

Closing as a duplicate of https://github.com/Glavin001/atom-beautify/issues/1487 which is resolved already by #1649.

Published to v0.29.26

**Closed by Glavin001** 2017-05-28 05:39 UTC
