### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by vektorich** [Glavin001/atom-beautify#518] opened 2015-08-19 14:27 UTC
Usage: autopep8 [options] [filename [filename ...]] Use filename '-' for stdin.

autopep8: error: no such option: --indent-size
Usage: autopep8 [options] [filename [filename ...]]
Use filename '-'  for stdin.
autopep8: error: no such option: --indent-size
Hide Stack Trace
Error: Usage: autopep8 [options] [filename [filename ...]]
Use filename '-'  for stdin.
autopep8: error: no such option: --indent-size
  at /usr/local/google/home/sashagl/.atom/packages/atom-beautify/src/beautifiers/beautifier.coffee:258:27
  at tryCatcher (/usr/share/atom/resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/util.js:26:23)
  at Promise._settlePromiseFromHandler (/usr/share/atom/resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/promise.js:503:31)
  at Promise._settlePromiseAt (/usr/share/atom/resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/promise.js:577:18)
  at Promise._settlePromises (/usr/share/atom/resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/promise.js:693:14)
  at Async._drainQueue (/usr/share/atom/resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/async.js:123:16)
  at Async._drainQueues (/usr/share/atom/resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/async.js:133:10)
  at MutationObserver.Async.drainQueues (/usr/share/atom/resources/app.asar/node_modules/babel-core/node_modules/bluebird/js/main/async.js:15:14)
  at process._tickCallback (node.js:367:9)

autopep8 --version
autopep8 0.9.1

**Comment by Glavin001** [comment] 2015-08-19 14:29
Looks like a duplicate of issue #419 

See https://github.com/Glavin001/atom-beautify/issues/419#issuecomment-115438486 for solution:
> It works with 1.5.7
Ubuntu 15.04 repo has 0.9.1 version. Needed to apt-get remove it then install through pip:
pip install autopep8

**Closed by Glavin001** 2015-08-19 14:29 UTC
