### ISSUE TITLE
TextBuffer.on is deprecated.

### ISSUE THREAD

**Issue by Schmidtwar** [Glavin001/atom-beautify#302] opened 2015-05-03 11:09 UTC
Use TextBuffer::onWillSave instead. A TextBuffer instance is no longer provided as a callback argument.
```
TextBuffer.on (C:\Users\Schmidtwar\AppData\Local\atom\app-0.196.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1179:16)
Object.subscribeWith (C:\Users\Schmidtwar\AppData\Local\atom\app-0.196.0\resources\app.asar\node_modules\emissary\lib\subscriber.js:28:32)
Object.subscribe (C:\Users\Schmidtwar\AppData\Local\atom\app-0.196.0\resources\app.asar\node_modules\emissary\lib\subscriber.js:63:21)
<unknown> (C:\Users\Schmidtwar\.atom\packages\atom-beautify\src\beautify.coffee:322:13)
```

**Comment by Schmidtwar** [comment] 2015-05-03 11:09
When I'm saving this error comes up.

**Comment by Glavin001** [comment] 2015-05-03 14:22
Duplicate of #289.

**Closed by Glavin001** 2015-05-03 14:22 UTC

**Comment by Glavin001** [comment] 2015-05-05 17:50
Published to v0.26.5
