### ISSUE TITLE
Missing settings

### ISSUE THREAD

**Issue by CorentinAndre** [Glavin001/atom-beautify#1587] opened 2017-04-10 16:01 UTC
Hi, I'm missing all the options inside atom-beautify settings.
![capture du 2017-04-10 17 59 21](https://cloud.githubusercontent.com/assets/11957741/24870694/71ef4810-1e17-11e7-813d-6eae874eba9d.png)

I've run through some issues like this one, but didn't manage to fix it.

Any help would be really appreciated :smiley:

**Comment by CorentinAndre** [comment] 2017-04-20 08:14
Seems it got resolved in last update for me, but didn't see any mention in the changelog

**Comment by Glavin001** [comment] 2017-04-20 13:24
Sorry about that! It was an issue with publishing version v0.29.21.

Duplicate of https://github.com/Glavin001/atom-beautify/issues/1601 and https://github.com/Glavin001/atom-beautify/issues/1599

Fix https://github.com/Glavin001/atom-beautify/commit/46a438d09e1e09185a3bb93b967558b24a842d57

Published to v0.29.22

Please let me know if you have any more problems!

**Closed by Glavin001** 2017-04-20 13:24 UTC
Labels: bug

**Comment by iNeedICS** [comment] 2019-05-03 19:48
This is currently happening to me. 

`SD-BMALDONADO :: ~ % atom --version
Atom    : 1.36.1
Electron: 2.0.18
Chrome  : 61.0.3163.100
Node    : 8.9.3`
