### ISSUE TITLE
Save on the first file get a little freeze time.

### ISSUE THREAD

**Issue by luunguyenbk** [Glavin001/atom-beautify#679] opened 2015-11-21 10:31 UTC
I'm using Atom 1.2.2 on Macos Yosermite, Atom-Beautify 0.28.19. When i first open Atom and save, it seem get a little freeze about 2-3 seconds, it only happen on the first file.
When i disable Atom-beautify, it don't happen anymore.
Is this a bug on Atom-Beautify ?

**Comment by Glavin001** [comment] 2015-11-22 20:12
Here is the applicable code for beautify on save functionality: https://github.com/Glavin001/atom-beautify/blob/master/src/beautify.coffee#L423-L467

~~The part that would take time and could be causing the little freeze would be here: https://github.com/Glavin001/atom-beautify/blob/master/src/beautify.coffee#L427-L444~~

Since you indicated that it only happens on the first file, it would suggest that subsequent requests are using a cache and therefore faster. All of the `require` calls would be applicable then, since they have a built-in cache.

It could be because of the `activationCommands`: https://github.com/Glavin001/atom-beautify/blob/master/package.json#L105-L106
When you save, this triggers Atom Beautify to activate and thus `require` all of its dependencies. This could take time. After the first time, everything should be processed and cached.
This would make a lot of sense.

The best way to reduce the activation time and reduce the freeze time when first activating Atom Beautify would be to look at:
- https://github.com/Glavin001/atom-beautify/blob/master/src/beautify.coffee#L3-L13
- https://github.com/Glavin001/atom-beautify/blob/master/src/beautify.coffee#L464-L471

And try to cut things down.
I have not run any benchmarks however I presume that constructing the `beautifier` at https://github.com/Glavin001/atom-beautify/blob/master/src/beautify.coffee#L10 will take a significant amount of time on load.

```
Beautifiers = require("./beautifiers")
beautifier = new Beautifiers()
``` 

The main `Beautifier` code can be found at https://github.com/Glavin001/atom-beautify/blob/master/src/beautifiers/index.coffee
It probably has the most room for optimization and performance improvements.

**Comment by ypresto** [comment] 2016-03-19 14:41
This also affects "Installed Packages" page in preferences.

**Comment by Glavin001** [comment] 2016-03-29 17:33
I'm going to count this issue as a duplicate of https://github.com/Glavin001/atom-beautify/issues/876 as #876 has some more information that I can use for debugging.
Please continue discussion of this issue over at #876. Thank you.

**Closed by Glavin001** 2016-03-29 17:33 UTC
Labels: bug, duplicate
