### ISSUE TITLE
atom-beautify not supported of blade language

### ISSUE THREAD

**Issue by tornadomajid** [Glavin001/atom-beautify#1938] opened 2017-11-12 14:25 UTC
i am try add blade language to atom-beautify but not woking.
and not beautify blade.php files.
please add this language in another update
thanks.

**Comment by darron1217** [comment] 2018-03-30 08:32
@tornadomajid  We're discussing about this issue at #448

**Comment by szeck87** [comment] 2018-03-30 14:35
Closing as a duplicate of #448.

**Closed by szeck87** 2018-03-30 14:35 UTC
Labels: duplicate
