### ISSUE TITLE
Hide error messages - Null Grammar

### ISSUE THREAD

**Issue by ffsantos92** [Glavin001/atom-beautify#290] opened 2015-04-25 17:18 UTC
I think these error messages should be hidden:
```
Unsupported language for grammar 'Null Grammar'.
```

# Atom Beautify - Debugging information

The following debugging information was generated by `Atom Beautify` on `Sat Apr 25 2015 18:17:08 GMT+0100 (WEST)`.

---

**Platform**: linux

## Versions

**Atom Version**: 0.175.0

**Atom Beautify Version**: 0.24.1

## Original file to be beautified

**Original File Path**: `/hidden_path/.gitignore`

**Original File Grammar**: Null Grammar

**Original File Contents**: 
```Null Grammar
*.raw

```

## Beautification options

**Editor Options**: 
Options from Atom Editor settings
```json
{
    "indent_size": 4,
    "indent_char": " ",
    "indent_with_tabs": false
}
```

**Config Options**: 
Options from Atom Beautify package settings
```json
{
    "js": {
        "break_chained_methods": true,
        "eval_code": true,
        "end_with_newline": true,
        "indent_size": 4,
        "indent_char": " ",
        "indent_level": 0,
        "indent_with_tabs": false,
        "preserve_newlines": true,
        "max_preserve_newlines": 10,
        "space_in_paren": false,
        "jslint_happy": false,
        "space_after_anon_function": false,
        "brace_style": "collapse",
        "keep_array_indentation": false,
        "keep_function_indentation": false,
        "space_before_conditional": true,
        "unescape_strings": false,
        "wrap_line_length": 0
    },
    "css": {
        "selector_separator_newline": true,
        "newline_between_rules": true,
        "preserve_newlines": true,
        "indent_size": 4,
        "indent_char": " "
    },
    "html": {
        "indent_inner_html": true,
        "end_with_newline": true,
        "htmlbeautifier_path": "",
        "indent_size": 4,
        "indent_char": " ",
        "brace_style": "collapse",
        "indent_scripts": "normal",
        "wrap_line_length": 250,
        "wrap_attributes": "auto",
        "wrap_attributes_indent_size": 4,
        "preserve_newlines": true,
        "max_preserve_newlines": 10,
        "unformatted": [
            "a",
            "sub",
            "sup",
            "b",
            "i",
            "u"
        ]
    },
    "php": {
        "cs_fixer_path": "/usr/local/bin/php-cs-fixer",
        "fixers": "",
        "level": ""
    },
    "sql": {
        "indent_size": 4,
        "keywords": "upper",
        "identifiers": "lower",
        "sqlformat_path": ""
    },
    "markdown": {
        "pandoc_path": "",
        "yaml_front_matter": true
    },
    "perl": {
        "perltidy_path": "perltidy",
        "perltidy_profile": ""
    },
    "python": {
        "autopep8_path": "",
        "max_line_length": 79,
        "indent_size": 4,
        "ignore": [
            "E24"
        ]
    },
    "ruby": {
        "rbeautify_path": ""
    },
    "c": {
        "uncrustifyPath": "",
        "configPath": ""
    },
    "cpp": {
        "uncrustifyPath": "",
        "configPath": ""
    },
    "objectivec": {
        "uncrustifyPath": "",
        "configPath": ""
    },
    "cs": {
        "uncrustifyPath": "",
        "configPath": ""
    },
    "d": {
        "uncrustifyPath": "",
        "configPath": ""
    },
    "java": {
        "uncrustifyPath": "",
        "configPath": ""
    },
    "pawn": {
        "uncrustifyPath": "",
        "configPath": ""
    },
    "vala": {
        "uncrustifyPath": "",
        "configPath": ""
    }
}
```

**Home Options**: 
Options from `/home/fabio/.jsbeautifyrc`
```json
{}
```

**EditorConfig Options**: 
Options from [EditorConfig](http://editorconfig.org/) file
```json
{}
```

**Project Options**: 
Options from `.jsbeautifyrc` files starting from directory `/hidden_path` and going up to root
```json
[
    {},
    {},
    {},
    {},
    {},
    {}
]
```

## Logs

**Error logs**: *Not yet supported*

**Comment by Glavin001** [comment] 2015-04-28 14:42
Duplicate of #105 and #118

Please see Package Setting `muteUnsupportedLanguageErrors`: https://github.com/Glavin001/atom-beautify#package-options

**Closed by Glavin001** 2015-04-28 14:42 UTC
