### ISSUE TITLE
Feature request: Add shell/bash beautifier.

### ISSUE THREAD

**Issue by jbkr** [Glavin001/atom-beautify#604] opened 2015-10-13 10:33 UTC
There appears to be no beautify support for bash on the OSX version (and possibly other versions). Are there any plans to introduce this feature? Perhaps there is a bug and there is already support.

[Debugging information.](https://gist.github.com/jbkr/34f4251d28c791a228a4)

**Comment by jwigley** [comment] 2016-06-21 05:33
Looks like a duplicate of https://github.com/Glavin001/atom-beautify/issues/451.

**Closed** 2016-06-21 13:09 UTC
Labels: add-language, duplicate
