### ISSUE TITLE
More JS options for HTML files?

### ISSUE THREAD

**Issue by mercmobily** [Glavin001/atom-beautify#1118] opened 2016-08-07 17:01 UTC
# Description

I am developing in Polymer. Basically every file I edit is HTML -- they just so happen to be mostly full of Javascript. However, atom-beautify treats them as HTML files -- and they have therefore far fewer options than JS files. For example I would like to enable "End with Comma" etc.

Is there a way to have the (many!) extra options for HTML files containing Javascript as well?
# Expected Results

I expect to have the same Javascript formatting options for Javascript contained in HTML as I have for Javascript files.

NOTE: There is no code that beautify the wrong way.
# Steps to Reproduce
1. Open a .html file
2. Beautify it
3. Imagine you want to have the options (available in the Javascript beautifier) to have "Space in paren"
4. You discover that you can't -- "Space in paren" is only available for straight Javascript files.
5. You see that there ARE some Javascript options in the HTML config section, but not as many
# Debug

There is no debug.md in my case
# Checklist
- [X] I have tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [X] I have reloaded (or restarted) Atom to ensure it is not a caching issue
- [X] Searched for existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
  so I know this is not a duplicate issue
- [-] Generated debugging information and added link for `debug.md` Gist to this issue

**Comment by Glavin001** [comment] 2016-08-08 03:30
Please follow the issue template provided. More specifically, adding a link to the required `debug.md` Gist which includes debugging information that answers our most commonly asked questions: https://github.com/Glavin001/atom-beautify/blob/master/ISSUE_TEMPLATE.md#how-to-create-debugmd-gist
Thank you.

**Comment by mercmobily** [comment] 2016-08-08 03:40
I am a little confused by your request. I hope this makes it clearer!

**Comment by mercmobily** [comment] 2016-08-09 12:36
I just wanted to make sure that you got all the info you need. I noticed that the waiting-for-user-information is still on -- hence my double-checking!

**Comment by prettydiff** [comment] 2016-08-09 12:52
I think he just wants JavaScript options available to HTML grammars

**Comment by Glavin001** [comment] 2016-08-09 19:17
`js-beautify`, a beautifier for HTML (and CSS), only supports a limited subset of options in comparison to JavaScript. See https://github.com/beautify-web/js-beautify#css--html 
> The CSS & HTML beautifiers are much simpler in scope, and possess far fewer options.

Of course, if Pretty Diff supports these missing options then they should be added. 

It is important to note that these beautifiers, such as JS-Beautify, often only support a *single language*. HTML and JavaScript beautification are exclusive from each other. This is the same problem as with PHP, which has both PHP and HTML code. A PHP beautifier only formats PHP code and leaves HTML unformatted. This is something we need to work on such that a single file can have multiple beautifiers applied.
I believe this is the relevant, open issue: https://github.com/Glavin001/atom-beautify/issues/457

**Comment by prettydiff** [comment] 2016-08-09 19:36
The way I work this for Pretty Diff is that I have a single options object.  This object doesn't care whether you are beautifying, minifying, or using some other mode and it doesn't care what language you are using.  The options in that object either apply universally, are not used where they don't apply, or allow language specific values for user selective application.

The logic on this is fairly standard and universal through out Pretty Diff, but I declare the object in multiple locations, which is really sloppy.  I have been thinking about creating a new library file to store a declared object that lists all options and their default values and also storing option specific functions in there.

I used to pass separate specific option lists to the respective parsers until a bug was reported here last year that I wasn't passing appropriate options around for things like JSX.  Now I pass this global object between the various parses as they are called.  Two things I have to keep in mind:

* There are minor changes I have to make to this big object each time I pass it around, which is mostly just changing the value of options.source to the content specific to the given parser call.
* I also have to be sure not to overwrite some option values with a default too specific to a given parser.  For example I have options like `objsort` and `vertical` where I allow language specific values in case you want to sort HTML attributes but not CSS properties.

**Comment by Glavin001** [comment] 2017-01-01 03:51
I'm going to close this as a duplicate of #457 which will allow both JavaScript and HTML beautifiers to be used one this single file.

**Closed by Glavin001** 2017-01-01 03:51 UTC
Labels: enhancement
