### ISSUE TITLE
php-cs-fixer doesn't work

### ISSUE THREAD

**Issue by MrVil** [Glavin001/atom-beautify#368] opened 2015-05-26 07:26 UTC
Hi
It seems that beautify for PHP doesn't work. I get this message

    spawn php-cs-fixer ENOENT

    Error: spawn php-cs-fixer ENOENT
      at exports._errnoException (util.js:734:11)
      at Process.ChildProcess._handle.onexit (child_process.js:1035:32)
      at child_process.js:1127:20
      at process._tickCallback (node.js:357:13)

**Comment by Glavin001** [comment] 2015-05-28 00:50
Duplicate of #288

Please read the discussion and if you still have further questions let me know.

The solution should be, in short, configure Atom Beautify with the absolute path to `php-cs-fixer`. 
To configure, go to `Atom Beautify` package settings -> `Language Config - PHP - CS Fixer Path` -> enter the absolute path to your `php-cs-fixer.phar` file.

**Closed by Glavin001** 2015-05-28 00:50 UTC
Labels: question

**Comment by Glavin001** [comment] 2015-05-28 01:10
@MrVil could you confirm that you are running Windows? The solution above will work the same, however it's important that I know what platforms are not working, as this should be automatically detected and this error does not occur.
