### ISSUE TITLE
Requesting beautify support for "Velocity (HTML)" with extension .vm

### ISSUE THREAD

**Issue by zyxdick6** [Glavin001/atom-beautify#721] opened 2015-12-23 06:18 UTC
Atom Beautify could not determine a supported beautifier to handle this file with grammar "Velocity (HTML)" and extension "vm". If you would like to request support for this file and its language, please create an issue for Atom Beautify at https://github.com/Glavin001/atom-beautify/issues

**Comment by prettydiff** [comment] 2015-12-29 13:42
Do you have better documentation I could look at?  This is the best I could find from their site: https://velocity.apache.org/dvsl/devel/users-guide.html

Based upon that documentation it looks like XML/HTML wrapped in blocks defined as `#match()` and `#end` plus methods defined as `$node.` and `$context.`.

Is there more to velocity?

**Comment by rediris** [comment] 2016-02-26 20:12
This is a duplicate of https://github.com/Glavin001/atom-beautify/issues/522

**Closed** 2016-02-26 20:19 UTC
Labels: add-language, duplicate
