### ISSUE TITLE
When updating atom-beautify the progress UI fails to recognize when installing has finished

### ISSUE THREAD

**Issue by frankhale** [Glavin001/atom-beautify#401] opened 2015-06-15 20:01 UTC
This one is a bit weird and I don't know if the problem is with Atom or atom-beautify. I've noticed on several releases of atom-beautify that when I go to update it the UI which shows the update progress never finishes. It will continue to appear as if it's updating indefinitely. If I click on "check for updates" then Atom will recognize that the update has finished.

I'm currently on Atom 0.209 and atom-beautify 0.28.5 but I've noticed this with at least 5 versions of atom-beautify. This is also the only package that I'm using that seems to have this issue.

**Comment by Glavin001** [comment] 2015-06-15 20:43
Duplicate of https://github.com/Glavin001/atom-beautify/issues/391

I believe the problem is that [Atom Beautify has a lot of dependencies](https://github.com/Glavin001/atom-beautify/blob/master/package.json#L55-L85). https://github.com/Glavin001/atom-beautify/issues/320 should resolve this.

Thanks for your feedback!

**Closed by Glavin001** 2015-06-15 20:43 UTC

**Comment by frankhale** [comment] 2015-06-16 13:12
Thank you! Sorry for the duplicate.

**Comment by Glavin001** [comment] 2015-06-16 13:13
Not a problem. I hope this is something I can resolve soon. :smiley:

**Comment by frankhale** [comment] 2016-02-26 14:13
This is happening for me again on multiple machines. Atom can't tell when Atom-Beautify is finished installing it's updates so Atom's package update UI makes it look like the package never finishes installing. Hitting the check for updates button after some time will refresh Atom's UI and this package will have finished.
