### ISSUE TITLE
JS Chained methods never break regardless of "Break Chained Method" setting

### ISSUE THREAD

**Issue by ProustIdee** [Glavin001/atom-beautify#836] opened 2016-02-27 17:49 UTC
With Atom-Beautify 0.28.24.

`Input` code:

```
<html>
  <script>
    d3.csv("/data/test.csv", function (d) {
      svg.append('g')
      .selectAll('path');
    });
  </script>
</html>
```

Result of Beautifying:

```
<html>
  <script>
    d3.csv("/data/test.csv", function (d) {
      svg.append('g').selectAll('path');
    });
  </script>
</html>
```

It doesn't matter what I set "Javascript - Break chained methods" to. I'm using the JS Beautify engine.

I didn't have this problem until the last day or two. I assume Atom-Beautify was updated recently?

**Comment by Glavin001** [comment] 2016-02-27 21:11
Please follow the Issue template provided, it is required not a recommendation. For your convience, here it is again: https://github.com/Glavin001/atom-beautify/blob/master/ISSUE_TEMPLATE.md 
The most important part being the Gist containing your debugging information. That information would help me resolve many questions I will be asking without a tedious back and forth.

I await your debugging information. Thank you.

**Comment by ProustIdee** [comment] 2016-02-27 21:55
I uninstalled Atom-Beautify and reinstalled, I also deleted the Atom-beautify section from my config.cson file.

Here is the debug.md: https://gist.github.com/ProustIdee/d0eb29920a3addc00409

**Comment by Glavin001** [comment] 2016-02-27 22:52
The option you used is:

```
    "js_break_chained_methods": true
```

Which is language namespace `js`.

While the language namespace for your code is `html`, as the grammar detected is `HTML`.

So Atom Beautify filtered out the options only for `html` namespace.

I do not see the `break_chained_methods` in the list of supported `HTML` language options: https://github.com/Glavin001/atom-beautify/blob/master/src/languages/html.coffee#L28
Feel free to submit a Pull Request, however using the `.jsbeautifyrc` file can allow any option.

I'd recommend setting `break_chained_methods` for `html` namespace in your `.jsbeautifyrc` file.

Something like:

```json
{
  "html": { "break_chained_methods": true }
}
```

**Comment by ProustIdee** [comment] 2016-02-27 23:00
Thanks for the reply. Is there a reason this worked until recently?

The way that I understand it, I should have separate js files and call them from the html file, rather than writing script in the <script> </script> tags in the html file.

However, I didn't have any problems with this until recently, everything worked perfectly.

**Comment by Glavin001** [comment] 2016-02-27 23:06
So you had a single HTML file with JavaScript content and using the `js_break_chained_methods` option everything worked before as expected and now it does not? Strange. 
The only thing I could suggest is that maybe Pretty Diff (your currently selected beautifier) has been updated. /cc @prettydiff

**Comment by ProustIdee** [comment] 2016-02-27 23:22
Weird, is there was reason it was using Pretty Diff (is that the default)? This is what my Atom-Beautify Settings look like (I haven't touched it since I posted the debug.md). It doesn't even look like I can change the html beautifier?

![atom-beaufier](https://cloud.githubusercontent.com/assets/15386719/13376075/06268dde-dd7f-11e5-98a8-ba5e256a4386.png)

**Comment by ProustIdee** [comment] 2016-02-27 23:32
I'm not sure how you incorporate Pretty Diff into Atom-Beautify. They made some changes about 13 days ago, could you have picked these up recently?

https://github.com/prettydiff/prettydiff/search?utf8=%E2%9C%93&q=+methodchain

**Comment by Glavin001** [comment] 2016-02-27 23:38
Updates published to npm for dependencies, such as Pretty Diff or JS-Beautify, are not automatically applied to Atom Beautify in Atom, nor is Atom Beautify even shown as needing an update. However the dependency versions required for dependencies are very loose within Atom Beautify, such that by reinstalling Atom Beautify you can effectively update to the latest version of all the dependencies. For example, Pretty Diff: `"prettydiff": "^1.16.17",` at https://github.com/Glavin001/atom-beautify/blob/master/package.json#L97

So when you updated Atom Beautify, which has not happened in a while, you likely did update Pretty Diff and those changes made 13 days ago.

@prettydiff this may be an issue on your end then. Let me know if there's anything I can help with.

**Comment by prettydiff** [comment] 2016-02-28 12:37
Looking at this now.  When I run the sample code against the `methodchain` option used internally by Pretty Diff at http://prettydiff.com/ the output is as expected for the three supported values: `chain`, `indent`, `none`.  It appears to correct on the Pretty Diff side.

I am examining this operation in Atom now.

**Comment by prettydiff** [comment] 2016-02-28 12:50
I think I found the problem in Atom.  You can reproduce the problem if Pretty Diff is the beautifier for both HTML and JavaScript.  I think this problem is this following line where Pretty Diff is being passed a boolean for its `methodchain` option: https://github.com/Glavin001/atom-beautify/blob/3a6763a25c399eb07c641d8c3136f57649cd19e6/src/beautifiers/prettydiff.coffee#L34

I am verifying now and also looking to see when/why this was changed on the Pretty Diff side.

**Comment by prettydiff** [comment] 2016-02-28 13:01
Disregard the previous comment.  I appear to be handling boolean values for that option correctly for backwards compatibility.  That is not the problem.

The problem is that the language grammar is HTML.  When I isolate the JavaScript code and change the language grammar to JavaScript everything work as expected.  For some reason the option is not being passed through from HTML to JavaScript in Atom Beautify.  I am looking to where this gets dropped.

**Comment by prettydiff** [comment] 2016-02-28 13:13
I am not sure how to resolve this.  I think the error is the settings screen for Atom Beautify (though I have not confirmed this and dont know how).  You can set a value for a JavaScript option on that page, and once that option is set the value is cached for that given language grammar.  HTML, a different language grammar with a different set of options, sets and applies its options independently.  When the current language grammar is HTML you can change JavaScript options to no effect.  When you change the language grammar to JavaScript the change in effect is manifest.

I have confirmed that the option setting works correctly if the language grammar is JavaScript.  I have also confirmed that whatever setting was chosen for the given option is "locked in" once you change your grammar back to HTML.  So long as the grammar is HTML the only thing that is broken is the JavaScript language option on the settings screen.

**Comment by timothyerwin** [comment] 2017-01-03 06:45
I had the same problem...I had to change the file type in Atom to "JavaScript" as it was set to "Babel ES6 Javascript"

**Comment by prettydiff** [comment] 2017-10-10 16:49
This issue is likely resolved as the latest version of Pretty Diff recently landed in Atom Beautify.  If I am in error please reopen this issue.

**Closed by prettydiff** 2017-10-10 16:49 UTC
Labels: enhancement

**Comment by szeck87** [comment] 2017-10-10 16:57
@prettydiff the updates have been published to apm yet, so you won't see changes yet. Should be soon though

**Comment by prettydiff** [comment] 2017-10-10 17:42
@szeck87 I am aware.  Closing all these issues might be a bit premature for the users, but I still feel good about cleaning house and clearing out some of the backlog.  Excellent work on that pull request by the way!

**Comment by JeffML** [comment] 2018-03-02 17:25
Disabling  'Break chained methods' in Javascript settings didn't work for me.  I had to disable it in JSX settings.
