### ISSUE TITLE
Code duplication issues with JS beautification.

### ISSUE THREAD

**Issue by JamesCoyle** [Glavin001/atom-beautify#1391] opened 2016-12-02 17:10 UTC
# Description
When beautifying javascript files the file seems to be beautified for a second and then seems to revert back. Not sure why this is but it also leads to lines at the end of the file being repeated which can be annoying to fix. 

# Steps to Reproduce
No clue really. Seems to happen randomly when I beautify javascript files on save with any of the beautifiers for JS. This is the case both on my previous install and now again on a completely fresh OS and fresh install of Atom. 

# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/anonymous/d2b69fc5718f39d947943acb0c6bba83

**Comment by prettydiff** [comment] 2016-12-02 18:44
The beautifier used is Pretty Diff.  I put the code sample into http://prettydiff.com and didn't see any problems.  The two likely explanations are they I have simply glanced over the problems when reading the output or that the defect no longer exists in Pretty Diff as Atom Beautify is currently using an older version of Pretty Diff.

**Comment by JamesCoyle** [comment] 2016-12-02 18:53
It seems to happen with all three beautifiers so seems likely to be an issue with the beautify package itself?

**Comment by Glavin001** [comment] 2017-01-03 02:19
Sounds like a duplicate of #1213.

**Closed by Glavin001** 2017-01-03 02:19 UTC
Labels: bug
