### ISSUE TITLE
Could not find 'php-cs-fixer'. The program may not be installed. windows 10

### ISSUE THREAD

**Issue by Feefty** [Glavin001/atom-beautify#1052] opened 2016-07-06 23:06 UTC
### Description

I can run php and php-cs-fixer in my cmd

which php
`/c/xampp/php/php`

which php-cs-fixer
`/c/Users/Me/AppData/Roaming/Composer/vendor/bin/php-cs-fixer`

Here is my stacktrace

```
Error: Could not find 'php-cs-fixer'. The program may not be installed.
    at PHPCSFixer.module.exports.Beautifier.commandNotFoundError (file:///C:/Users/Me/.atom/packages/atom-beautify/src/beautifiers/beautifier.coffee:196:14)
    at file:///C:/Users/Me/.atom/packages/atom-beautify/src/beautifiers/php-cs-fixer.coffee:55:28
    at tryCatcher (C:\Users\Me\.atom\packages\atom-beautify\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\Me\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:504:31)
    at Promise._settlePromise (C:\Users\Me\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:561:18)
    at Promise._settlePromise0 (C:\Users\Me\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:606:10)
    at Promise._settlePromises (C:\Users\Me\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:685:18)
    at Promise._fulfill (C:\Users\Me\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:630:18)
    at PromiseArray._resolve (C:\Users\Me\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise_array.js:125:19)
    at PromiseArray._promiseFulfilled (C:\Users\Me\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise_array.js:143:14)
    at Promise._settlePromise (C:\Users\Me\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:566:26)
    at Promise._settlePromise0 (C:\Users\Me\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:606:10)
    at Promise._settlePromises (C:\Users\Me\.atom\packages\atom-beautify\node_modules\bluebird\js\release\promise.js:685:18)
    at Async._drainQueue (C:\Users\Me\.atom\packages\atom-beautify\node_modules\bluebird\js\release\async.js:138:16)
    at Async._drainQueues (C:\Users\Me\.atom\packages\atom-beautify\node_modules\bluebird\js\release\async.js:148:10)
    at Async.drainQueues (C:\Users\Me\.atom\packages\atom-beautify\node_modules\bluebird\js\release\async.js:17:14)
```

**Comment by Glavin001** [comment] 2016-07-06 23:25
Please follow the issue template provided. More specifically, adding a link to the required `debug.md` Gist which includes debugging information that answers our most commonly asked questions: https://github.com/Glavin001/atom-beautify/blob/master/ISSUE_TEMPLATE.md#how-to-create-debugmd-gist
Thank you.

**Comment by Feefty** [comment] 2016-07-07 10:12
well the command `Atom Beautify: Help Debug Editor` is not copying the results

**Comment by Glavin001** [comment] 2016-07-07 15:18
> the command `Atom Beautify: Help Debug Editor` is not copying the results

This is a big issue. Is there any errors shown in the Developer Console of Atom?

**Comment by UziTech** [comment] 2016-07-07 16:30
could be the same issue I was having #1054 

check to make sure your `PATH` system variable is all caps. Mine was set to `Path` probably by a windows update.

**Comment by myUsernamesTaken** [comment] 2016-08-04 07:06
Any news on this?

**Comment by gqferreira** [comment] 2016-11-29 22:54
I had the same problem. Any solution?

I has the php-cs-fixer package installed.

> See https://github.com/FriendsOfPHP/PHP-CS-Fixer for program installation instructions.
> Your program is properly installed if running 'which php-cs-fixer' in your Terminal returns an absolute path to the executable. If this does not work then you have not installed the program correctly and so Atom Beautify will not find the program. Atom Beautify requires that the program be found in your PATH environment variable. 
> Note that this is not an Atom Beautify issue if beautification does not work and the above command also does not work: this is expected behaviour, since you have not properly installed your program. Please properly setup the program and search through existing Atom Beautify issues before creating a new issue. See https://github.com/Glavin001/atom-beautify/search?q=php-cs-fixer&type=Issues for related Issues and https://github.com/Glavin001/atom-beautify/tree/master/docs for documentation. If you are still unable to resolve this issue on your own then please create a new issue and ask for help.

```
Error: Could not find 'php-cs-fixer'. The program may not be installed.
    at PHPCSFixer.module.exports.Beautifier.commandNotFoundError (/Users/Gustavo/.atom/packages/atom-beautify/src/beautifiers/beautifier.coffee:204:14)
    at /Users/Gustavo/.atom/packages/atom-beautify/src/beautifiers/beautifier.coffee:304:22
    at tryCatcher (/Users/Gustavo/.atom/packages/atom-beautify/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/Gustavo/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Users/Gustavo/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Users/Gustavo/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/Gustavo/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:687:18)
    at Async._drainQueue (/Users/Gustavo/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/Users/Gustavo/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:148:10)
    at Async.drainQueues (/Users/Gustavo/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:17:14)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by myUsernamesTaken** [comment] 2016-11-30 05:50
Solved it by now using Sublime Text. Easy fix. :\

**Comment by Wockito** [comment] 2016-12-01 07:30
What was the fix  ?

**Comment by Glavin001** [comment] 2017-01-02 16:28
Command `Atom Beautify: Help Debug Editor` has been improved. If you are experiencing this issue it is because your environment is not correctly setup. We can help with a provided `debug.md` Gist generated from `Atom Beautify: Help Debug Editor`.

**Comment by Glavin001** [comment] 2017-01-02 16:29
I'm closing this as a duplicate of the many existing Issues: https://github.com/Glavin001/atom-beautify/search?q=Could+not+find+%27php-cs-fixer%27.+The+program+may+not+be+installed.&state=closed&type=Issues&utf8=%E2%9C%93

**Closed by Glavin001** 2017-01-02 16:29 UTC
Labels: question

**Comment by Glavin001** [comment] 2017-06-04 18:25
I really want to focus on improving the installation experience for users. I have created a new Issue, #1687, to target this problem. Please provide your feedback! Thanks in advance.
