### ISSUE TITLE
atom-beautify doesn't beauty of a html section <script>

### ISSUE THREAD

**Issue by oshliaer** [Glavin001/atom-beautify#835] opened 2016-02-27 06:40 UTC
### Description

The results of beautification are not what I expect.

### Expected Results

The beautified code should have looked like:

```html
<script>
    var m;
</script>
```

### Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

### Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/anonymous/7a54ebba49f8d62e6563

# Checklist

- [x] I have tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Searched for existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues 
so I know this is not a duplicate issue
- [x] Generated debugging information and added link for `debug.md` Gist to this issue

**Comment by prettydiff** [comment] 2016-02-27 06:43
I can reproduce the defect.  I am working it.

**Comment by oshliaer** [comment] 2016-02-27 08:21
@prettydiff , I can work, too. But I have to begin. Is there the fast FAQ about `Atom` &  `atom-beautify` & `bug-fix`?

**Comment by prettydiff** [comment] 2016-02-27 12:23
@oshliaer The problem will be in https://github.com/prettydiff/prettydiff/blob/master/lib/markuppretty.js

Clone prettydiff and look at lib/markuppretty.js.  The problem is most likely in the `markuppretty__tokenize_content` function in the condition where `ext === true`.  I am guessing that the markup parser is attempting to parse script code as a segment of content (it gets passed to the JavaScript parser later) but it isn't finding the closing script tag correctly.  There are some conventions in place to prevent early termination in the case of string literals, regular expressions, comments, and other areas of JavaScript that may contain a closing HTML script tag in a passively ignored way.

**Comment by prettydiff** [comment] 2016-02-27 13:11
@oshliaer If you are working this just let me know if you have any questions.  I think I may have found the problem as I had to jump into the library for the issue I am currently working https://github.com/prettydiff/prettydiff/issues/275

I don't want to step on your feet.  Since you have expressed interest I don't want to deprive you of the chance to contribute.

Some additional information is that the unit tests are run with `npm install` in the project directory.

**Comment by oshliaer** [comment] 2016-02-27 13:26
Ok. @prettydiff , I'll try today soon.

**Comment by prettydiff** [comment] 2016-02-27 13:41
No hurry.  I have a huge backlog of tasks that have stacked up over the past week and I will be in and out a bunch today trying to tackle some family responsibilities.

**Comment by prettydiff** [comment] 2016-03-01 01:05
Published resolution to v1.16.23.

**Closed** 2016-03-01 01:06 UTC
Labels: third-party bug
