### ISSUE TITLE
Could not find 'docker'. The program may not be installed.

### ISSUE THREAD

**Issue by mukeshbasira** [Glavin001/atom-beautify#2178] opened 2018-07-07 21:30 UTC
# Description

The results of beautification are not what I expect.

# Input Before Beautification

I am using atom for c++. As this is my first time on Atom (used xcode ). 

# Actual Output

See docker installation instructions at https://github.com/Glavin001/atom-beautify#beautifiers or go to https://www.docker.com/get-docker
You can configure Atom Beautify with the absolute path to 'docker' by setting 'Executable - Docker - Path' in the Atom Beautify package settings.
Your program is properly installed if running 'which docker' in your Terminal returns an absolute path to the executable.

Error: Could not find 'docker'. The program may not be installed.
    at Function.Executable.commandNotFoundError (/Users/mukeshbasira/.atom/packages/atom-beautify/src/beautifiers/executable.coffee:277:10)
    at Executable.commandNotFoundError (/Users/mukeshbasira/.atom/packages/atom-beautify/src/beautifiers/executable.coffee:269:18)
    at /Users/mukeshbasira/.atom/packages/atom-beautify/src/beautifiers/executable.coffee:197:22
    at tryCatcher (/Users/mukeshbasira/.atom/packages/atom-beautify/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/mukeshbasira/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/mukeshbasira/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/mukeshbasira/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/mukeshbasira/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/Users/mukeshbasira/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/mukeshbasira/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:143:10)
    at Async.drainQueues (/Users/mukeshbasira/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:17:14)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:109:7)

# Checklist

I have:
- [ ] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [ ] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [ ] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
Yes this is a duplicate issue . Previous issues are not so much informative for the user to resolve the error .

**Comment by szeck87** [comment] 2018-07-07 21:37
Duplicate of #2145.

**Closed by szeck87** 2018-07-07 21:37 UTC
Labels: waiting-for-user-information
