### ISSUE TITLE
Stylus

### ISSUE THREAD

**Issue by malyarevich** [Glavin001/atom-beautify#1558] opened 2017-03-18 17:18 UTC
Add stylus 
It same grama of less or sass

**Comment by prettydiff** [comment] 2017-03-18 23:44
Would you mind testing some stylus code out at http://prettydiff.com/?m=beautify&lang=less and let me know if that tool works?  It is already integrated into Atom Beautify, and so if this works then this could be a very simple enhancement.

**Comment by malyarevich** [comment] 2017-03-19 16:50
It does not work. Bad idea...
[main.txt](https://github.com/Glavin001/atom-beautify/files/853369/main.txt)

**Comment by prettydiff** [comment] 2017-03-20 02:34
Yeah, Pretty Diff will not support that.  It looks like SASS syntax opposed to LESS or SCSS.

**Comment by Glavin001** [comment] 2017-04-09 21:43
Closing this Stylus feature request as a duplicate of https://github.com/Glavin001/atom-beautify/issues/318

**Closed by Glavin001** 2017-04-09 21:43 UTC
Labels: add-language
