### ISSUE TITLE
Beautify selection as another language

### ISSUE THREAD

**Issue by oschwald** [Glavin001/atom-beautify#1202] opened 2016-09-17 18:49 UTC
As far as I can tell, there is no way to currently beautify a selection of code in a specific language that is different than the file's language. My primary use case for this feature would be beautifying SQL that is embedded in string literals, although I imagine it could also be useful for beautifying other embedded code or markup.

**Comment by prettydiff** [comment] 2016-09-18 03:30
Could you also provide a tiny code sample?  It will give us something to test against.

**Comment by oschwald** [comment] 2016-09-18 14:43
Sure, here are two made up examples where I'd like to be able to beautify the SQL within the other code:

```perl
my $sql = <<'SQL';
SELECT fname, lname 
FROM people 
WHERE id >= ? AND id < ?
SQL

my $sth = $dbh->prepare($sql);
$sth->execute(1, 10);
while (my @row = $sth->fetchrow_array) {
   print "fname: $row[0]  lname: $row[1]\n";
}
```

```go
package main

import (
	"database/sql"
	"log"

	_ "github.com/go-sql-driver/mysql"
)

func main() {
	var (
		id   int
		name string
	)

	db, err := sql.Open("mysql",
		"user:password@tcp(127.0.0.1:3306)/hello")
	if err != nil {
		log.Fatal(err)
	}
	defer db.Close()

	sql := `
SELECT id,
       name
FROM "user"
WHERE name='Bob'
AND   date='2014-01-10'
`

	rows, err := db.Query(sql)

	if err != nil {
		log.Fatal(err)
	}
	defer rows.Close()
	for rows.Next() {
		err := rows.Scan(&id, &name)
		if err != nil {
			log.Fatal(err)
		}
		log.Println(id, name)
	}
	err = rows.Err()
	if err != nil {
		log.Fatal(err)
	}
}
```

**Comment by prettydiff** [comment] 2016-09-19 13:38
Perhaps a right click option *Beautify As...* that open a list of grammars.

**Comment by Glavin001** [comment] 2017-05-06 18:26
Closing as duplicate of https://github.com/Glavin001/atom-beautify/issues/27

**Closed by Glavin001** 2017-05-06 18:26 UTC
Labels: enhancement
