### ISSUE TITLE
in .vue file style lang="scss"Error: Source sample is missing

### ISSUE THREAD

**Issue by MAYDAY1993** [Glavin001/atom-beautify#1182] opened 2016-09-08 09:09 UTC
I new a vue file and type 'template'->tab  
![image](https://cloud.githubusercontent.com/assets/14831051/18343563/727bde76-75e6-11e6-989a-66bded645cea.png)
because I use scss  ,so I tried to change like this:
![image](https://cloud.githubusercontent.com/assets/14831051/18343598/9c3454b4-75e6-11e6-9d7b-68a4333dbd4b.png)
ok  changed it .
and I save the file use command+s,it turns out to be:
![image](https://cloud.githubusercontent.com/assets/14831051/18343621/bdc0c478-75e6-11e6-9393-33d1b467e36b.png)
but the page show:
![image](https://cloud.githubusercontent.com/assets/14831051/18343662/e9793028-75e6-11e6-89a5-e176b1b1acf1.png)
so  what's wrong?

**Comment by prettydiff** [comment] 2016-09-08 10:47
Pretty Diff error.  I am working on a resolution.

**Comment by prettydiff** [comment] 2016-09-08 10:57
I am having trouble reproducing would you mind producing the debug.md file for me?  https://github.com/Glavin001/atom-beautify/blob/master/docs/troubleshooting.md

**Comment by prettydiff** [comment] 2016-10-04 13:32
The problem is in Pretty Diff.  The last published version of Pretty Diff to NPM is 1.16.37.  The defect has since been fixed in Pretty Diff, but Pretty Diff no longer publishes to NPM.  I am working on an alternate distribution method right now.

**Comment by Glavin001** [comment] 2017-01-01 05:02
Closing as Pretty Diff bug.

**Closed by Glavin001** 2017-01-01 05:02 UTC
Labels: third-party bug

**Comment by derwaldgeist** [comment] 2017-01-03 21:49
Any updates on a workaround? This bug is quite annoying. :-)
It always happens if a scss file is empty.

**Comment by prettydiff** [comment] 2017-01-04 23:55
@derwaldgeist You could clone down Pretty Diff from github and then copy it over the Pretty Diff used by Atom Beautify.

`git clone git@github.com:prettydiff/prettydiff.git`

To look for the Pretty Diff that comes with Atom Beautify try looking in:

`.atom/packages/atom-beautify/node_modules`

If you are on Windows the .atom directory is typically located in %appdata%.

**Comment by derwaldgeist** [comment] 2017-01-08 09:59
Thanks for the info! Would prefer a solution without patching the package, though :-)

**Comment by prettydiff** [comment] 2017-01-08 11:45
@derwaldgeist Here is the status and current blocker of my solution to this distribution problem: https://github.com/prettydiff/biddle/issues/25#issuecomment-270567516

I was testing this in production with Pretty Diff and only discovered the issue after auditing a republish.  The solution is close and once I have solved the current problem I will resume testing in production and eventually recommend this to Atom Beautify.

**Comment by derwaldgeist** [comment] 2017-01-08 20:57
Thanks for your fast reply and the additional insights! Highly appreciated.

**Comment by prettydiff** [comment] 2017-01-20 04:16
Keeping everybody informed I have fixed biddle.  Check it out now - https://github.com/prettydiff/biddle

I will republish Pretty Diff using biddle in production tomorrow.  I am not ready to give it to Atom Beautify just yet though.  I actually need users to play around with this thing for a bit so that I can get a sense of where the pain points are and just how bad it works for fails for other people.  I wrote a getting started document at https://github.com/prettydiff/biddle/blob/master/documentation/gettingstarted.md

The documentation might be easier to read from the command line though as I included a markdown to CLI parser in biddle.  The number at the end defines the word wrap limit:

    node biddle markdown documentation/gettingstarted.md 80
