### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by jerone** [Glavin001/atom-beautify#188] opened 2015-01-18 14:43 UTC
Bug report from Atom:

> atom.workspaceView is no longer available.
> In most cases you will not need the view. See the Workspace docs for
> alternatives: https://atom.io/docs/api/latest/Workspace.
> If you do need the view, please use `atom.views.getView(atom.workspace)`,
> which returns an HTMLElement.
> ```
> Atom.Object.defineProperty.get (c:\Users\xxx\AppData\Local\atom\app-0.174.0\resources\app\src\atom.js:55:11)
> LoadingView.module.exports.LoadingView.show (c:\Users\xxx\.atom\packages\atom-beautify\lib\loading-view.coffee:38:11)
> ```

**Comment by Glavin001** [comment] 2015-03-16 05:22
Duplicate of #191

**Closed by Glavin001** 2015-03-16 05:22 UTC
Labels: high priority
