### ISSUE TITLE
Any plan to support Shell script?

### ISSUE THREAD

**Issue by wangx1ng** [Glavin001/atom-beautify#654] opened 2015-11-11 10:03 UTC

**Comment by ianremsen** [comment] 2015-11-13 01:36
+1, it doesn't seem to be a huge burden, definitely sub-C levels of work required.

**Comment by Glavin001** [comment] 2016-09-25 21:59
Sounds like a duplicate of #451.
FYI, waiting on Pull Request: https://github.com/Glavin001/atom-beautify/pull/1220

**Closed by Glavin001** 2016-09-25 21:59 UTC
Labels: add-language
