### ISSUE TITLE
stop throwing erros for unsupported languages

### ISSUE THREAD

**Issue by luisrudge** [Glavin001/atom-beautify#207] opened 2015-02-07 14:24 UTC
It's annoying to have an error for every time I save a document with an unsupported language. Maybe you should just send a toast notification with a button to never read that again

**Comment by Glavin001** [comment] 2015-02-09 01:43
Please see https://github.com/Glavin001/atom-beautify#package-options and use `muteUnsupportedLanguageErrors`.

Duplicate of #105

**Closed by Glavin001** 2015-02-09 01:43 UTC

**Comment by luisrudge** [comment] 2015-02-09 01:59
Wow. Sorry! I missed the configuration option! Thanks!
