### ISSUE TITLE
It's better not show grammar error message

### ISSUE THREAD

**Issue by Tedko** [Glavin001/atom-beautify#258] opened 2015-03-29 21:06 UTC
![2015-03-29 4 05 45](https://cloud.githubusercontent.com/assets/6687437/6887712/7d74507e-d62d-11e4-9a12-6f30ccb63afc.png)

**Comment by Glavin001** [comment] 2015-03-29 23:27
There are options available for muting error messages: https://github.com/Glavin001/atom-beautify#package-options

Duplicate of #105

**Closed by Glavin001** 2015-03-29 23:27 UTC
Labels: duplicate, question
