### ISSUE TITLE
it hangs during a save command

### ISSUE THREAD

**Issue by mk6488** [Glavin001/atom-beautify#1806] opened 2017-08-11 10:44 UTC
# Description
Since the latest Atom update (1.19.0), atom-beautify hangs during the save command (cmd-s). It's as if it's generating an endless "save-loop" and renders any further input/command ineffective. Any ideas what is happening?

**Comment by runartrollet** [comment] 2017-08-11 16:13
Something similar is happening for me too. It also keeps deleting my content, (got vcs of course, so no real loss of data), and my whole editor turns terribly slow. I have so far only seen the issue while editing `.html`-files, while `pretty diff` is used as the Beautifier. As a workaround, I set it to `JS Beautify`, and so far no more issues. 

So for me, this issue seems related to `pretty diff`

**Comment by szeck87** [comment] 2017-08-11 16:46
The endless save loop is caused by https://github.com/Glavin001/atom-beautify/issues/1721. A temporary workaround is to disable beautify on save and do it via the menu command. Fix should be ready soon.

**Comment by Glavin001** [comment] 2017-08-12 01:25
This is caused by https://github.com/Glavin001/atom-beautify/issues/1721 . I will close this as a duplicate.

Workaround: disable "Beautify On Save" until fixed.

Upcoming fix: https://github.com/Glavin001/atom-beautify/pull/1804

**Comment by Glavin001** [comment] 2017-08-12 01:25
Published to v0.30.5

**Closed by Glavin001** 2017-08-12 01:25 UTC
