### ISSUE TITLE
Cannot beautify JSON file

### ISSUE THREAD

**Issue by smlombardi** [Glavin001/atom-beautify#1006] opened 2016-06-07 13:17 UTC
Updated to 1.9b1, and now when I run "beautify" on a JSON file, I get this error:

```
Cannot read property 'getView' of undefined
Hide Stack Trace
TypeError: Cannot read property 'getView' of undefined
    at getScrollTop (/Users/stevelombardi/.atom/packages/atom-beautify/src/beautify.coffee:31:29)
    at beautifyCompleted (/Users/stevelombardi/.atom/packages/atom-beautify/src/beautify.coffee:108:27)
    at tryCatcher (/Users/stevelombardi/.atom/packages/atom-beautify/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/stevelombardi/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:502:31)
    at Promise._settlePromise (/Users/stevelombardi/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:559:18)
    at Promise._settlePromise0 (/Users/stevelombardi/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:604:10)
    at Promise._settlePromises (/Users/stevelombardi/.atom/packages/atom-beautify/node_modules/bluebird/js/release/promise.js:683:18)
    at Async._drainQueue (/Users/stevelombardi/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/Users/stevelombardi/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:148:10)
    at Async.drainQueues (/Users/stevelombardi/.atom/packages/atom-beautify/node_modules/bluebird/js/release/async.js:17:14)
```

**Comment by Glavin001** [comment] 2016-06-08 01:00
Duplicate of https://github.com/Glavin001/atom-beautify/issues/979

**Closed by Glavin001** 2016-06-08 01:00 UTC
