### ISSUE TITLE
JSX in an array does not format correctly.

### ISSUE THREAD

**Issue by ghost** [Glavin001/atom-beautify#1057] opened 2016-07-10 19:00 UTC
### Description

The results of beautification are not what I expect.
Code:

```
import React, {Component} from 'react';
import {Link} from 'react-router';
import {connect} from 'react-redux';

class Header extends Component {
    renderLinks() {
        if (this.props.authenticated) {
            return (
                <li className="nav-item">
                    <Link className="nav-link" to="/signout">SignOut</Link>
                </li>
            )

        } else {
            return [ < li key = "signin" className = "nav-item" > <Link className="nav-link" to="/signin">Sign in</Link> < /li>,
            <li key= "signout" className="nav-item"><Link className="nav-link" to="/signup ">Sign Up</Link></li>]

            }
        }
    }
    render() {
        return (
            <nav className="navbar navbar-light">
                <Link to="/" className="navbar-brand" href="">
                    <h3>
                        <strong>
                            <i>T-STORE</i>
                        </strong>
                    </h3>
                </Link>
                <ul className="nav navbar-nav">
                    {this.renderLinks()}
                </ul >
            </nav>
        )
    }
}

function mapStateToProps(state) {
    return {authenticated: state.auth.authenticated}
}

export default connect(mapStateToProps)(Header);

```
### Expected Results

The beautified code should have looked like:

```
import React, {Component} from 'react';
import {Link} from 'react-router';
import {connect} from 'react-redux';

class Header extends Component {
    renderLinks() {
        if (this.props.authenticated) {
            return (
                <li className="nav-item">
                    <Link className="nav-link" to="/signout">SignOut</Link>
                </li>
            )

        } else {
            return [ 
                <li key = "signin" className = "nav-item" > 
                     <Link className="nav-link" to="/signin">Sign in</Link>
               </li>,
               <li key= "signout" className="nav-item">
                     <Link className="nav-link" to="/signup">Sign Up</Link>
               </li>
             ]
            }
        }
    }
    render() {
        return (
            <nav className="navbar navbar-light">
                <Link to="/" className="navbar-brand" href="">
                    <h3>
                        <strong>
                            <i>T-STORE</i>
                        </strong>
                    </h3>
                </Link>
                <ul className="nav navbar-nav">
                    {this.renderLinks()}
                </ul >
            </nav>
        )
    }
}

function mapStateToProps(state) {
    return {authenticated: state.auth.authenticated}
}

export default connect(mapStateToProps)(Header);

```
### Steps to Reproduce
1. Add code to Atom editor
2. Save code (As we have setting beautify on save)
3. This beautified code does not look right!
### Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/sujandthakare/dddd2438b5261b176c2d301058cf17d4

**Comment by prettydiff** [comment] 2016-07-10 23:07
This is a Pretty Diff defect that I can reproduce.  I am working it now.

**Comment by prettydiff** [comment] 2016-07-10 23:57
The defect is at https://github.com/prettydiff/prettydiff/blob/master/lib/jspretty.js#L2084

    if (token[d] === "return" || types[d] === "operator" || token[d] === "(") {

should become

    if (token[d] === "return" || types[d] === "operator" || types[d] === "start" || types[d] === "separator") {

This will open up JSX syntax to wider interpretation inside the parser.  This opens up some beautification regression that I am looking into now.  Even with this code fix the above code will still fail because of line:

    < li key = "signin" className = "nav-item" >

Pretty Diff considers white space between the opening delimiter and tag name to be invalid XML and instead interprets the `<` as a JavaScript less than operator.

**Comment by sujandthakare** [comment] 2016-07-11 05:55
I also encountered a weird issue, if you type JSX tag and hit save without completing the tag sometimes it adds text at the end of the file. I am trying to reproduce exact case .

**Comment by derwaldgeist** [comment] 2017-01-09 21:50
+1

I am trying to get AtomBeautify work for JSX for some days now. Unfortunately, these kind of bugs prevent me from using it for JSX :-/ Yet, I am addicted to this package, I don't have any clue on how to proceed now.

**Comment by prettydiff** [comment] 2017-10-10 16:35
The latest version of Pretty Diff recently landed in Atom Beautify which should resolve this issue.  If the defect remains please reopen this issue.

**Closed by prettydiff** 2017-10-10 16:35 UTC
Labels: third-party-bug
