### ISSUE TITLE
TextBuffer.on is deprecated.

### ISSUE THREAD

**Issue by fuczak** [Glavin001/atom-beautify#310] opened 2015-05-04 16:33 UTC
Use TextBuffer::onWillSave instead. A TextBuffer instance is no longer provided as a callback argument.
```
TextBuffer.on (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1179:16)
Object.subscribeWith (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/emissary/lib/subscriber.js:28:32)
Object.subscribe (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/emissary/lib/subscriber.js:63:21)
<unknown> (/Users/damianprus/.atom/packages/atom-beautify/lib/beautify.coffee:297:18)
```

**Comment by Glavin001** [comment] 2015-05-05 14:11
Duplicate of #289

**Closed by Glavin001** 2015-05-05 14:11 UTC

**Comment by Glavin001** [comment] 2015-05-05 17:50
Published to v0.26.5
