### ISSUE TITLE
SCSS PrettyDiff adds extra space in front of '@' statements

### ISSUE THREAD

**Issue by jhulbert-eb** [Glavin001/atom-beautify#1407] opened 2016-12-09 15:08 UTC
# Description

When running PrettyDiff on .scss files via Atom Beautify, an extra space is added at the beginning of the first `@` statement in a block.

# Input Before Beautification

This is what the code looked like before:

```
@mixin block-size( $size: $global-block-context, $context: $global-block-context ) {
  @if $size == $context {
    width: 100%;
  }
  @else {
    width: percentage($size / $context);
  }
}
```

# Expected Output

The beautified code should have looked like this:

```
@mixin block-size( $size: $global-block-context, $context: $global-block-context ) {
  @if $size == $context {
    width: 100%;
  }
  @else {
    width: percentage($size / $context);
  }
}
```

# Actual Output

The beautified code actually looked like this:

```
@mixin block-size( $size: $global-block-context, $context: $global-block-context ) {
   @if $size == $context{ /// <-- Extra space added at beginning of this line
    width: 100%;
  }
  @else {
    width: percentage($size / $context);
  }
}
```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Debug

Here is a link to the `debug.md` Gist: <INSERT GIST HERE>

# Checklist

I have:
- [x] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [x] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [ ] Generated debugging information and added link for `debug.md` Gist to this issue

**Comment by prettydiff** [comment] 2016-12-09 17:35
I am having trouble reproducing this in the latest version of Pretty Diff, so the error could have been resolved since last published to NPM.  I did notice that `@if` and `@else` are both treated as selectors that can be sorted, which is bad.  For clarity the `@else` statement should be on the prior line following the closing brace: `} @else {`

**Comment by Glavin001** [comment] 2017-01-03 02:48
Please follow the [issue template](https://github.com/Glavin001/atom-beautify/blob/master/ISSUE_TEMPLATE.md) provided. More specifically, [adding a link to the required `debug.md` Gist](https://github.com/Glavin001/atom-beautify/blob/master/docs/troubleshooting.md#how-to-create-debugmd-gist) which includes debugging information that answers our most commonly asked questions.
Thank you.

**Closed by Glavin001** 2017-01-03 02:48 UTC
