### ISSUE TITLE
<i> Tag Autoclosing itself

### ISSUE THREAD

**Issue by Ethaan** [Glavin001/atom-beautify#435] opened 2015-06-30 05:07 UTC
When i try to beautify my `html` markup the `<i>` tag is auto closing itself, causing the 

`only certain elements like HG BR can auto close itself`

I see that elements like `<i>` are unformatted on the **HTML-Unformatted Field** on the *\* > settings.**

Is there a way to avoid beatify auto close the `<i>` tag

**Comment by Glavin001** [comment] 2015-06-30 09:55
> only certain elements like HG BR can auto close itself

Is this an error message that pops up? I am not sure where this is from.

I would assume that `HTML - Unformatted` option would do this. See https://github.com/Glavin001/atom-beautify/blob/master/docs/options.md#html---unformatted

However, if that is not the case then you should create an issue asking the team at JS Beautify about this: https://github.com/beautify-web/js-beautify
JS Beautify is what handles HTML, and Pretty Diff is what handles most other languages in Atom Beautify.

- https://github.com/beautify-web/js-beautify
- https://github.com/prettydiff/prettydiff/

Let me know what they say. Reference this issue in your new issue over on their repository, so any users also having this issue on Atom Beautify can see the link to the next issue to follow it's progress. Thanks!

**Comment by prettydiff** [comment] 2015-07-08 19:48
> only certain elements like HG BR can auto close itself

That must be something generated from software like @Glavin001 suggests. Any tag can self-close, even in HTML, and still be perfectly valid unless such tags are required to contain text or a child element, which the deprecated `i` element is not. There are certain tags that must not self-close in order to maintain compatibility with older versions of IE even though these tags do not require any child nodes, specifically:

* div
* span
* script

More importantly is that I pushed this feature behind option [tagmerge](http://prettydiff.com/documentation.xhtml#tagmerge) in v1.12.11 so it should no longer be a problem of default settings.

**Comment by prettydiff** [comment] 2017-10-10 16:51
Closing this issue as it is old and not likely a current problem.  If the problem is reproducible against the latest Atom Beautify please reopen this issue.

**Closed by prettydiff** 2017-10-10 16:51 UTC
Labels: question, third-party-bug
