### ISSUE TITLE
[Feature Request] - support for "Solidity" language and extension ".sol"

### ISSUE THREAD

**Issue by jinjideqiangwei** [Glavin001/atom-beautify#1552] opened 2017-03-13 10:24 UTC
# Description

Atom Beautify could not determine a supported beautifier to handle this file with grammar "Solidity" and extension "sol".

**Comment by prettydiff** [comment] 2017-03-14 10:01
Closing as a duplicate of #727

**Closed by prettydiff** 2017-03-14 10:01 UTC
Labels: add-language, duplicate
