### ISSUE TITLE
Atom-beautify causes chaotic behaviour and empties files on save (.html)

### ISSUE THREAD

**Issue by DmitryGrechko** [Glavin001/atom-beautify#1801] opened 2017-08-08 21:14 UTC
# Description

After updating to 1.19 Atom starts behaving unexpected after saving html files. It doesn't add/delete anything and redo command is not working. Then, if I close the file and open again the file appears empty. Disabling atom-beautify fixed the problem.

# Steps to Reproduce

1. Open html file
2. Save file 
3. Close file
4. Open again

# Debug

Disable atom-beautify

# Checklist

I have:
- [x] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [x] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [ ] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by colinhemphill** [comment] 2017-08-08 21:32
This started happening after I updated Atom as well. It seems to be on multiple file types, not just HTML. I noticed it while working in .js files.

**Comment by TheophanyFR** [comment] 2017-08-09 08:31
Same bug here, started happening after Atom updated to 1.19.0. I confirm it's at least on HTML and CSS files.

**Comment by Guillaume-Docquier** [comment] 2017-08-09 16:53
I'm having this issue as well with .js files. 

Moreover, when I press save, it seems like the beautifier runs non stop, taking 100% CPU. When I close atom to stop it and start it back, the file is empty. 

Disabling atom-beautify fixed the problem.

**Comment by ms223iu** [comment] 2017-08-09 22:14
Confirming issue. Just spent half an hour figuring out which plugin caused this behaviour. Cheers!

**Comment by Rmartinez532** [comment] 2017-08-10 05:00
Same issue here, been having the issue going for 2 days. Only happened with JS files tho. Disabled each plugin installed one by one until issue was fixed. Disable atom-beautify and now all works perfectly again.

**Comment by InvalidC** [comment] 2017-08-10 12:32
I have the same issue as well.... Although if you go in and disable the beautify on save for the language you are currently working with it will no longer have the random issues.

**Comment by scmccoy** [comment] 2017-08-10 12:56
Same after updating to Atom 1.19.0 
Causes webpack dev server to recompile in constant loop, on save of .js file it wipes out all content.

**Comment by szeck87** [comment] 2017-08-10 13:04
Ultimately caused by https://github.com/Glavin001/atom-beautify/issues/1721. Try disabling beautify on save  as that is where the issue lies. Manual beautify should not cause these problems.

**Comment by derwaldgeist** [comment] 2017-08-11 21:00
Same problem here. Another weird phenomenon: If I try to save a .json file with beautify on save enabled, the cursor wanders around backwords from token to token.

**Comment by Glavin001** [comment] 2017-08-12 01:12
This is caused by https://github.com/Glavin001/atom-beautify/issues/1721 . I will close this as a duplicate.

Workaround: disable "Beautify On Save" until fixed.

Upcoming fix: https://github.com/Glavin001/atom-beautify/pull/1804

**Closed by Glavin001** 2017-08-12 01:12 UTC
Labels: deprecated-atom-api, duplicate, high priority

**Comment by Glavin001** [comment] 2017-08-12 01:25
Published to v0.30.5
