### ISSUE TITLE
"Failed to activate the atom-beautify package", cannot find emissary

### ISSUE THREAD

**Issue by evjan** [Glavin001/atom-beautify#618] opened 2015-10-23 01:09 UTC
I just got this one in Atom 1.1.0-beta1

![screen shot 2015-10-23 at 12 07 14 pm](https://cloud.githubusercontent.com/assets/18362/10682242/c847ccc6-797e-11e5-9aa6-66da5c1854a7.png)

**Comment by leetal** [comment] 2015-10-23 06:15
+1. Running Windows 10

**Comment by m1ga** [comment] 2015-10-25 15:34
duplicate of https://github.com/Glavin001/atom-beautify/issues/428 https://github.com/Glavin001/atom-beautify/issues/605

**Comment by dsifford** [comment] 2015-10-26 01:04
+1 Windows 10 Preview, fast build

**Closed** 2015-10-26 02:42 UTC
Labels: duplicate

**Comment by Glavin001** [comment] 2015-10-26 02:58
Published fix to v0.28.15

Thank you everyone for your patience.

**Comment by seronal** [comment] 2015-10-27 18:08
I have v0.28.15 but I am still getting an error message with a link to this issue.

**Atom Version**: 1.0.19
**System**: Mac OS X 10.11.1
**Thrown From**: [atom-beautify](https://github.com/Glavin001/atom-beautify) package, v0.28.15


### Stack Trace

Failed to activate the atom-beautify package

```
At Cannot find module 'event-kit'

Error: Cannot find module 'event-kit'
  at Module._resolveFilename (module.js:334:15)
  at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
  at Function.Module._load (module.js:284:25)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Object.<anonymous> (/Users/Serdar/.atom/packages/atom-beautify/src/beautify.coffee:7:25)
  at Object.<anonymous> (/Users/Serdar/.atom/packages/atom-beautify/src/beautify.coffee:2:2)
  at Module._compile (module.js:428:26)
  at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:169:21)
  at Module.load (module.js:353:32)
  at Function.Module._load (module.js:308:12)
  at Module.require (module.js:363:17)
  at require (module.js:382:17)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:761:34)
  at Package.module.exports.Package.activateConfig (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:263:14)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:241:14)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:838:25
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:226:20)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:184:20)

```

### Commands

```
     -0:29.3.0 core:copy (atom-text-editor.editor.is-focused)
     -0:24.3.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -0:23.7.0 core:paste (atom-text-editor.editor.is-focused)
     -0:02.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "tool-bar-main",
      "save-session"
    ],
    "themes": [
      "one-dark-ui",
      "outlander-syntax"
    ]
  },
  "atom-beautify": {
    "analytics": false,
    "beautifyEntireFileOnSave": false,
    "java_configPath": "/Users/Serdar/Development/misc/google-play-crawler/uncrustify.cfg",
    "js_end_with_newline": true,
    "js_brace_style": "none"
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.3
angularjs-styleguide-snippets, v0.7.2
atom-beautify, v0.28.15
atom-jasmine, v0.6.0
atom-ternjs, v0.8.4
color-picker, v2.0.13
file-icons, v1.6.11
language-lua, v0.9.4
linter, v1.9.1
linter-jscs, v3.1.2
linter-jshint, v1.2.1
minimap, v4.15.0
outlander-syntax, v1.0.3
pigments, v0.18.0
tool-bar, v0.1.9

# Dev
No dev packages
```

**Comment by Glavin001** [comment] 2015-10-27 21:10
@seronal Atom Beautify definitely lists `event-kit` as a dependency, see https://github.com/Glavin001/atom-beautify/blob/master/package.json#L74

So my recommendation would be to reinstall Atom Beautify and/or restart Atom.

**Comment by martinaware** [comment] 2015-11-04 09:09
Got this :

Error: Cannot find module 'C:\Users\t375678\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\emissary'
    at Module._resolveFilename (module.js:334:15)
    at Function.Module._resolveFilename (C:\Users\t375678\AppData\Local\atom\app-1.1.0\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:284:25)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Object.<anonymous> (C:\Users\t375678\.atom\packages\atom-beautify\src\beautify.coffee:447:16)
    at Object.<anonymous> (C:\Users\t375678\.atom\packages\atom-beautify\src\beautify.coffee:2:1)
    at Module._compile (module.js:428:26)
    at Object.defineProperty.value [as .coffee] (C:\Users\t375678\AppData\Local\atom\app-1.1.0\resources\app.asar\src\compile-cache.js:169:21)
    at Module.load (module.js:353:32)
    at Function.Module._load (module.js:308:12)
    at Module.require (module.js:363:17)
    at require (module.js:382:17)
    at Package.module.exports.Package.requireMainModule (C:\Users\t375678\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package.js:725:34)
    at Package.module.exports.Package.activateConfig (C:\Users\t375678\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package.js:250:14)
    at Package.module.exports.Package.activateNow (C:\Users\t375678\AppData\Local\atom\app-1.1.0\resources\app.asar\src\package.js:228:14)

**Comment by Glavin001** [comment] 2015-11-04 14:23
@martinaware please confirm that you have updated to the latest Atom Beautify, which no longer uses emissary.
