### ISSUE TITLE
Error installing package

### ISSUE THREAD

**Issue by tiago7alves** [Glavin001/atom-beautify#204] opened 2015-02-04 13:02 UTC
While installing atom-beautify using Atom package manager I get the following error:
```
npm ERR! git clone git://github.com/ariya/esprima.git Cloning into bare repository '/Users/tiagoalves/.atom/.node-gyp/.atom/.apm/_git-remotes/git-github-com-ariya-esprima-git-9077e517'...
npm ERR! git clone git://github.com/ariya/esprima.git fatal: read error: Operation timed out
npm ERR! Darwin 14.0.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Applications/Atom.app/Contents/Resources/app/apm/.apmrc" "--userconfig" "/Users/tiagoalves/.atom/.apmrc" "install" "/private/var/folders/t6/gw_y3h2j1d50s81vt4vrbp2w0000gq/T/d-11514-35617-1d7dd6h/package.tgz" "--target=0.20.0" "--arch=x64"
npm ERR! node v0.10.35
npm ERR! npm  v2.3.0
npm ERR! code 128

npm ERR! Command failed: Cloning into bare repository '/Users/tiagoalves/.atom/.node-gyp/.atom/.apm/_git-remotes/git-github-com-ariya-esprima-git-9077e517'...
npm ERR! fatal: read error: Operation timed out
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/t6/gw_y3h2j1d50s81vt4vrbp2w0000gq/T/apm-install-dir-11514-35617-1j4pip0/npm-debug.log
```

The installation fails and I am not able to use the package.

**Comment by Bodhiz** [comment] 2015-02-04 13:28
@tiago7alves Are you behind a proxy ?

**Comment by tiago7alves** [comment] 2015-02-04 14:17
I was but then I disconnected from VPN and tried again. Still the same error.

**Comment by assertnotnull** [comment] 2015-02-04 16:03
I have the same error.
The actual path git:// is no longer valid it seems.
Either git@ or http://

**Comment by billiam13s** [comment] 2015-02-06 14:06
I have the same problem 

It seen like that github.com/ariya/esprima.git repo doesn't exits and when visiting by url, it get redirect to https://github.com/jquery/esprima

**Comment by assertnotnull** [comment] 2015-02-06 14:29
Oh you're right i didn't notice that

**Comment by tiago7alves** [comment] 2015-02-06 16:12
@billiam13s so how can we solve this? I want to solve this but I don't see any approach.
Maybe we can change the project dependency that uses github.com/ariya/esprima.git repo?

**Comment by billiam13s** [comment] 2015-02-06 16:42
@tiago7alves I am sorry. I only start using atom last week and would like to use this package as well. I have no knowledge on atom package development. I think it might be just changing the project dependency that sample. We need to verify `github.com/ariya/esprima.git` and `github.com/jquery/esprima.git` are the same thing, but with ariya is missing I have no idea.

**Comment by tiago7alves** [comment] 2015-02-11 10:44
@billiam13s I cloned the project, ran **npm install** and checked every **package.json** file.
The module that requires **esprima** is **js-yaml** and its dependencies are:

```
"dependencies": {
    "argparse": "~ 0.1.11",
    "esprima": "~ 1.0.2"
}
```

Since **esprima** module is registered in **npm** repository as https://www.npmjs.com/package/esprima*, how does it resolve to *git://github.com/ariya/esprima.git when downloading the package using **apm**?

**Comment by billiam13s** [comment] 2015-02-11 14:19
@tiago7alves Last night, I finally install PHP_Beautifier my own machine(Mac) at home, and were able to install atom-beautify. Then I wonder what where is wrong with my work machine(Ubuntu), with some try on `git clone`, I can only clone via HTTPS not SSH. It turn out my work firewall is blocking all SSH traffic, finally when I switch to the unrestricted network. I was able to install the package. I guess for some reason, when installing dependencies are install via HTTPS over SSH. Hope this help you. Good luck.

**Comment by Glavin001** [comment] 2015-03-10 13:50
### Possible solution by @VeitSanner:
See https://github.com/Glavin001/atom-beautify/issues/214#issuecomment-75367660

> Following steps helped:
>
1. Uninstall *atom-beautify*.
2. Close *Atom* editor.
3. Open *Terminal* and execute `apm install atom-beautify`.
4. Open *Atom* editor.
>
> *P.S.: Installing within Atom editor did not work either.*

**Comment by jackmaney** [comment] 2015-03-10 16:44
I have the same problem, and the solution above did not help. I got the same stack trace on the command line.

**Comment by aarongundel** [comment] 2015-03-11 16:39
After reviewing my npm debug log, I think this is actually due to the analytics-node dependency.  I think @billiam13s was on track -- if you're in a place where the git protocol is blocked, you won't be able to install atom-beautify.  analytics-node has a dependency down the line for node-degenerator.  Node-degenerator depends on esprima -- but it specifies that dependency in an unfriendly way.  I have created a pull request there https://github.com/TooTallNate/node-degenerator/pull/1 to address this long term.  Short term, I suppose one could clone the atom-beautify repo and remove that dependency, npm install, and install manually.  That's a lot of pain, but I don't see another way at this point, short of @Glavin001 removing the dependency for the time being, or installing somewhere the git protocol is available.

**Comment by aarongundel** [comment] 2015-03-11 17:03
Ok, so here's my workaround -- this worked for me.

first...

    git clone https://github.com/Glavin001/atom-beautify.git && cd atom-beautify

then edit package.json, remove the line for the dependency on analytics-node

then..

    npm install
    apm link

restart atom.

**Comment by MetaMemoryT** [comment] 2015-03-11 17:17
The commit is merged, would we need a version bump to `TooTallNate/node-degenerator` in order to get install from atom working again?

**Comment by aarongundel** [comment] 2015-03-11 17:21
I think so, yes.  Also, deleted my previous workaround.  Didn't take into account obvious dependencies within the code itself.

**Comment by aarongundel** [comment] 2015-03-11 17:57
Version bump is completed, install works for me now.

**Comment by MetaMemoryT** [comment] 2015-03-11 18:29
I still get:

```
npm ERR! Failed to clone git+https://github.com/ariya/esprima.git#a41a40b49046747b3af57341cda048bbd3d9df79 from https://github.com/ariya/esprima.git Cloning into 'C:\Users\Sean\AppData\Local\Temp\npm-2996-0d414730\git-cache-8be4a0fd06f1\a41a40b49046747b3af57341cda048bbd3d9df79'...
npm ERR! Failed to clone git+https://github.com/ariya/esprima.git#a41a40b49046747b3af57341cda048bbd3d9df79 from https://github.com/ariya/esprima.git fatal: '/c/Users/Sean/.atom/.apm/_git-remotes/https-github-com-ariya-esprima-git-1bd370f9/C:\Users\Sean\.atom\.apm\_git-remotes\https-github-com-ariya-esprima-git-1bd370f9' does not appear to be a git repository
npm ERR! Failed to clone git+https://github.com/ariya/esprima.git#a41a40b49046747b3af57341cda048bbd3d9df79 from https://github.com/ariya/esprima.git fatal: Could not read from remote repository.
npm ERR! Failed to clone git+https://github.com/ariya/esprima.git#a41a40b49046747b3af57341cda048bbd3d9df79 from https://github.com/ariya/esprima.git 
npm ERR! Failed to clone git+https://github.com/ariya/esprima.git#a41a40b49046747b3af57341cda048bbd3d9df79 from https://github.com/ariya/esprima.git Please make sure you have the correct access rights
npm ERR! Failed to clone git+https://github.com/ariya/esprima.git#a41a40b49046747b3af57341cda048bbd3d9df79 from https://github.com/ariya/esprima.git and the repository exists.
npm ERR! Failed to clone git+https://github.com/ariya/esprima.git#a41a40b49046747b3af57341cda048bbd3d9df79 from https://github.com/ariya/esprima.git 
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Users\\Sean\\AppData\\Local\\atom\\app-0.184.0\\resources\\app\\apm\\bin\\\\node.exe" "C:\\Users\\Sean\\AppData\\Local\\atom\\app-0.184.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Sean\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Sean\\.atom\\.apmrc" "install" "C:\\Users\\Sean\\AppData\\Local\\Temp\\d-115211-3532-12py6u1\\package.tgz" "--target=0.21.0" "--arch=ia32" "--msvs_version=2013"
npm ERR! node v0.10.35
npm ERR! npm  v2.5.1
npm ERR! code 128

npm ERR! Command failed: Cloning into 'C:\Users\Sean\AppData\Local\Temp\npm-2996-0d414730\git-cache-8be4a0fd06f1\a41a40b49046747b3af57341cda048bbd3d9df79'...
npm ERR! fatal: '/c/Users/Sean/.atom/.apm/_git-remotes/https-github-com-ariya-esprima-git-1bd370f9/C:\Users\Sean\.atom\.apm\_git-remotes\https-github-com-ariya-esprima-git-1bd370f9' does not appear to be a git repository
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>
```

**Comment by jackmaney** [comment] 2015-03-11 20:30
The install worked. Thank you! This is a package that I love on my home installation of Atom, and I'm glad that I'm now able to use it at work, too.

**Comment by aarongundel** [comment] 2015-03-11 20:41
Great @jackmaney!  @MetaMemoryT clone the repo and run

    npm install

inside.  Post your npm-debug.log.

**Comment by MetaMemoryT** [comment] 2015-03-13 17:16
npm-debug.log: https://gist.githubusercontent.com/MetaMemoryT/e4e5f900cc85c8d305ef/raw/gistfile1.txt

**Comment by aarongundel** [comment] 2015-03-13 17:59
@MetaMemoryT From your log...

    6499 error Failed to clone git+https://github.com/ariya/esprima.git#a41a40b49046747b3af57341cda048bbd3d9df79 from https://github.com/ariya/esprima.git Cloning into 'C:\Users\Sean\AppData\Local\Temp\npm-5544-4782edbc\git-cache-334001f102e0\a41a40b49046747b3af57341cda048bbd3d9df79'...
    6499 error Failed to clone git+https://github.com/ariya/esprima.git#a41a40b49046747b3af57341cda048bbd3d9df79 from https://github.com/ariya/esprima.git fatal: '/c/Users/Sean/AppData/Roaming/npm-cache/_git-remotes/https-github-com-ariya-esprima-git-1bd370f9/C:\Users\Sean\AppData\Roaming\npm-cache\_git-remotes\https-github-com-ariya-esprima-git-1bd370f9' does not appear to be a git repository
    6499 error Failed to clone git+https://github.com/ariya/esprima.git#a41a40b49046747b3af57341cda048bbd3d9df79 from https://github.com/ariya/esprima.git fatal: Could not read from remote repository.
    6499 error Failed to clone git+https://github.com/ariya/esprima.git#a41a40b49046747b3af57341cda048bbd3d9df79 from https://github.com/ariya/esprima.git
    6499 error Failed to clone git+https://github.com/ariya/esprima.git#a41a40b49046747b3af57341cda048bbd3d9df79 from https://github.com/ariya/esprima.git Please make sure you have the correct access rights
    6499 error Failed to clone git+https://github.com/ariya/esprima.git#a41a40b49046747b3af57341cda048bbd3d9df79 from https://github.com/ariya/esprima.git and the repository exists.

Your log seems to indicate that you can't access https://github.com/ariya/esprima.git -- can you confirm this is true?

**Comment by MetaMemoryT** [comment] 2015-03-13 18:02
I can access in in my web browser, gives me a redirect to https://github.com/ariya/esprima

**Comment by aarongundel** [comment] 2015-03-13 18:19
@MetaMemoryT 

Try this

    npm cache clean

And try to install after that.

**Comment by MetaMemoryT** [comment] 2015-03-13 19:52
now I got:

```
 Failed to activate package named 'atom-beautify' Error: Cannot find module 'ast-types'
  at Module._resolveFilename (module.js:351:15)
  at Function.exports.register.Module._resolveFilename (C:\Users\Sean\AppData\Local\atom\app-0.184.0\resources\app\src\module-cache.js:383:52)
  at Function.Module._load (module.js:293:25)
  at Module.require (module.js:380:17)
  at require (module.js:399:17)
```

**Comment by aarongundel** [comment] 2015-03-13 19:59
I'm running out of thoughts here, but try to

    npm cache clean
    npm update

Then try to install the package.  It seems like the issue is limited to your local install of npm.

**Comment by MetaMemoryT** [comment] 2015-03-13 21:12
still same problem, but look at this part of the error message:

```
npm ERR! fatal: '/c/Users/Sean/AppData/Roaming/npm-cache/_git-remotes/https-github-com-ariya-esprima-git-1bd370f9/C:\Users\Sean\AppData\Roaming\npm-cache\_git-remotes\https-github-com-ariya-esprima-git-1bd370f9' does not appear to be a git repository
```

It looks like a windows specific problem, somehow its appending the `/c/...` path to the `C:\...` path, to determine the directory.

```
$ npm --version
2.5.1
```

**Comment by aarongundel** [comment] 2015-03-13 21:31
@MetaMemoryT  The pathing is cygwin-ish behavior.  I'm not sure where npm is installed for you; but if I had to guess, I'd say cygwin is somehow involved.  But that's only a guess.

**Comment by MetaMemoryT** [comment] 2015-03-13 21:46
I opened up a bug:

https://github.com/npm/npm/issues/7623

tried to update npm but trashed my system, will keep trying.

**Comment by aarongundel** [comment] 2015-03-13 21:48
Ok, happy hunting @MetaMemoryT .  @Glavin001  I think it's safe to close this issue.

**Comment by Glavin001** [comment] 2015-03-16 04:47
Great discussion everyone! Thanks for resolving this.

**Closed by Glavin001** 2015-03-16 04:47 UTC
Labels: high priority, third-party bug
