### ISSUE TITLE
Installing “atom-beautify@0.28.7” failed.

### ISSUE THREAD

**Issue by gios** [Glavin001/atom-beautify#431] opened 2015-06-29 09:49 UTC
When I installing atom-beautify@0.28.7, I have some error.
![screenshot from 2015-06-26 20 38 06](https://cloud.githubusercontent.com/assets/6967294/8405458/4b50ea3a-1e5d-11e5-879a-4aae5d995aae.png)

**Comment by Glavin001** [comment] 2015-06-29 23:26
Duplicate of #423.

I recommend that you forward this over to https://github.com/ForbesLindesay/spawn-sync (the package that is breaking) and hopefully someone can help there.

**Closed by Glavin001** 2015-06-29 23:26 UTC

**Comment by Glavin001** [comment] 2015-06-29 23:27
See https://github.com/ForbesLindesay/spawn-sync/issues/11

**Comment by ForbesLindesay** [comment] 2015-07-16 17:03
The latest version of spawn-sync should be much more resilient (even on older versions of node.js).  If anyone was struggling with this issue I'd encourage them to have another go.

**Comment by Glavin001** [comment] 2015-07-16 17:24
Great, thanks @ForbesLindesay !
