### ISSUE TITLE
Error: Could not get Shell Environment. Exit code: 1, Signal: null

### ISSUE THREAD

**Issue by imdaadz** [Glavin001/atom-beautify#1640] opened 2017-05-03 12:36 UTC
# Description

When I save file to beautify then I see a spinner for a while and then this error bubble pops up to the top-right of Atom

This is what error look like:

```
Error: Could not get Shell Environment. Exit code: 1, Signal: null
    at ChildProcess.<anonymous> (/Users/imdaadz/.atom/packages/atom-beautify/src/beautifiers/beautifier.coffee:174:31)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor` or  Save it
3. This beautified code does not look right!

# Debug

Here is a link to the `debug.md` Gist: [debug.md](https://gist.github.com/imdaadz/54a1909577ac2ae849ba53c11481723e)

# Checklist

I have:
- [x] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [x] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [x] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue

**Comment by Glavin001** [comment] 2017-05-06 21:02
Closing as duplicate of https://github.com/Glavin001/atom-beautify/issues/1113

Please discuss of at https://github.com/Glavin001/atom-beautify/issues/1113

**Closed by Glavin001** 2017-05-06 21:02 UTC
