### ISSUE TITLE
"Beautify on save" in javascript erases file then saves then crashes

### ISSUE THREAD

**Issue by peteyhayman** [Glavin001/atom-beautify#1805] opened 2017-08-11 05:52 UTC
Apologies this seems to be a duplicate issue, although it looks as though it has been closed
https://github.com/Glavin001/atom-beautify/issues/924

**Comment by mateddy** [comment] 2017-08-11 07:17
Also happen on json files.

**Comment by Glavin001** [comment] 2017-08-12 01:29
This may be caused by https://github.com/Glavin001/atom-beautify/issues/1721 . I will close this as a duplicate of either #1721 or #924.

Workaround: disable "Beautify On Save" until fixed.

---

Fix published to v0.30.5

**Closed by Glavin001** 2017-08-12 01:29 UTC
