### ISSUE TITLE
Unable to update to the latest version

### ISSUE THREAD

**Issue by krishnat2** [Glavin001/atom-beautify#913] opened 2016-04-12 13:23 UTC
I am trying to update to the latest version, it spins on forever and does not complete. Please advice.

**Comment by Glavin001** [comment] 2016-04-12 15:56
Duplicate of https://github.com/Glavin001/atom-beautify/issues/896 and many others and is a bug of Atom's Settings-View which can be found at https://github.com/atom/settings-view/issues/532

**Closed by Glavin001** 2016-04-12 15:56 UTC
