### ISSUE TITLE
Cannot Upgrade to atom-beautify@0.21.3

### ISSUE THREAD

**Issue by VeitSanner** [Glavin001/atom-beautify#214] opened 2015-02-15 11:55 UTC
# Description
When I try to upgrade from version 0.21.2 to 0.21.3 because git cannot be found on my Mac (OS X 10.10.2). When I run apm -v in terminal I get the following information:

```
apm  0.137.0
npm  2.3.0
node 0.10.35
python 2.7.6
git 2.3.0
```

I used homebrew to install git.

# Error Message
```
Updating to “atom-beautify@0.21.3” failed.Hide output…
Failed to install atom-beautify because Git was not found.

The atom-beautify package has module dependencies that cannot be installed without Git.

You need to install Git and add it to your path environment variable in order to install this package.

Run apm -v after installing Git to see what version has been detected.
```

**Comment by GradyD** [comment] 2015-02-18 15:24
I am getting an error on this also. when I run `apm -v` I get

```
apm  0.137.0
npm  2.3.0
node 0.10.35
python
git 1.9.5.msysgit.0
visual studio 2010
```

I am on windows 7 64bit. The stack trace is,

```
Updating to “atom-beautify@0.21.3” failed.Hide output…

npm ERR! git clone git://github.com/ariya/esprima.git Cloning into bare repository 'C:\Users\gduncan\.atom\.apm\_git-remotes\git-github-com-ariya-esprima-git-9077e517'...
npm ERR! git clone git://github.com/ariya/esprima.git fatal: unable to connect to github.com:
npm ERR! git clone git://github.com/ariya/esprima.git github.com[0: 192.30.252.128]: errno=No error
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\gduncan\\AppData\\Local\\atom\\app-0.179.0\\resources\\app\\apm\\bin\\\\node.exe" "C:\\Users\\gduncan\\AppData\\Local\\atom\\app-0.179.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\gduncan\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\gduncan\\.atom\\.apmrc" "install" "C:\\Users\\gduncan\\AppData\\Local\\Temp\\d-115118-203188-128dw6x\\package.tgz" "--target=0.21.0" "--arch=ia32" "--msvs_version=2010"
npm ERR! node v0.10.35
npm ERR! npm  v2.3.0
npm ERR! code 128

npm ERR! Command failed: Cloning into bare repository 'C:\Users\gduncan\.atom\.apm\_git-remotes\git-github-com-ariya-esprima-git-9077e517'...
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.252.128]: errno=No error
npm ERR! 
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>


Compiler tools not found
Packages that depend on modules that contain C/C++ code will fail to install.
Read here for instructions on installing Python and Visual Studio.
Run apm install --check after installing to test compiling a native module.
```
When I run `apm install --check` I get this stack trace,

```
Checking for native build tools
c:\Users\gduncan\AppData\Local\atom\app-0.180.0\resources\app\apm\lib\install.js:77
      useStrictSsl = (_ref = this.npm.config.get('strict-ssl')) != null ? _ref
                                     ^
TypeError: Cannot read property 'config' of undefined
    at Install.module.exports.Install.installNode (c:\Users\gduncan\AppData\Local\atom\app-0.180.0\resources\app\apm\lib
\install.js:77:38)
    at Install.installNode (c:\Users\gduncan\AppData\Local\atom\app-0.180.0\resources\app\apm\lib\install.js:3:61)
    at Install.module.exports.Install.checkNativeBuildTools (c:\Users\gduncan\AppData\Local\atom\app-0.180.0\resources\a
pp\apm\lib\install.js:559:19)
    at Install.module.exports.Install.run (c:\Users\gduncan\AppData\Local\atom\app-0.180.0\resources\app\apm\lib\install
.js:724:21)
    at Object.module.exports.run (c:\Users\gduncan\AppData\Local\atom\app-0.180.0\resources\app\apm\lib\apm-cli.js:209:3
2)
    at Object.<anonymous> (c:\Users\gduncan\AppData\Local\atom\app-0.180.0\resources\app\apm\lib\cli.js:6:7)
    at Object.<anonymous> (c:\Users\gduncan\AppData\Local\atom\app-0.180.0\resources\app\apm\lib\cli.js:17:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

Not exactly sure if this is the same issue or not but I have the plugin installed and its working, just like to be on the latest version.

**Comment by VeitSanner** [comment] 2015-02-21 11:25
Following steps helped:

1. Uninstall *atom-beautify*.
2. Close *Atom* editor.
3. Open *Terminal* and execute `apm install atom-beautify`.
4. Open *Atom* editor.

*P.S.: Installing within *Atom* editor did not work either.

**Comment by GradyD** [comment] 2015-02-24 03:14
I tried to uninstall within Atom and I get this error, 

`Failed to delete atom-beautify: ENOTEMPTY, directory not empty 'C:\Users\gduncan\.atom\packages\atom-beautify\examples\simple-jsbeautifyrc\ruby'`

When I actually browse to that location it tells me that `\examples\*` does not exist. 

When I run `apm uninstall` it errors and gives me the same error message.

**Comment by Glavin001** [comment] 2015-03-10 13:49
Duplicate of #204.
Please continue your group discussion with the others at #204. I hope that you are able to find a reproducible solution. Unfortunately, I am not able to reproduce this issue myself, and this is also not an Atom Beautify issue, but an APM or NPM issue, and Atom Beautify is just one of those cases that makes it arise. I hope we can work through this. Thank you for your patients.

**Closed by Glavin001** 2015-03-10 13:49 UTC
