### ISSUE TITLE
EJS Beautification support

### ISSUE THREAD

**Issue by karloluis** [Glavin001/atom-beautify#136] opened 2014-11-05 09:50 UTC
It might be hard to deal with given that it will work as a html an html and js thing running over eachother but hey. It'd be awesome and you'd be one of the few if not the most complete out there yet.

**Comment by Glavin001** [comment] 2015-03-10 14:02
@prettydiff is this on your roadmap?

**Comment by prettydiff** [comment] 2015-03-10 17:03
Yes, assign this issue to me.  I believe EJS is:
http://www.embeddedjs.com/

I was looking at something similar this morning, but with different delimiters: {@ and @} instead of <% and %>, but all the logic appears the same. The delimiters not a concern (even the angle braces).  The big challenge I am thinking through is:

    <% } else { %>

It is challenging because that is a closing and opening of a block consolidated to a single markup token. HTML/XML does not have such a concept, because markup tokens either close or open blocks or neither.  I will think through this.

The worst case scenario if I cannot find an answer is that children of such blocks do not receive an additional level of indentation.

**Comment by Glavin001** [comment] 2015-03-10 17:07
I think everything between `<%` and `%>` is JavaScript, so could you have it use two separate beautifiers? HTML for the main code and omit anything inside of the `<% %>`s and then process those next with JavaScript? I think trying to handle it as one language may become complicated.

**Comment by Glavin001** [comment] 2015-03-16 05:07
@prettydiff has added support so this is not high priority.

**Comment by Glavin001** [comment] 2015-03-16 05:22
@karloluis can you please provide an example file that I can use for my tests. Once I have passing tests I will be publishing. Thank you.

**Comment by Glavin001** [comment] 2015-05-01 07:33
Will be supported, thanks to @prettydiff, when #282 is released.

**Comment by Glavin001** [comment] 2015-05-03 01:28
Published to v0.25.0

This is a very big release with lots of internal changes and (hopefully) no breaking changes. Please let me know if you are experiencing any unusual behaviour / breaking changes after updating. Thank you.

**Closed by Glavin001** 2015-05-03 01:28 UTC
Labels: add-language, feature, high priority

**Comment by adammeola01** [comment] 2017-01-05 04:32
gives me a pinwheel dialogue that doesn't terminate...

**Comment by prettydiff** [comment] 2017-01-05 05:08
@adammeola01 Would you mind creating a new issue for that and following the template with the required information?  That way we can triage and diagnose it properly.

**Comment by mywarr** [comment] 2017-01-08 12:12
@prettydiff 
had the same problem these days,
the problem only occurs on js-beautify; pretty diff is all ok.

procedure to reproduce this:
1. open an empty file
2. select grammer as HTML (Angular)
3. ctrl + option + b = endless in progress wheel spinning.

it got me a endless pinwheel even when i run the command  "Atom Beautify: Help Debug Editor" .
so i ran debug editor on pretty diff, hope it helps.

https://gist.github.com/mywarr/7c051e94c3a573382a3f2254c1462dae

**Comment by Glavin001** [comment] 2017-01-25 02:07
@adammeola01 and @mywarr : your issue is a duplicate of #1432.

Published fix of #1432 to v0.29.17! Thank you for your patience!
