### ISSUE TITLE
brace-style: collapse-preserve-inline not working for js inside <script>

### ISSUE THREAD

**Issue by aahoo** [Glavin001/atom-beautify#1012] opened 2016-06-10 08:08 UTC
### Description

When using js-beautifier, the option `brace-style: collapse-preserve-inline` does not work for js code embedded in <script> tags in `.html` file. It works perfectly in pure `.js` files.

**test.html**:

``` html
<script>

    var obj = { foo: bar };

</script>
```

**test.js:**

``` js
var obj = { foo: bar };
```
### Expected Results

The beautified code should have looked like:

``` js
var obj = { foo: bar };
```
### Steps to Reproduce
1. Add the HTML code to Atom editor in a .html file
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!
### Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/aahoo/126260de77ee1fb2465d431faa76d3a2

**Comment by prettydiff** [comment] 2016-06-10 15:09
Would you please paste into a gist the debug.md file generated by Atom Beautify?  This will allow us to reproduce the problem and ensure we can inform the right people or provide the most precise resolution.

**Comment by aahoo** [comment] 2016-06-11 11:01
I updated the original post. Sorry for being lazy the first time :)

**Comment by danielrvt** [comment] 2016-11-27 11:49
how can I get this debug.md ?

**Comment by prettydiff** [comment] 2016-11-27 19:15
@danielrvt https://github.com/Glavin001/atom-beautify/blob/master/docs/troubleshooting.md

**Comment by Glavin001** [comment] 2017-01-03 02:12
Looks like https://github.com/Glavin001/atom-beautify/issues/457#issuecomment-204499368 will address this issue, by allowing both HTML and JavaScript beautifiers to be applied to the same file. Closing as a duplicate feature request.

**Closed by Glavin001** 2017-01-03 02:12 UTC
Labels: question
