### ISSUE TITLE
Atom Beautify could not determine a supported beautifier to handle this file with grammar "Velocity (HTML)" and extension "vm". 

### ISSUE THREAD

**Issue by zetay** [Glavin001/atom-beautify#874] opened 2016-03-28 03:07 UTC
### Description

Atom Beautify could not determine a supported beautifier to handle this file with grammar "Velocity (HTML)" and extension "vm".

**Comment by prettydiff** [comment] 2016-03-28 11:52
I have an issue open to work on this https://github.com/prettydiff/prettydiff/issues/280

I have not gotten to it yet.

**Comment by Glavin001** [comment] 2016-07-24 15:00
Duplicate of #522.

**Closed by Glavin001** 2016-07-24 15:00 UTC
