### ISSUE TITLE
Code Folding error

### ISSUE THREAD

**Issue by kasik96** [Glavin001/atom-beautify#615] opened 2015-10-21 13:01 UTC
When i have folded some code. And if press Beautify, folding open its self and doesnt come back to closed. It will be handfull after Beautify ends, load the folding. :)
![screen shot 2015-10-21 at 14 57 11](https://cloud.githubusercontent.com/assets/7235992/10637197/75ad3350-7804-11e5-9656-ec69c28b923f.png)
![screen shot 2015-10-21 at 14 57 19](https://cloud.githubusercontent.com/assets/7235992/10637198/75d65942-7804-11e5-8fbb-1c8b12c550b1.png)

**Comment by Glavin001** [comment] 2017-05-28 03:30
Duplicate of #116

**Closed by Glavin001** 2017-05-28 03:30 UTC
