### ISSUE TITLE
{block} or .tpl support

### ISSUE THREAD

**Issue by n8lauscher** [Glavin001/atom-beautify#1368] opened 2016-11-18 15:52 UTC
i search for a way to pimp up my smarty tpl files - but i don´t find a solution. 
Is there a way ?

**Comment by prettydiff** [comment] 2016-11-18 16:20
It looks like smarty is a template language with a site at http://www.smarty.net/

Try passing code samples through Pretty Diff and see if that beautifies the code correctly.  If not we will need a proper beautifier to make this work.  http://prettydiff.com/

**Comment by beingmrkenny** [comment] 2016-11-24 11:00
Pretty diff just handled some smarty code reasonably well when I tried it just now.

**Comment by Glavin001** [comment] 2017-01-03 02:07
Closing as duplicate of https://github.com/Glavin001/atom-beautify/issues/940

**Closed by Glavin001** 2017-01-03 02:07 UTC
Labels: add-language
