### ISSUE TITLE
Atom Beautify could not find a supported beautifier for this file

### ISSUE THREAD

**Issue by NavyaaB** [Glavin001/atom-beautify#1894] opened 2017-10-18 14:19 UTC
Atom Beautify could not determine a supported beautifier to handle this file with grammar
"Null Grammar" and extension "dust". I would like to request support for this file and its language.

**Comment by prettydiff** [comment] 2017-10-18 15:05
Duplicate of https://github.com/Glavin001/atom-beautify/issues/392

**Closed by prettydiff** 2017-10-18 15:05 UTC
