### ISSUE TITLE
Bug when beautify .swig file

### ISSUE THREAD

**Issue by Mr-Binary** [Glavin001/atom-beautify#1148] opened 2016-08-23 03:46 UTC
# Description

Actually, the file has been pre-beautified.
And I have disabled both the `beautify on save` and `Disable Beautifing Language`
It will always beautify this file, and messy all the things which is very frustrated. 
# Let me show you the original(without beautify) one first

```
    <footer id="footer" class="footer">
      <div class="footer-inner">
        {% include '_partials/footer.swig' %}
        {% include '_scripts/third-party/analytics/busuanzi-counter.swig' %}
        {% block footer %}{% endblock %}
      </div>
    </footer>

    <div class="back-to-top">
      <i class="fa fa-arrow-up">111</i>
    </div>
  </div>

  {% include '_scripts/vendors.swig' %}
  {% include '_scripts/commons.swig' %}

  {% set scheme_script = '_scripts/schemes/' + theme.scheme | lower + '.swig' %}
  {% include scheme_script %}

  {% block script_extra %}{% endblock %}

  {% include '_scripts/boostrap.swig' %}

  {% include '_scripts/third-party/comments.swig' %}
  {% include '_scripts/third-party/tinysou.swig' %}
  {% include '_scripts/third-party/localsearch.swig' %}
  {% include '_scripts/third-party/mathjax.swig' %}
  {% include '_scripts/third-party/lean-analytics.swig' %}
  {% include '_scripts/baidu-push.swig' %}
```
# This is what happens when it finishes beautifying even I disallow that

```
    <footer id="footer" class="footer">
      <div class="footer-inner">
        {% include '_partials/footer.swig' %} {% include '_scripts/third-party/analytics/busuanzi-counter.swig' %} {% block footer %}{% endblock %}
      </div>
    </footer>

    <div class="back-to-top">
      <i class="fa fa-arrow-up">111</i>
    </div>
  </div>

  {% include '_scripts/vendors.swig' %} {% include '_scripts/commons.swig' %} {% set scheme_script = '_scripts/schemes/' + theme.scheme | lower + '.swig' %} {% include scheme_script %} {% block script_extra %}{% endblock %} {% include '_scripts/boostrap.swig'
  %} {% include '_scripts/third-party/comments.swig' %} {% include '_scripts/third-party/tinysou.swig' %} {% include '_scripts/third-party/localsearch.swig' %} {% include '_scripts/third-party/mathjax.swig' %} {% include '_scripts/third-party/lean-analytics.swig'
  %} {% include '_scripts/baidu-push.swig' %}
```

This is minifying...not beautifying...
# Steps to Reproduce
1. edit the file .swig
2. save it
3. It will auto-beautify without lookinig for the options
# A workaround

Disable the whole plugin...

I have worked with lots of templating language these days, always encounter bugs like this, I will report the rest file type when I work with them again.

**Comment by prettydiff** [comment] 2016-08-23 10:41
Would you mind producing the debug.md file and saving it into a gist?  I cannot reproduce this defect in Pretty Diff.  It looks like what I get when I use http://jsbeautifier.org/

It is not really minifying, but rather just collapsing the indentation between the template tags into a single space.  If it turns out to be a JS Beautify bug I will let that project know.

**Comment by Mr-Binary** [comment] 2016-08-23 12:50
Hi, I'd love to, but to be honest, how to produce that debug.md....xD If I upload the original file, could it help?

**Comment by prettydiff** [comment] 2016-08-23 13:09
https://github.com/Glavin001/atom-beautify/blob/0212f49c83a9eec9fd777bd0d8f3f98af9d5d5e9/docs/troubleshooting.md

**Comment by Mr-Binary** [comment] 2016-08-23 14:07
[https://gist.github.com/anonymous/c0dc03dd555d4afa26c227bc1c10ef5a](https://gist.github.com/anonymous/c0dc03dd555d4afa26c227bc1c10ef5a)

[https://gist.github.com/anonymous/a1f67c14b33fbcb752f2aabb68a04717](https://gist.github.com/anonymous/a1f67c14b33fbcb752f2aabb68a04717)

Sorry, first time, don't know the exact procedure, seems that it has already create a anonymous gist for me. Check the above two. Both for same file.

I have find some kind of pattern, when the file is full of template syntax, the result will look good most of the time,  if there are remarkable HTML part mixup, the result will mess up.

**Comment by Glavin001** [comment] 2017-01-01 04:13
Closing as a JS-Beautify bug: https://github.com/beautify-web/js-beautify/issues/1003

**Closed by Glavin001** 2017-01-01 04:13 UTC
Labels: third-party bug
